import {
  Worker,
  WorkerDocument,
  WorkerSkillEntry,
  ServiceCategory,
  Booking,
  CommunityBooking,
  CooperativeFund,
  ToolBankItem,
  WorkerEmergencyAidRequest,
  NotificationItem,
  PlatformConfig,
  User,
  CommunityChannel,
  CommunityMessage,
  SocietyData,
  FederationData,
  PlatformAuditLog,
} from '../types';

export const INITIAL_CONFIG: PlatformConfig = {
  workerSharePercent: 70,
  societySharePercent: 5,
  cooperativeFundPercent: 25,
  matchingWeights: {
    skillCompatibility: 35,
    proficiency: 20,
    distance: 20,
    availability: 15,
    workloadBalance: 10,
  },
};

export const DEMO_USERS: Record<string, User> = {
  customer: {
    id: 'user_cust_01',
    name: 'Ananya Deshmukh',
    email: 'ananya.d@example.com',
    phone: '+91 98201 44521',
    role: 'customer',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    address: 'Flat 402, Tower B, Green Residency, Baner Rd',
    societyId: 'soc_gr',
    societyName: 'Green Residency',
    federationId: 'fed_mcf',
    federationName: 'Maharashtra Community Federation',
    designation: 'Resident & Household Member',
  },
  worker: {
    id: 'w_rahul',
    name: 'Rahul Sharma',
    email: 'rahul.s@coop.org',
    phone: '+91 97112 88402',
    role: 'worker',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    address: 'Coop Workers Colony, Sector 4, Baner',
    societyId: 'soc_gr',
    societyName: 'Green Residency',
    federationId: 'fed_mcf',
    federationName: 'Maharashtra Community Federation',
    designation: 'Master Plumber · Green Residency',
    tradeProfession: 'Plumbing',
  },
  society_manager: {
    id: 'user_soc_mgr_01',
    name: 'Priya Sharma',
    email: 'priya.sharma@greenresidency.coop',
    phone: '+91 98204 11983',
    role: 'society_manager',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    address: 'Society Management Office, Green Residency',
    societyId: 'soc_gr',
    societyName: 'Green Residency',
    federationId: 'fed_mcf',
    federationName: 'Maharashtra Community Federation',
    designation: 'Society Manager (Green Residency)',
  },
  federation_admin: {
    id: 'user_fed_admin_01',
    name: 'Meera Nambiar',
    email: 'meera.nambiar@maharashtracoop.org',
    phone: '+91 98223 77410',
    role: 'federation_admin',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    address: 'Federation Apex House, Senapati Bapat Road, Pune',
    societyName: 'Maharashtra Community Federation',
    federationId: 'fed_mcf',
    federationName: 'Maharashtra Community Federation',
    designation: 'Federation Admin (Maharashtra Region)',
  },
  federation_manager: {
    id: 'user_fed_admin_01',
    name: 'Meera Nambiar',
    email: 'meera.nambiar@maharashtracoop.org',
    phone: '+91 98223 77410',
    role: 'federation_admin',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    address: 'Federation Apex House, Senapati Bapat Road, Pune',
    societyName: 'Maharashtra Community Federation',
    federationId: 'fed_mcf',
    federationName: 'Maharashtra Community Federation',
    designation: 'Federation Admin (Maharashtra Region)',
  },
};

export const INITIAL_FEDERATIONS: FederationData[] = [
  {
    id: 'fed_mcf',
    name: 'Maharashtra Community Federation',
    region: 'Western Maharashtra Urban Zone (Pune & Pimpri Chinchwad)',
    totalSocieties: 8,
    totalWorkers: 27,
    monthlyGMV: 2840000,
    federationReliefFund: 482500,
    crossSocietyRequests: 84,
    leadCoordinator: 'Meera Nambiar',
    adminId: 'user_fed_admin_01',
    adminName: 'Meera Nambiar',
    adminPhone: '+91 98223 77410',
    adminEmail: 'meera.nambiar@maharashtracoop.org',
    adminAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
  },
];

export interface SocietyManagerInfo {
  id: string;
  name: string;
  email: string;
  phone: string;
  avatar: string;
  societyId: string;
  societyName: string;
  workersCount: number;
}

export const INITIAL_SOCIETY_MANAGERS: SocietyManagerInfo[] = [
  {
    id: 'mgr_priya',
    name: 'Priya Sharma',
    email: 'priya.sharma@greenresidency.coop',
    phone: '+91 98204 11983',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    societyId: 'soc_gr',
    societyName: 'Green Residency',
    workersCount: 8,
  },
  {
    id: 'mgr_amit',
    name: 'Amit Shah',
    email: 'amit.shah@lakeview.coop',
    phone: '+91 98221 44090',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    societyId: 'soc_ls',
    societyName: 'Lakeview Society',
    workersCount: 4,
  },
  {
    id: 'mgr_neha',
    name: 'Neha Rao',
    email: 'neha.rao@sunrise.coop',
    phone: '+91 94200 66120',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    societyId: 'soc_sa',
    societyName: 'Sunrise Apartments',
    workersCount: 3,
  },
  {
    id: 'mgr_rahul',
    name: 'Rahul Mehta',
    email: 'rahul.mehta@palmheights.coop',
    phone: '+91 98901 77332',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    societyId: 'soc_ph',
    societyName: 'Palm Heights',
    workersCount: 3,
  },
  {
    id: 'mgr_kavita',
    name: 'Kavita Nair',
    email: 'kavita.nair@riverview.coop',
    phone: '+91 93701 55219',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    societyId: 'soc_rv',
    societyName: 'River View',
    workersCount: 2,
  },
  {
    id: 'mgr_sanjay',
    name: 'Sanjay Patil',
    email: 'sanjay.patil@harmonytowers.coop',
    phone: '+91 98234 88102',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    societyId: 'soc_ht',
    societyName: 'Harmony Towers',
    workersCount: 3,
  },
  {
    id: 'mgr_deepali',
    name: 'Deepali Kulkarni',
    email: 'deepali.k@silveroaks.coop',
    phone: '+91 94211 33490',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    societyId: 'soc_so',
    societyName: 'Silver Oaks',
    workersCount: 2,
  },
  {
    id: 'mgr_vikram',
    name: 'Vikram Shinde',
    email: 'vikram.s@emeraldheights.coop',
    phone: '+91 98902 66741',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    societyId: 'soc_eh',
    societyName: 'Emerald Heights',
    workersCount: 2,
  },
];

export const INITIAL_SOCIETIES: SocietyData[] = [
  {
    id: 'soc_gr',
    name: 'Green Residency',
    code: 'SOC-PUN-01',
    address: 'Baner Main Road, Pune 411045',
    totalHouseholds: 420,
    activeWorkersCount: 8,
    activeBookingsCount: 6,
    monthlyRevenue: 184500,
    satisfactionRate: 4.92,
    societyFundBalance: 48200,
    coordinatorName: 'Priya Sharma',
    coordinatorPhone: '+91 98204 11983',
    managerId: 'mgr_priya',
    managerName: 'Priya Sharma',
    managerPhone: '+91 98204 11983',
    managerEmail: 'priya.sharma@greenresidency.coop',
    managerAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    federationId: 'fed_mcf',
    federationName: 'Maharashtra Community Federation',
  },
  {
    id: 'soc_ls',
    name: 'Lakeview Society',
    code: 'SOC-PUN-02',
    address: 'Pashan Lake Road, Pune 411021',
    totalHouseholds: 510,
    activeWorkersCount: 4,
    activeBookingsCount: 8,
    monthlyRevenue: 246000,
    satisfactionRate: 4.88,
    societyFundBalance: 61500,
    coordinatorName: 'Amit Shah',
    coordinatorPhone: '+91 98221 44090',
    managerId: 'mgr_amit',
    managerName: 'Amit Shah',
    managerPhone: '+91 98221 44090',
    managerEmail: 'amit.shah@lakeview.coop',
    managerAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    federationId: 'fed_mcf',
    federationName: 'Maharashtra Community Federation',
  },
  {
    id: 'soc_sa',
    name: 'Sunrise Apartments',
    code: 'SOC-PUN-03',
    address: 'Paud Road, Kothrud, Pune 411038',
    totalHouseholds: 340,
    activeWorkersCount: 3,
    activeBookingsCount: 4,
    monthlyRevenue: 132000,
    satisfactionRate: 4.85,
    societyFundBalance: 33000,
    coordinatorName: 'Neha Rao',
    coordinatorPhone: '+91 94200 66120',
    managerId: 'mgr_neha',
    managerName: 'Neha Rao',
    managerPhone: '+91 94200 66120',
    managerEmail: 'neha.rao@sunrise.coop',
    managerAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    federationId: 'fed_mcf',
    federationName: 'Maharashtra Community Federation',
  },
  {
    id: 'soc_ph',
    name: 'Palm Heights',
    code: 'SOC-PUN-04',
    address: 'High Street, Balewadi, Pune 411045',
    totalHouseholds: 480,
    activeWorkersCount: 3,
    activeBookingsCount: 7,
    monthlyRevenue: 218000,
    satisfactionRate: 4.90,
    societyFundBalance: 54500,
    coordinatorName: 'Rahul Mehta',
    coordinatorPhone: '+91 98901 77332',
    managerId: 'mgr_rahul',
    managerName: 'Rahul Mehta',
    managerPhone: '+91 98901 77332',
    managerEmail: 'rahul.mehta@palmheights.coop',
    managerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    federationId: 'fed_mcf',
    federationName: 'Maharashtra Community Federation',
  },
  {
    id: 'soc_rv',
    name: 'River View',
    code: 'SOC-PUN-05',
    address: 'DP Road, Aundh, Pune 411007',
    totalHouseholds: 310,
    activeWorkersCount: 2,
    activeBookingsCount: 3,
    monthlyRevenue: 98000,
    satisfactionRate: 4.82,
    societyFundBalance: 24500,
    coordinatorName: 'Kavita Nair',
    coordinatorPhone: '+91 93701 55219',
    managerId: 'mgr_kavita',
    managerName: 'Kavita Nair',
    managerPhone: '+91 93701 55219',
    managerEmail: 'kavita.nair@riverview.coop',
    managerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    federationId: 'fed_mcf',
    federationName: 'Maharashtra Community Federation',
  },
  {
    id: 'soc_ht',
    name: 'Harmony Towers',
    code: 'SOC-PUN-06',
    address: 'Dange Chowk, Wakad, Pune 411057',
    totalHouseholds: 620,
    activeWorkersCount: 3,
    activeBookingsCount: 9,
    monthlyRevenue: 285000,
    satisfactionRate: 4.93,
    societyFundBalance: 71250,
    coordinatorName: 'Sanjay Patil',
    coordinatorPhone: '+91 98234 88102',
    managerId: 'mgr_sanjay',
    managerName: 'Sanjay Patil',
    managerPhone: '+91 98234 88102',
    managerEmail: 'sanjay.patil@harmonytowers.coop',
    managerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    federationId: 'fed_mcf',
    federationName: 'Maharashtra Community Federation',
  },
  {
    id: 'soc_so',
    name: 'Silver Oaks',
    code: 'SOC-PUN-07',
    address: 'NDA Road, Bavdhan, Pune 411021',
    totalHouseholds: 390,
    activeWorkersCount: 2,
    activeBookingsCount: 4,
    monthlyRevenue: 145000,
    satisfactionRate: 4.86,
    societyFundBalance: 36250,
    coordinatorName: 'Deepali Kulkarni',
    coordinatorPhone: '+91 94211 33490',
    managerId: 'mgr_deepali',
    managerName: 'Deepali Kulkarni',
    managerPhone: '+91 94211 33490',
    managerEmail: 'deepali.k@silveroaks.coop',
    managerAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    federationId: 'fed_mcf',
    federationName: 'Maharashtra Community Federation',
  },
  {
    id: 'soc_eh',
    name: 'Emerald Heights',
    code: 'SOC-PUN-08',
    address: 'Phase 1 Road, Hinjewadi, Pune 411057',
    totalHouseholds: 450,
    activeWorkersCount: 2,
    activeBookingsCount: 5,
    monthlyRevenue: 172000,
    satisfactionRate: 4.89,
    societyFundBalance: 43000,
    coordinatorName: 'Vikram Shinde',
    coordinatorPhone: '+91 98902 66741',
    managerId: 'mgr_vikram',
    managerName: 'Vikram Shinde',
    managerPhone: '+91 98902 66741',
    managerEmail: 'vikram.s@emeraldheights.coop',
    managerAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    federationId: 'fed_mcf',
    federationName: 'Maharashtra Community Federation',
  },
];

export const INITIAL_PLATFORM_METRICS = {
  totalUsers: 14820,
  totalWorkers: 1160,
  totalSocieties: 40,
  totalFederations: 2,
  allTimeGMV: 38400000,
  platformUptimePercent: 99.98,
  activeSessions: 428,
};

export const INITIAL_AUDIT_LOGS: PlatformAuditLog[] = [
  {
    id: 'AUD-910',
    timestamp: '2026-09-19 18:45:12',
    actor: 'Suresh Menon (Society Manager)',
    role: 'society_manager',
    action: 'ADD_WORKER',
    actionType: 'ADD_WORKER',
    details: 'New Worker Registered: Deepak Shinde (WRK-PUN-104) under Green Residency Cooperative',
    ipAddress: '172.16.0.45',
    workerId: 'w_deepak',
    workerName: 'Deepak Shinde',
    societyId: 'soc_green',
    societyName: 'Green Residency Cooperative',
    managerId: 'user_soc_mgr_01',
    managerName: 'Suresh Menon',
    newStatus: 'PENDING',
    notes: 'Level 1 Personal KYC registered at estate office desk.',
  },
  {
    id: 'AUD-909',
    timestamp: '2026-09-19 17:30:00',
    actor: 'Priya Sharma (Society Manager)',
    role: 'society_manager',
    action: 'VERIFY_PERSONAL_KYC',
    actionType: 'VERIFY_PERSONAL_KYC',
    details: 'Personal KYC Verified: Aadhaar and local residence confirmed for Ramesh Kumar',
    ipAddress: '172.16.0.48',
    workerId: 'w_ramesh',
    workerName: 'Ramesh Kumar',
    societyId: 'soc_green',
    societyName: 'Green Residency Cooperative',
    managerId: 'user_soc_mgr_01',
    managerName: 'Priya Sharma',
    previousStatus: 'PENDING',
    newStatus: 'VERIFIED',
    notes: 'Physical government photo ID and biometric verification completed.',
  },
  {
    id: 'AUD-908',
    timestamp: '2026-09-19 16:15:45',
    actor: 'Vikramaditya Patil (Society Manager)',
    role: 'society_manager',
    action: 'ADD_WORKER_SKILL',
    actionType: 'ADD_WORKER_SKILL',
    details: 'New Skill Added: Inverter & Solar Installation (4 yrs experience) for Worker Amit Kumar',
    ipAddress: '172.16.0.52',
    workerId: 'w_amit',
    workerName: 'Amit Kumar',
    societyId: 'soc_green',
    societyName: 'Green Residency Cooperative',
    managerId: 'user_soc_mgr_01',
    managerName: 'Vikramaditya Patil',
    skillName: 'Inverter & Solar Installation',
  },
  {
    id: 'AUD-907',
    timestamp: '2026-09-19 15:00:22',
    actor: 'Anjali Deshmukh (Society Manager)',
    role: 'society_manager',
    action: 'VERIFY_WORKER_SKILL',
    actionType: 'VERIFY_WORKER_SKILL',
    details: 'Worker Skill Verified: Master Carpentry & Woodworking validated for Rajesh Verma',
    ipAddress: '172.16.0.60',
    workerId: 'w_rajesh',
    workerName: 'Rajesh Verma',
    societyId: 'soc_silver',
    societyName: 'Silver Oak Enclave',
    managerId: 'user_soc_mgr_03',
    managerName: 'Anjali Deshmukh',
    skillName: 'Master Carpentry',
    newStatus: 'VERIFIED',
    notes: 'Practical workshop demonstration observed and passed.',
  },
  {
    id: 'AUD-906',
    timestamp: '2026-09-19 14:10:05',
    actor: 'Rohit Kulkarni (Society Manager)',
    role: 'society_manager',
    action: 'UPDATE_WORKER_DOCS',
    actionType: 'UPDATE_WORKER_DOCS',
    details: 'Worker Documents Updated: Police Verification Certificate approved for Sunita Rao',
    ipAddress: '172.16.0.71',
    workerId: 'w_sunita',
    workerName: 'Sunita Rao',
    societyId: 'soc_palm',
    societyName: 'Palm Meadows Society',
    managerId: 'user_soc_mgr_02',
    managerName: 'Rohit Kulkarni',
    previousStatus: 'UNDER_REVIEW',
    newStatus: 'MANAGER_VERIFIED',
    notes: 'Official police verification certificate valid through 2027 confirmed.',
  },
  {
    id: 'AUD-905',
    timestamp: '2026-09-19 13:05:50',
    actor: 'Suresh Menon (Society Manager)',
    role: 'society_manager',
    action: 'ASSIGN_WORKER_JOB',
    actionType: 'ASSIGN_WORKER_JOB',
    details: 'Worker Assigned to Job: Priya Patel assigned to Emergency Electrical Repair #BKG-1048',
    ipAddress: '172.16.0.45',
    workerId: 'w_priya',
    workerName: 'Priya Patel',
    societyId: 'soc_green',
    societyName: 'Green Residency Cooperative',
    managerId: 'user_soc_mgr_01',
    managerName: 'Suresh Menon',
    bookingId: 'BKG-1048',
  },
  {
    id: 'AUD-904',
    timestamp: '2026-09-19 11:40:18',
    actor: 'Rohit Kulkarni (Society Manager)',
    role: 'society_manager',
    action: 'REJECT_WORKER',
    actionType: 'REJECT_WORKER',
    details: 'Worker Rejected by Manager: Dinesh Thorat — Reason: Incomplete residential address proof and unverified identity document',
    ipAddress: '172.16.0.71',
    workerId: 'w_dinesh_temp',
    workerName: 'Dinesh Thorat',
    societyId: 'soc_palm',
    societyName: 'Palm Meadows Society',
    managerId: 'user_soc_mgr_02',
    managerName: 'Rohit Kulkarni',
    previousStatus: 'PENDING',
    newStatus: 'MANAGER_REJECTED',
    reason: 'Incomplete residential address proof and unverified identity document. Requested updated electricity bill.',
  },
  {
    id: 'AUD-903',
    timestamp: '2026-09-19 10:20:00',
    actor: 'Anjali Deshmukh (Society Manager)',
    role: 'society_manager',
    action: 'CHANGE_WORKER_STATUS',
    actionType: 'CHANGE_WORKER_STATUS',
    details: 'Worker Status Changed: Ganesh Hegde set to Online / Available for emergency plumbing dispatch',
    ipAddress: '172.16.0.60',
    workerId: 'w_ganesh',
    workerName: 'Ganesh Hegde',
    societyId: 'soc_silver',
    societyName: 'Silver Oak Enclave',
    managerId: 'user_soc_mgr_03',
    managerName: 'Anjali Deshmukh',
    previousStatus: 'offline',
    newStatus: 'online',
  },
  {
    id: 'AUD-902',
    timestamp: '2026-09-19 09:15:30',
    actor: 'Suresh Menon (Society Manager)',
    role: 'society_manager',
    action: 'UPDATE_WORKER_PROFILE',
    actionType: 'UPDATE_WORKER_PROFILE',
    details: 'Worker Profile Updated: Updated contact number and tools kit checklist for Vikram Joshi',
    ipAddress: '172.16.0.45',
    workerId: 'w_vikram',
    workerName: 'Vikram Joshi',
    societyId: 'soc_green',
    societyName: 'Green Residency Cooperative',
    managerId: 'user_soc_mgr_01',
    managerName: 'Suresh Menon',
    notes: 'Worker acquired certified insulated toolkit.',
  },
  {
    id: 'AUD-901',
    timestamp: '2026-09-18 17:50:00',
    actor: 'Meera Nambiar (Federation Manager)',
    role: 'federation_manager',
    action: 'FUND_ALLOCATION',
    actionType: 'FUND_ALLOCATION',
    details: 'Approved ₹60,000 monthly emergency reserve allocation for Western Federation',
    ipAddress: '192.168.1.84',
    managerName: 'Meera Nambiar',
  },
];

export const INITIAL_COMMUNITY_CHANNELS: CommunityChannel[] = [
  // Society Channels for Residents
  {
    id: 'comm_gr_updates',
    name: 'Society Announcements',
    scope: 'society',
    memberCount: 420,
    description: 'Official notices, maintenance schedules, and security advisories from Society Management.',
    lastActive: '10 min ago',
  },
  {
    id: 'comm_gr_maintenance',
    name: 'Home Maintenance & Tips',
    scope: 'society',
    memberCount: 185,
    description: 'Resident discussions, DIY maintenance suggestions, and reliable cooperative service reviews.',
    lastActive: '25 min ago',
  },
  {
    id: 'comm_gr_group_requests',
    name: 'Group Service Drives',
    scope: 'society',
    memberCount: 94,
    description: 'Propose and coordinate apartment-wide service batches to unlock 20% collective discounts.',
    lastActive: '1 hr ago',
  },
  // Profession Channels for Workers
  {
    id: 'trade_electricians',
    name: 'Electricians Guild',
    scope: 'profession',
    professionCategory: 'Electrical',
    memberCount: 23,
    description: 'High voltage troubleshooting, circuit breaker standards, and rooftop solar safety notes.',
    lastActive: '5 min ago',
  },
  {
    id: 'trade_plumbers',
    name: 'Plumbers Guild',
    scope: 'profession',
    professionCategory: 'Plumbing',
    memberCount: 18,
    description: 'Copper vs CPVC piping, non-destructive leak tracing, and pre-monsoon storm drain readiness.',
    lastActive: '12 min ago',
  },
  {
    id: 'trade_carpenters',
    name: 'Carpenters & Joiners',
    scope: 'profession',
    professionCategory: 'Carpentry',
    memberCount: 11,
    description: 'Concealed hinge adjustments, modular furniture fittings, and timber restoration techniques.',
    lastActive: '45 min ago',
  },
  {
    id: 'trade_painters',
    name: 'Painters & Polishers',
    scope: 'profession',
    professionCategory: 'Painting',
    memberCount: 14,
    description: 'Weather-guard exterior coats, damp wall primer chemistry, and airless sprayer maintenance.',
    lastActive: '2 hrs ago',
  },
];

export const INITIAL_COMMUNITY_MESSAGES: CommunityMessage[] = [
  // Society messages (Customer view)
  {
    id: 'msg-soc-01',
    channelId: 'comm_gr_updates',
    authorName: 'Suresh Menon',
    authorRole: 'society_manager',
    authorAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    content: 'Notice: Pre-monsoon overhead water tank cleaning and pipeline descaling is scheduled for this Saturday starting 10:00 AM. Please register via the group booking drive on your dashboard for discounted flat servicing.',
    timestamp: 'Today, 09:30 AM',
    isOfficial: true,
  },
  {
    id: 'msg-soc-02',
    channelId: 'comm_gr_maintenance',
    authorName: 'Kunal Kulkarni (Flat A-101)',
    authorRole: 'customer',
    content: 'Has anyone replaced their master bathroom shower cartridge recently? Any recommendation on whether to replace the diverter body or just the internal ceramic spindle?',
    timestamp: 'Today, 11:15 AM',
  },
  {
    id: 'msg-soc-03',
    channelId: 'comm_gr_maintenance',
    authorName: 'Rahul Sharma (Master Plumber)',
    authorRole: 'worker',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    authorProfession: 'Master Plumber',
    content: 'Namaste Kunal ji. In 90% of Kohler and Jaquar fixtures installed in Green Residency Tower A, replacing just the 35mm ceramic spindle resolves dripping and temperature stickiness without hacking any wall tiles.',
    timestamp: 'Today, 11:40 AM',
  },
  {
    id: 'msg-soc-04',
    channelId: 'comm_gr_maintenance',
    authorName: 'Ananya Deshmukh (Flat B-402)',
    authorRole: 'customer',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    content: 'Sunita ji from the cleaning collective deep sanitized our kitchen tiles and chimney yesterday. Extraordinary quality and very respectful work!',
    timestamp: 'Today, 01:20 PM',
  },
  // Trade messages (Worker view)
  {
    id: 'msg-w-01',
    channelId: 'trade_electricians',
    authorName: 'Priya Patel',
    authorRole: 'worker',
    authorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
    authorProfession: 'Licensed Wireman Grade 1',
    content: 'Has anyone worked with the latest Schneider Neo modular switchboard model installed in Wing C? Remember that the dual earthing screw has a secondary plastic retainer clip.',
    timestamp: 'Today, 10:10 AM',
  },
  {
    id: 'msg-w-02',
    channelId: 'trade_electricians',
    authorName: 'Vikram Joshi',
    authorRole: 'worker',
    authorAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&auto=format&fit=crop&q=80',
    authorProfession: 'Electrical Technician',
    content: 'Yes Priya ji, verified on yesterday’s job. Don’t force it with a standard flathead screwdriver — use the #1 insulated Phillips bit from the cooperative tool bank.',
    timestamp: 'Today, 10:25 AM',
  },
  {
    id: 'msg-w-03',
    channelId: 'trade_plumbers',
    authorName: 'Amit Kumar',
    authorRole: 'worker',
    authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    authorProfession: 'Plumber',
    content: 'The Baner Tool Bank has received 2 new electric pipe threading machines (1/2" to 2"). Perfect for upcoming pre-monsoon riser renovations.',
    timestamp: 'Today, 08:45 AM',
  },
  {
    id: 'msg-w-04',
    channelId: 'trade_plumbers',
    authorName: 'Rahul Sharma',
    authorRole: 'worker',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    authorProfession: 'Master Plumber',
    content: 'Excellent update Amit. Let’s make sure we clean the die heads with cutting oil before returning to the depot custodian.',
    timestamp: 'Today, 09:05 AM',
  },
];

export const INITIAL_SERVICES: ServiceCategory[] = [
  {
    id: 'plumbing',
    name: 'Plumbing',
    iconName: 'Wrench',
    description: 'Pipes, taps, leak detection, drainage, bathroom fittings',
    basePrice: 400,
    problems: [
      'Leaking pipe under sink',
      'Tap repair / replacement',
      'Drain blockage / slow drainage',
      'Bathroom shower / geyser line leak',
      'Water tank overflow repair',
      'Flush cistern malfunction',
      'Something else',
    ],
  },
  {
    id: 'electrical',
    name: 'Electrical',
    iconName: 'Zap',
    description: 'Wiring, circuit trips, switchboards, fixtures, fan repair',
    basePrice: 450,
    problems: [
      'Circuit breaker tripping repeatedly',
      'Switchboard spark / loose connection',
      'Ceiling fan noisy / slow speed',
      'Inverter / battery backup setup',
      'Appliance short-circuit check',
      'Smart switch / lighting installation',
      'Something else',
    ],
  },
  {
    id: 'cleaning',
    name: 'Cleaning',
    iconName: 'Sparkles',
    description: 'Eco-friendly deep sanitization, kitchen, washrooms & sofa',
    basePrice: 650,
    problems: [
      'Deep kitchen grease removal',
      'Bathroom intensive tile descaling',
      'Sofa shampooing & upholstery revival',
      'Full 2BHK/3BHK sanitization',
      'Balcony & window track wash',
      'Something else',
    ],
  },
  {
    id: 'carpentry',
    name: 'Carpentry',
    iconName: 'Hammer',
    description: 'Furniture repair, door locks, hinges, custom cabinetry',
    basePrice: 500,
    problems: [
      'Door lock jammed / latch replacement',
      'Wardrobe hinge loose or misaligned',
      'Bed frame squeak / slat repair',
      'IKEA/modular furniture assembly',
      'Balcony pigeon net wooden framing',
      'Something else',
    ],
  },
  {
    id: 'painting',
    name: 'Painting',
    iconName: 'Paintbrush',
    description: 'Wall dampness treatment, patch touchups, full room coating',
    basePrice: 800,
    problems: [
      'Wall dampness & peeling paint patch',
      'Touch-up painting before tenancy handover',
      'Single bedroom fresh emulsion coat',
      'Balcony exterior weather-guard',
      'Something else',
    ],
  },
  {
    id: 'repairs',
    name: 'Appliance Repairs',
    iconName: 'Cpu',
    description: 'Washing machines, microwave, RO water filter, refrigerators',
    basePrice: 550,
    problems: [
      'RO water purifier filter change & leak',
      'Washing machine drum not spinning',
      'Refrigerator cooling insufficient',
      'Microwave not heating food',
      'Chimney suction reduced',
      'Something else',
    ],
  },
  {
    id: 'elderly_care',
    name: 'Elderly Assistance',
    iconName: 'HeartHandshake',
    description: 'Compassionate assistance, mobility escort, medicine runs',
    basePrice: 350,
    problems: [
      'Companion for evening garden walk',
      'Medicine refill pick-up & pharmacy errand',
      'Wheelchair transfer assistance',
      'Doctor appointment accompaniment',
      'Something else',
    ],
  },
  {
    id: 'moving_help',
    name: 'Moving & Heavy Help',
    iconName: 'Package',
    description: 'Intra-society heavy shifting, cartons, furniture relocation',
    basePrice: 600,
    problems: [
      'Shifting wardrobe/sofa across rooms',
      'Loading cartons into transit vehicle',
      'Dismantling heavy gym equipment',
      'Apartment handover cleanup help',
      'Something else',
    ],
  },
  {
    id: 'community_services',
    name: 'Community Services',
    iconName: 'Users',
    description: 'Society storm drain desilting, tree pruning, solar panel wash',
    basePrice: 1200,
    problems: [
      'Society storm drain pre-monsoon desilting',
      'Tree branch pruning near power cables',
      'Rooftop solar panel dust washing',
      'Common area pathway paver block repair',
      'Something else',
    ],
  },
];

export const SOCIETY_COORDINATES: Record<string, { lat: number; lng: number; area: string }> = {
  soc_gr: { lat: 18.5590, lng: 73.7868, area: 'Baner Rd, Sector 4' },
  soc_ls: { lat: 18.5350, lng: 73.7920, area: 'Pashan Lake Enclave' },
  soc_sa: { lat: 18.5074, lng: 73.8077, area: 'Paud Road, Kothrud' },
  soc_ph: { lat: 18.5750, lng: 73.7720, area: 'High Street, Balewadi' },
  soc_rv: { lat: 18.5600, lng: 73.8050, area: 'DP Road, Aundh' },
  soc_ht: { lat: 18.5980, lng: 73.7650, area: 'Dange Chowk, Wakad' },
  soc_so: { lat: 18.5150, lng: 73.7740, area: 'NDA Road, Bavdhan' },
  soc_eh: { lat: 18.5910, lng: 73.7380, area: 'Phase 1, Hinjawadi' },
};

export function createDefaultWorkerDocuments(
  workerId: string,
  _workerName?: string,
  isFullyVerified: boolean = true
): WorkerDocument[] {
  return [
    {
      id: `doc_${workerId}_id`,
      workerId,
      documentType: 'identity',
      title: 'Government Aadhaar / ID Card',
      fileUrl: 'https://images.unsplash.com/photo-1633409381658-a0c21b3dc704?w=600&auto=format&fit=crop&q=80',
      uploadedAt: '2026-08-14',
      status: isFullyVerified ? 'APPROVED' : 'PENDING',
      reviewedBy: isFullyVerified ? 'Priya Sharma (Society Manager)' : undefined,
      reviewedAt: isFullyVerified ? '2026-08-15' : undefined,
      reviewNotes: isFullyVerified ? 'Identity confirmed with government UIDAI registry.' : 'Awaiting Society Manager review.',
    },
    {
      id: `doc_${workerId}_addr`,
      workerId,
      documentType: 'address',
      title: 'Residential Address Proof',
      fileUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80',
      uploadedAt: '2026-08-14',
      status: isFullyVerified ? 'APPROVED' : 'PENDING',
      reviewedBy: isFullyVerified ? 'Priya Sharma (Society Manager)' : undefined,
      reviewedAt: isFullyVerified ? '2026-08-15' : undefined,
      reviewNotes: isFullyVerified ? 'Verified resident in society local ward block.' : 'Awaiting physical address verification.',
    },
    {
      id: `doc_${workerId}_skill`,
      workerId,
      documentType: 'skill',
      title: 'Trade Skill Certification (NCVT)',
      fileUrl: 'https://images.unsplash.com/photo-1589330694653-ded6df03f754?w=600&auto=format&fit=crop&q=80',
      uploadedAt: '2026-08-14',
      status: isFullyVerified ? 'APPROVED' : 'PENDING',
      reviewedBy: isFullyVerified ? 'Priya Sharma (Society Manager)' : undefined,
      reviewedAt: isFullyVerified ? '2026-08-15' : undefined,
      reviewNotes: isFullyVerified ? 'Trade skill certified Level 4.' : 'Awaiting trade assessment verification.',
    },
    {
      id: `doc_${workerId}_mem`,
      workerId,
      documentType: 'membership',
      title: 'Cooperative Collective Membership',
      fileUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=600&auto=format&fit=crop&q=80',
      uploadedAt: '2026-08-14',
      status: isFullyVerified ? 'APPROVED' : 'PENDING',
      reviewedBy: isFullyVerified ? 'Priya Sharma (Society Manager)' : undefined,
      reviewedAt: isFullyVerified ? '2026-08-15' : undefined,
      reviewNotes: isFullyVerified ? 'Member in good standing with cooperative society share.' : 'Awaiting cooperative share confirmation.',
    },
    {
      id: `doc_${workerId}_bg`,
      workerId,
      documentType: 'background',
      title: 'Background Verification & Police Clearance',
      fileUrl: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=600&auto=format&fit=crop&q=80',
      uploadedAt: '2026-08-14',
      status: isFullyVerified ? 'APPROVED' : 'PENDING',
      reviewedBy: isFullyVerified ? 'Priya Sharma (Society Manager)' : undefined,
      reviewedAt: isFullyVerified ? '2026-08-15' : undefined,
      reviewNotes: isFullyVerified
        ? 'Clean local police verification record.'
        : 'Awaiting local precinct police clearance verification stamp.',
    },
  ];
}

const RAW_WORKERS: Worker[] = [
  // 1. GREEN RESIDENCY (Manager: Priya Sharma) - 8 Workers
  {
    id: 'w_rahul',
    name: 'Rahul Sharma',
    phone: '+91 97112 88402',
    email: 'rahul.s@coop.org',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    profession: 'Plumbing',
    societyId: 'soc_gr',
    societyName: 'Green Residency',
    managerId: 'mgr_priya',
    managerName: 'Priya Sharma',
    rating: 4.88,
    totalReviews: 142,
    completedJobs: 139,
    hourlyRate: 350,
    distanceKm: 2.1,
    availability: 'online',
    currentWorkload: 35,
    proficiencyScore: 94,
    skills: ['Plumbing', 'Appliance Repairs', 'General Maintenance'],
    certificates: ['Govt NCVT Plumber Level 4', 'Advanced Water Line Safety'],
    verificationStatus: 'VERIFIED',
    kycDocumentsCount: 4,
    localVerificationStatus: 'verified',
    cooperativeMemberId: 'COP-PUN-4412',
    joinedDate: '2023-04-12',
    bio: 'Dedicated Master Plumber with 8+ years experience. Expert in copper piping and non-destructive leak tracing.',
  },
  {
    id: 'w_priya',
    name: 'Priya Patel',
    phone: '+91 94231 66720',
    email: 'priya.p@coop.org',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
    profession: 'Electrical',
    societyId: 'soc_gr',
    societyName: 'Green Residency',
    managerId: 'mgr_priya',
    managerName: 'Priya Sharma',
    rating: 4.96,
    totalReviews: 215,
    completedJobs: 211,
    hourlyRate: 400,
    distanceKm: 2.8,
    availability: 'online',
    currentWorkload: 55,
    proficiencyScore: 97,
    skills: ['Electrical', 'Appliance Repairs', 'Solar Inverters'],
    certificates: ['Licensed Wireman Grade 1', 'Solar Rooftop Certified'],
    verificationStatus: 'VERIFIED',
    kycDocumentsCount: 4,
    localVerificationStatus: 'verified',
    cooperativeMemberId: 'COP-PUN-1094',
    joinedDate: '2022-11-04',
    bio: 'Licensed Wireman & electrical troubleshooter with 10 years experience across residential townships.',
  },
  {
    id: 'w_amit',
    name: 'Amit Kumar',
    phone: '+91 98902 33104',
    email: 'amit.k@coop.org',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    profession: 'Plumbing',
    societyId: 'soc_gr',
    societyName: 'Green Residency',
    managerId: 'mgr_priya',
    managerName: 'Priya Sharma',
    rating: 4.79,
    totalReviews: 89,
    completedJobs: 86,
    hourlyRate: 320,
    distanceKm: 1.4,
    availability: 'online',
    currentWorkload: 25,
    proficiencyScore: 88,
    skills: ['Plumbing', 'Drainage', 'Sanitation'],
    certificates: ['Vocational ITI Plumbing Certificate'],
    verificationStatus: 'VERIFIED',
    kycDocumentsCount: 4,
    localVerificationStatus: 'verified',
    cooperativeMemberId: 'COP-PUN-3820',
    joinedDate: '2023-08-19',
    bio: 'Punctual and reliable neighbourhood plumber. Quick turnaround on all household fittings.',
  },
  {
    id: 'w_sunita',
    name: 'Sunita Devi',
    phone: '+91 93701 44589',
    email: 'sunita.d@coop.org',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&auto=format&fit=crop&q=80',
    profession: 'Cleaning',
    societyId: 'soc_gr',
    societyName: 'Green Residency',
    managerId: 'mgr_priya',
    managerName: 'Priya Sharma',
    rating: 4.92,
    totalReviews: 324,
    completedJobs: 320,
    hourlyRate: 300,
    distanceKm: 1.6,
    availability: 'online',
    currentWorkload: 40,
    proficiencyScore: 93,
    skills: ['Cleaning', 'Deep Sanitization', 'Elderly Assistance'],
    certificates: ['Hygienic Sanitation Master Class', 'CPR & First Aid'],
    verificationStatus: 'VERIFIED',
    kycDocumentsCount: 4,
    localVerificationStatus: 'verified',
    cooperativeMemberId: 'COP-PUN-2911',
    joinedDate: '2023-02-10',
    bio: 'Leading the Cooperative Women Cleaners Collective. Trusted by 200+ households in Baner.',
  },
  {
    id: 'w_rajesh',
    name: 'Rajesh Verma',
    phone: '+91 98811 77245',
    email: 'rajesh.v@coop.org',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&auto=format&fit=crop&q=80',
    profession: 'Carpentry',
    societyId: 'soc_gr',
    societyName: 'Green Residency',
    managerId: 'mgr_priya',
    managerName: 'Priya Sharma',
    rating: 4.75,
    totalReviews: 96,
    completedJobs: 92,
    hourlyRate: 380,
    distanceKm: 3.5,
    availability: 'online',
    currentWorkload: 20,
    proficiencyScore: 86,
    skills: ['Carpentry', 'Furniture Repair', 'Door Locks'],
    certificates: ['Carpentry Craftsmanship Certification'],
    verificationStatus: 'VERIFIED',
    kycDocumentsCount: 4,
    localVerificationStatus: 'verified',
    cooperativeMemberId: 'COP-PUN-5128',
    joinedDate: '2024-01-15',
    bio: 'Specialist in custom modular kitchen adjustments, concealed door hinges, and antique wood restoration.',
  },
  {
    id: 'w_deepa_r',
    name: 'Deepa Rao',
    phone: '+91 98221 33419',
    email: 'deepa.r@coop.org',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&auto=format&fit=crop&q=80',
    profession: 'Painting',
    societyId: 'soc_gr',
    societyName: 'Green Residency',
    managerId: 'mgr_priya',
    managerName: 'Priya Sharma',
    rating: 4.80,
    totalReviews: 64,
    completedJobs: 62,
    hourlyRate: 350,
    distanceKm: 2.2,
    availability: 'online',
    currentWorkload: 15,
    proficiencyScore: 90,
    skills: ['Painting', 'Waterproofing', 'Wall Touch-ups'],
    certificates: ['Master Painters Certification Level 2'],
    verificationStatus: 'VERIFIED',
    kycDocumentsCount: 4,
    localVerificationStatus: 'verified',
    cooperativeMemberId: 'COP-PUN-6014',
    joinedDate: '2024-03-20',
    bio: 'Expert in exterior damp-proof coatings and interior premium emulsions.',
  },
  {
    id: 'w_vikram',
    name: 'Vikram Joshi',
    phone: '+91 98234 11099',
    email: 'vikram.j@gmail.com',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&auto=format&fit=crop&q=80',
    profession: 'Electrical',
    societyId: 'soc_gr',
    societyName: 'Green Residency',
    managerId: 'mgr_priya',
    managerName: 'Priya Sharma',
    rating: 4.85,
    totalReviews: 24,
    completedJobs: 22,
    hourlyRate: 320,
    distanceKm: 2.2,
    availability: 'online',
    currentWorkload: 0,
    proficiencyScore: 86,
    skills: ['Electrical', 'Appliance Repairs', 'Switchboards'],
    certificates: ['ITI Electrical Diploma (Uploaded)'],
    verificationStatus: 'MANAGER_VERIFIED',
    kycDocumentsCount: 5,
    localVerificationStatus: 'verified',
    cooperativeMemberId: 'COP-APP-7721',
    joinedDate: '2026-09-08',
    bio: 'Certified electrical technician endorsed by Green Residency management; awaiting central federation accreditation.',
    managerVerification: {
      verifiedBy: 'Priya Sharma (Society Manager)',
      verifiedAt: '2026-09-15',
      status: 'APPROVED',
      notes: 'All 5 KYC credentials verified, electrical trade competency approved, and endorsed for central Federation accreditation.',
    },
  },
  {
    id: 'w_sneha',
    name: 'Sneha Joshi',
    phone: '+91 94229 88103',
    email: 'sneha.j@gmail.com',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    profession: 'Cleaning',
    societyId: 'soc_gr',
    societyName: 'Green Residency',
    managerId: 'mgr_priya',
    managerName: 'Priya Sharma',
    rating: 0,
    totalReviews: 0,
    completedJobs: 0,
    hourlyRate: 280,
    distanceKm: 3.1,
    availability: 'offline',
    currentWorkload: 0,
    proficiencyScore: 78,
    skills: ['Cleaning', 'Sanitization'],
    certificates: ['Sanitation Worker Certificate (Uploaded)'],
    verificationStatus: 'PENDING',
    kycDocumentsCount: 0,
    localVerificationStatus: 'pending',
    cooperativeMemberId: 'COP-APP-8910',
    joinedDate: '2026-09-10',
    bio: 'New cleaner applicant in Green Residency awaiting Society Manager document check.',
  },

  // 2. LAKEVIEW SOCIETY (Manager: Amit Shah) - 4 Workers
  {
    id: 'w_manoj',
    name: 'Manoj Shinde',
    phone: '+91 98225 66104',
    email: 'manoj.s@lakeview.coop',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    profession: 'Electrical',
    societyId: 'soc_ls',
    societyName: 'Lakeview Society',
    managerId: 'mgr_amit',
    managerName: 'Amit Shah',
    rating: 4.88,
    totalReviews: 112,
    completedJobs: 110,
    hourlyRate: 390,
    distanceKm: 1.8,
    availability: 'online',
    currentWorkload: 40,
    proficiencyScore: 92,
    skills: ['Electrical', 'MCB Repairs', 'Lighting'],
    certificates: ['Licensed Wireman Grade 2'],
    verificationStatus: 'VERIFIED',
    kycDocumentsCount: 4,
    localVerificationStatus: 'verified',
    cooperativeMemberId: 'COP-PUN-2291',
    joinedDate: '2023-05-18',
    bio: 'Senior electrician serving Lakeview Society and Pashan corridor.',
  },
  {
    id: 'w_ramesh',
    name: 'Ramesh Kadam',
    phone: '+91 98901 22489',
    email: 'ramesh.k@lakeview.coop',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    profession: 'Plumbing',
    societyId: 'soc_ls',
    societyName: 'Lakeview Society',
    managerId: 'mgr_amit',
    managerName: 'Amit Shah',
    rating: 4.75,
    totalReviews: 78,
    completedJobs: 76,
    hourlyRate: 330,
    distanceKm: 2.4,
    availability: 'online',
    currentWorkload: 30,
    proficiencyScore: 87,
    skills: ['Plumbing', 'Water Meter Fixing', 'Drain Lines'],
    certificates: ['ITI Plumbing Certification'],
    verificationStatus: 'VERIFIED',
    kycDocumentsCount: 4,
    localVerificationStatus: 'verified',
    cooperativeMemberId: 'COP-PUN-3419',
    joinedDate: '2023-09-02',
    bio: 'Reliable plumber specialized in water tanks and pressure pumps.',
  },
  {
    id: 'w_pooja',
    name: 'Pooja More',
    phone: '+91 94220 77103',
    email: 'pooja.m@lakeview.coop',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
    profession: 'Cleaning',
    societyId: 'soc_ls',
    societyName: 'Lakeview Society',
    managerId: 'mgr_amit',
    managerName: 'Amit Shah',
    rating: 4.91,
    totalReviews: 145,
    completedJobs: 142,
    hourlyRate: 310,
    distanceKm: 1.5,
    availability: 'online',
    currentWorkload: 45,
    proficiencyScore: 94,
    skills: ['Cleaning', 'Kitchen Degreasing', 'Washroom Descaling'],
    certificates: ['Cooperative Hygiene Protocol Level 3'],
    verificationStatus: 'VERIFIED',
    kycDocumentsCount: 4,
    localVerificationStatus: 'verified',
    cooperativeMemberId: 'COP-PUN-4102',
    joinedDate: '2023-06-11',
    bio: 'Experienced cleaning lead with exceptional customer satisfaction rating.',
  },
  {
    id: 'w_nitin',
    name: 'Nitin Deshmukh',
    phone: '+91 98812 55901',
    email: 'nitin.d@lakeview.coop',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&auto=format&fit=crop&q=80',
    profession: 'Carpentry',
    societyId: 'soc_ls',
    societyName: 'Lakeview Society',
    managerId: 'mgr_amit',
    managerName: 'Amit Shah',
    rating: 4.82,
    totalReviews: 83,
    completedJobs: 80,
    hourlyRate: 370,
    distanceKm: 3.0,
    availability: 'online',
    currentWorkload: 20,
    proficiencyScore: 89,
    skills: ['Carpentry', 'Wardrobes', 'Window Meshes'],
    certificates: ['Vocational Carpentry Craft Level 3'],
    verificationStatus: 'FEDERATION_REJECTED',
    rejectionReason: 'Police clearance certificate blurred and needs clear re-upload.',
    kycDocumentsCount: 4,
    localVerificationStatus: 'verified',
    cooperativeMemberId: 'COP-PUN-5520',
    joinedDate: '2024-02-01',
    bio: 'Precision furniture carpentry and door latch fittings in Lakeview Society.',
    managerVerification: {
      verifiedBy: 'Amit Shah (Society Manager)',
      verifiedAt: '2026-09-12',
      status: 'APPROVED',
      notes: 'Local identity and practical trade skills verified.',
    },
    federationVerification: {
      approvedBy: 'Meera Nambiar (Federation Admin)',
      approvedAt: '2026-09-14',
      status: 'REJECTED',
      notes: 'Police clearance certificate blurred and needs clear re-upload.',
    },
  },

  // 3. SUNRISE APARTMENTS (Manager: Neha Rao) - 3 Workers
  {
    id: 'w_anil',
    name: 'Anil Jadhav',
    phone: '+91 98230 44102',
    email: 'anil.j@sunrise.coop',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    profession: 'Plumbing',
    societyId: 'soc_sa',
    societyName: 'Sunrise Apartments',
    managerId: 'mgr_neha',
    managerName: 'Neha Rao',
    rating: 4.90,
    totalReviews: 130,
    completedJobs: 128,
    hourlyRate: 340,
    distanceKm: 2.0,
    availability: 'online',
    currentWorkload: 35,
    proficiencyScore: 93,
    skills: ['Plumbing', 'Bathroom Fixtures', 'Geysers'],
    certificates: ['Govt NCVT Plumber Level 4'],
    verificationStatus: 'VERIFIED',
    kycDocumentsCount: 4,
    localVerificationStatus: 'verified',
    cooperativeMemberId: 'COP-PUN-3180',
    joinedDate: '2023-03-14',
    bio: 'Master Plumber serving Kothrud and Paud Road apartments.',
  },
  {
    id: 'w_sangeeta',
    name: 'Sangeeta Gaikwad',
    phone: '+91 93702 99401',
    email: 'sangeeta.g@sunrise.coop',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&auto=format&fit=crop&q=80',
    profession: 'Cleaning',
    societyId: 'soc_sa',
    societyName: 'Sunrise Apartments',
    managerId: 'mgr_neha',
    managerName: 'Neha Rao',
    rating: 4.86,
    totalReviews: 95,
    completedJobs: 93,
    hourlyRate: 290,
    distanceKm: 1.2,
    availability: 'online',
    currentWorkload: 30,
    proficiencyScore: 91,
    skills: ['Cleaning', 'Balcony Wash', 'Kitchen Sanitization'],
    certificates: ['Hygienic Sanitation Master Class'],
    verificationStatus: 'VERIFIED',
    kycDocumentsCount: 4,
    localVerificationStatus: 'verified',
    cooperativeMemberId: 'COP-PUN-4712',
    joinedDate: '2023-07-22',
    bio: 'Dedicated household sanitization specialist in Sunrise Apartments.',
  },
  {
    id: 'w_sachin',
    name: 'Sachin Sawant',
    phone: '+91 98813 11890',
    email: 'sachin.s@sunrise.coop',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    profession: 'Electrical',
    societyId: 'soc_sa',
    societyName: 'Sunrise Apartments',
    managerId: 'mgr_neha',
    managerName: 'Neha Rao',
    rating: 4.78,
    totalReviews: 62,
    completedJobs: 60,
    hourlyRate: 360,
    distanceKm: 2.7,
    availability: 'online',
    currentWorkload: 25,
    proficiencyScore: 88,
    skills: ['Electrical', 'Ceiling Fans', 'Inverter Wiring'],
    certificates: ['Licensed Wireman Grade 2'],
    verificationStatus: 'VERIFIED',
    kycDocumentsCount: 4,
    localVerificationStatus: 'verified',
    cooperativeMemberId: 'COP-PUN-5901',
    joinedDate: '2024-01-10',
    bio: 'Expert electrician with quick troubleshooting capability.',
  },

  // 4. PALM HEIGHTS (Manager: Rahul Mehta) - 3 Workers
  {
    id: 'w_vikas',
    name: 'Vikas Jagtap',
    phone: '+91 98224 88390',
    email: 'vikas.j@palmheights.coop',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    profession: 'Appliance Repairs',
    societyId: 'soc_ph',
    societyName: 'Palm Heights',
    managerId: 'mgr_rahul',
    managerName: 'Rahul Mehta',
    rating: 4.93,
    totalReviews: 158,
    completedJobs: 155,
    hourlyRate: 420,
    distanceKm: 1.4,
    availability: 'online',
    currentWorkload: 50,
    proficiencyScore: 96,
    skills: ['Appliance Repairs', 'RO Purifiers', 'Washing Machines'],
    certificates: ['Advanced Appliance Diagnostics Diploma'],
    verificationStatus: 'VERIFIED',
    kycDocumentsCount: 4,
    localVerificationStatus: 'verified',
    cooperativeMemberId: 'COP-PUN-1823',
    joinedDate: '2022-10-05',
    bio: 'Lead appliance technician serving Balewadi High Street societies.',
  },
  {
    id: 'w_maya',
    name: 'Maya Bhosale',
    phone: '+91 94228 33109',
    email: 'maya.b@palmheights.coop',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&auto=format&fit=crop&q=80',
    profession: 'Cleaning',
    societyId: 'soc_ph',
    societyName: 'Palm Heights',
    managerId: 'mgr_rahul',
    managerName: 'Rahul Mehta',
    rating: 4.87,
    totalReviews: 104,
    completedJobs: 101,
    hourlyRate: 300,
    distanceKm: 1.9,
    availability: 'online',
    currentWorkload: 35,
    proficiencyScore: 92,
    skills: ['Cleaning', 'Sofa Shampooing', 'Balcony Care'],
    certificates: ['Eco-Clean Sanitation Certificate'],
    verificationStatus: 'VERIFIED',
    kycDocumentsCount: 4,
    localVerificationStatus: 'verified',
    cooperativeMemberId: 'COP-PUN-4019',
    joinedDate: '2023-04-28',
    bio: 'Thorough eco-friendly cleaning expert in Palm Heights.',
  },
  {
    id: 'w_prashant',
    name: 'Prashant Koli',
    phone: '+91 98903 44102',
    email: 'prashant.k@palmheights.coop',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&auto=format&fit=crop&q=80',
    profession: 'Painting',
    societyId: 'soc_ph',
    societyName: 'Palm Heights',
    managerId: 'mgr_rahul',
    managerName: 'Rahul Mehta',
    rating: 4.76,
    totalReviews: 54,
    completedJobs: 52,
    hourlyRate: 360,
    distanceKm: 3.2,
    availability: 'online',
    currentWorkload: 20,
    proficiencyScore: 87,
    skills: ['Painting', 'Wall Emulsion', 'Waterproofing'],
    certificates: ['Asian Paints Certified Applicator'],
    verificationStatus: 'VERIFIED',
    kycDocumentsCount: 4,
    localVerificationStatus: 'verified',
    cooperativeMemberId: 'COP-PUN-6204',
    joinedDate: '2024-04-10',
    bio: 'Specialist painter for apartment repainting and patch touch-ups.',
  },

  // 5. RIVER VIEW (Manager: Kavita Nair) - 2 Workers
  {
    id: 'w_ganesh',
    name: 'Ganesh Shinde',
    phone: '+91 98226 77104',
    email: 'ganesh.s@riverview.coop',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    profession: 'Plumbing',
    societyId: 'soc_rv',
    societyName: 'River View',
    managerId: 'mgr_kavita',
    managerName: 'Kavita Nair',
    rating: 4.81,
    totalReviews: 71,
    completedJobs: 69,
    hourlyRate: 330,
    distanceKm: 1.6,
    availability: 'online',
    currentWorkload: 25,
    proficiencyScore: 89,
    skills: ['Plumbing', 'Pipeline Repairs', 'Taps'],
    certificates: ['NCVT Plumbing Certificate Level 3'],
    verificationStatus: 'VERIFIED',
    kycDocumentsCount: 4,
    localVerificationStatus: 'verified',
    cooperativeMemberId: 'COP-PUN-3710',
    joinedDate: '2023-08-04',
    bio: 'Reliable plumber for Aundh and River View community.',
  },
  {
    id: 'w_sunita_k',
    name: 'Sunita Kamble',
    phone: '+91 94221 55902',
    email: 'sunita.k@riverview.coop',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&auto=format&fit=crop&q=80',
    profession: 'Cleaning',
    societyId: 'soc_rv',
    societyName: 'River View',
    managerId: 'mgr_kavita',
    managerName: 'Kavita Nair',
    rating: 4.89,
    totalReviews: 88,
    completedJobs: 86,
    hourlyRate: 300,
    distanceKm: 1.1,
    availability: 'online',
    currentWorkload: 30,
    proficiencyScore: 92,
    skills: ['Cleaning', 'Deep Sanitization', 'Elderly Care'],
    certificates: ['Community Sanitization Protocol'],
    verificationStatus: 'VERIFIED',
    kycDocumentsCount: 4,
    localVerificationStatus: 'verified',
    cooperativeMemberId: 'COP-PUN-4590',
    joinedDate: '2023-05-30',
    bio: 'Punctual and meticulous cleaning provider in River View.',
  },

  // 6. HARMONY TOWERS (Manager: Sanjay Patil) - 3 Workers
  {
    id: 'w_santosh',
    name: 'Santosh Pawar',
    phone: '+91 98814 33902',
    email: 'santosh.p@harmonytowers.coop',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    profession: 'Electrical',
    societyId: 'soc_ht',
    societyName: 'Harmony Towers',
    managerId: 'mgr_sanjay',
    managerName: 'Sanjay Patil',
    rating: 4.94,
    totalReviews: 176,
    completedJobs: 173,
    hourlyRate: 410,
    distanceKm: 1.7,
    availability: 'online',
    currentWorkload: 45,
    proficiencyScore: 95,
    skills: ['Electrical', 'Main Distribution Panels', 'EV Chargers'],
    certificates: ['Licensed High-Tension & Wireman Grade 1'],
    verificationStatus: 'VERIFIED',
    kycDocumentsCount: 4,
    localVerificationStatus: 'verified',
    cooperativeMemberId: 'COP-PUN-1289',
    joinedDate: '2022-12-01',
    bio: 'Lead electrical technician with 12 years residential and township experience.',
  },
  {
    id: 'w_bharati',
    name: 'Bharati Chavan',
    phone: '+91 94232 88401',
    email: 'bharati.c@harmonytowers.coop',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&auto=format&fit=crop&q=80',
    profession: 'Cleaning',
    societyId: 'soc_ht',
    societyName: 'Harmony Towers',
    managerId: 'mgr_sanjay',
    managerName: 'Sanjay Patil',
    rating: 4.85,
    totalReviews: 92,
    completedJobs: 90,
    hourlyRate: 300,
    distanceKm: 1.3,
    availability: 'online',
    currentWorkload: 30,
    proficiencyScore: 90,
    skills: ['Cleaning', 'Floor Scrubbing', 'Window Tracks'],
    certificates: ['Advanced Sanitation Specialist'],
    verificationStatus: 'VERIFIED',
    kycDocumentsCount: 4,
    localVerificationStatus: 'verified',
    cooperativeMemberId: 'COP-PUN-4819',
    joinedDate: '2023-09-18',
    bio: 'Dedicated deep cleaning specialist in Wakad corridor.',
  },
  {
    id: 'w_ashok',
    name: 'Ashok Gite',
    phone: '+91 98904 11782',
    email: 'ashok.g@harmonytowers.coop',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&auto=format&fit=crop&q=80',
    profession: 'Carpentry',
    societyId: 'soc_ht',
    societyName: 'Harmony Towers',
    managerId: 'mgr_sanjay',
    managerName: 'Sanjay Patil',
    rating: 4.80,
    totalReviews: 67,
    completedJobs: 65,
    hourlyRate: 370,
    distanceKm: 2.8,
    availability: 'online',
    currentWorkload: 20,
    proficiencyScore: 88,
    skills: ['Carpentry', 'Modular Fittings', 'Bed Frames'],
    certificates: ['ITI Carpentry Diploma'],
    verificationStatus: 'VERIFIED',
    kycDocumentsCount: 4,
    localVerificationStatus: 'verified',
    cooperativeMemberId: 'COP-PUN-5690',
    joinedDate: '2024-03-01',
    bio: 'Skilled wood craftsman and modular furniture assembler.',
  },

  // 7. SILVER OAKS (Manager: Deepali Kulkarni) - 2 Workers
  {
    id: 'w_dilip',
    name: 'Dilip Patil',
    phone: '+91 98227 44190',
    email: 'dilip.p@silveroaks.coop',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    profession: 'Plumbing',
    societyId: 'soc_so',
    societyName: 'Silver Oaks',
    managerId: 'mgr_deepali',
    managerName: 'Deepali Kulkarni',
    rating: 4.84,
    totalReviews: 82,
    completedJobs: 80,
    hourlyRate: 340,
    distanceKm: 2.1,
    availability: 'online',
    currentWorkload: 25,
    proficiencyScore: 90,
    skills: ['Plumbing', 'Overhead Tanks', 'Pressure Pumps'],
    certificates: ['Govt NCVT Plumber Level 3'],
    verificationStatus: 'VERIFIED',
    kycDocumentsCount: 4,
    localVerificationStatus: 'verified',
    cooperativeMemberId: 'COP-PUN-3902',
    joinedDate: '2023-07-15',
    bio: 'Trusted Bavdhan neighbourhood plumber with quick emergency response.',
  },
  {
    id: 'w_manisha',
    name: 'Manisha Shinde',
    phone: '+91 94222 66310',
    email: 'manisha.s@silveroaks.coop',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
    profession: 'Cleaning',
    societyId: 'soc_so',
    societyName: 'Silver Oaks',
    managerId: 'mgr_deepali',
    managerName: 'Deepali Kulkarni',
    rating: 4.88,
    totalReviews: 98,
    completedJobs: 96,
    hourlyRate: 300,
    distanceKm: 1.4,
    availability: 'online',
    currentWorkload: 35,
    proficiencyScore: 92,
    skills: ['Cleaning', 'Kitchen Deep Clean', 'Bathroom Sanitization'],
    certificates: ['Hygienic Sanitation Master Class'],
    verificationStatus: 'VERIFIED',
    kycDocumentsCount: 4,
    localVerificationStatus: 'verified',
    cooperativeMemberId: 'COP-PUN-4910',
    joinedDate: '2023-06-04',
    bio: 'Meticulous residential cleaning specialist.',
  },

  // 8. EMERALD HEIGHTS (Manager: Vikram Shinde) - 2 Workers
  {
    id: 'w_suresh',
    name: 'Suresh Sonawane',
    phone: '+91 98815 66201',
    email: 'suresh.s@emeraldheights.coop',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    profession: 'Electrical',
    societyId: 'soc_eh',
    societyName: 'Emerald Heights',
    managerId: 'mgr_vikram',
    managerName: 'Vikram Shinde',
    rating: 4.90,
    totalReviews: 110,
    completedJobs: 108,
    hourlyRate: 400,
    distanceKm: 1.9,
    availability: 'online',
    currentWorkload: 40,
    proficiencyScore: 94,
    skills: ['Electrical', 'UPS/Inverters', 'Smart Home Switches'],
    certificates: ['Licensed Wireman Grade 1'],
    verificationStatus: 'VERIFIED',
    kycDocumentsCount: 4,
    localVerificationStatus: 'verified',
    cooperativeMemberId: 'COP-PUN-1490',
    joinedDate: '2023-01-20',
    bio: 'Senior electrician serving Hinjewadi tech corridor apartments.',
  },
  {
    id: 'w_rekha',
    name: 'Rekha Ghorpade',
    phone: '+91 94223 77901',
    email: 'rekha.g@emeraldheights.coop',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&auto=format&fit=crop&q=80',
    profession: 'Cleaning',
    societyId: 'soc_eh',
    societyName: 'Emerald Heights',
    managerId: 'mgr_vikram',
    managerName: 'Vikram Shinde',
    rating: 4.87,
    totalReviews: 76,
    completedJobs: 74,
    hourlyRate: 310,
    distanceKm: 1.5,
    availability: 'online',
    currentWorkload: 25,
    proficiencyScore: 91,
    skills: ['Cleaning', 'Move-in Sanitization', 'Kitchen Scrub'],
    certificates: ['Eco-Clean Sanitation Certificate'],
    verificationStatus: 'VERIFIED',
    kycDocumentsCount: 4,
    localVerificationStatus: 'verified',
    cooperativeMemberId: 'COP-PUN-5021',
    joinedDate: '2023-11-12',
    bio: 'High-rated cleaning professional in Emerald Heights.',
  },
];

export const INITIAL_WORKERS: Worker[] = RAW_WORKERS.map((w, idx) => {
  const socCoords = (w.societyId && SOCIETY_COORDINATES[w.societyId]) || {
    lat: 18.5590,
    lng: 73.7868,
    area: w.societyName || 'Green Residency',
  };
  // Distribute workers realistically around their society base perimeter
  const angle = (idx * 45 * Math.PI) / 180;
  const radius = 0.003 + (idx % 4) * 0.0015;
  const lat = parseFloat((socCoords.lat + Math.sin(angle) * radius).toFixed(5));
  const lng = parseFloat((socCoords.lng + Math.cos(angle) * radius).toFixed(5));

  const isVerified = w.verificationStatus === 'VERIFIED';
  const isManagerVerified = w.verificationStatus === 'MANAGER_VERIFIED';
  const isPending = w.verificationStatus === 'PENDING' || w.verificationStatus === 'UNDER_REVIEW';
  const docs = w.documents || createDefaultWorkerDocuments(w.id, w.name, isVerified || isManagerVerified);
  const locationStatus =
    w.availability === 'online'
      ? (w.currentWorkload > 50 ? 'ON_JOB' : idx % 3 === 0 ? 'TRAVELLING' : 'AVAILABLE')
      : 'OFFLINE';

  const updatedMinutes = (idx * 3 + 1) % 45;

  const defaultSkills: WorkerSkillEntry[] = (w.skills || []).map((skillName, sIdx) => ({
    id: `skill_${w.id}_${sIdx}`,
    workerId: w.id,
    name: skillName,
    experienceYears: sIdx === 0 ? 5 : 3,
    description: `Experienced in residential ${skillName.toLowerCase()} maintenance, troubleshooting, and repairs.`,
    certificateName: `${skillName} Trade Vocational Certificate`,
    certificateUrl: 'https://images.unsplash.com/photo-1589330694653-ded6df03f754?w=600&auto=format&fit=crop&q=80',
    serviceArea: socCoords.area,
    status: isPending ? 'PENDING' : 'VERIFIED',
    verifiedBy: isPending ? undefined : (w.managerName || 'Priya Sharma (Society Manager)'),
    verifiedAt: isPending ? undefined : '2026-08-15',
  }));

  const personalKycStatus = w.personalKycStatus || (isPending ? 'PENDING' : 'VERIFIED');

  return {
    ...w,
    latitude: lat,
    longitude: lng,
    locationUpdatedAt: `${updatedMinutes} min ago`,
    locationStatus,
    lastKnownArea: socCoords.area,
    personalKycStatus,
    personalKycVerifiedBy: personalKycStatus === 'VERIFIED' ? (w.managerName || 'Priya Sharma') : undefined,
    personalKycVerifiedAt: personalKycStatus === 'VERIFIED' ? '2026-08-15' : undefined,
    gender: w.gender || (idx % 3 === 0 ? 'Female' : 'Male'),
    dob: w.dob || '1990-06-15',
    aadhaarNumber: w.aadhaarNumber || `98204419${String(idx + 1000).slice(0, 4)}`,
    address: w.address || `${w.societyName || 'Green Residency'} Staff Quarters, Pune`,
    pinCode: w.pinCode || '411045',
    emergencyContactName: w.emergencyContactName || 'Family Kin / Society Desk',
    emergencyContactNumber: w.emergencyContactNumber || '+91 98204 11983',
    documents: docs,
    skillEntries: w.skillEntries || defaultSkills,
    kycDocumentsCount: docs.filter((d) => d.status === 'APPROVED').length,
  };
});

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'BKG-1048',
    customerId: 'user_cust_01',
    customerName: 'Ananya Deshmukh',
    customerPhone: '+91 98201 44521',
    customerAddress: 'Flat 402, Tower B, Green Residency, Baner Rd',
    societyName: 'Green Residency',
    serviceCategory: 'Electrical',
    problemType: 'Switchboard spark / loose connection',
    details: 'Master bedroom main switch panel makes buzzing sound when AC turns on.',
    photos: [],
    urgencyTier: 'URGENT',
    state: 'IN_PROGRESS',
    createdAt: '2026-09-11T20:30:00Z',
    updatedAt: '2026-09-11T21:15:00Z',
    otp: '4829',
    pricing: {
      total: 800,
      workerShare: 560,
      societyShare: 40,
      cooperativeFund: 200,
    },
    matchedWorkerId: 'w_rahul',
    matchedWorker: INITIAL_WORKERS[0],
    beforeImage: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'BKG-1120',
    customerId: 'user_cust_01',
    customerName: 'Ananya Deshmukh',
    customerPhone: '+91 98201 44521',
    customerAddress: 'Flat 402, Tower B, Green Residency, Baner Rd',
    societyName: 'Green Residency',
    serviceCategory: 'Plumbing',
    problemType: 'Angle valve gasket replacement & pipe leak fix',
    details: 'Bathroom geyser inlet angle valve was dripping heavily. Replaced gasket and washer.',
    photos: [],
    urgencyTier: 'STANDARD',
    state: 'AWAITING_VERIFICATION',
    createdAt: '2026-09-12T09:00:00Z',
    updatedAt: '2026-09-12T11:30:00Z',
    otp: '5219',
    pricing: {
      total: 650,
      workerShare: 455,
      societyShare: 35,
      cooperativeFund: 160,
    },
    matchedWorkerId: 'w_rahul',
    matchedWorker: INITIAL_WORKERS[0],
    beforeImage: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=500&auto=format&fit=crop&q=80',
    afterImage: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=500&auto=format&fit=crop&q=80',
    notes: 'Replaced brass compression washer and checked line under full overhead tank pressure.',
    customerConfirmation: true,
    customerConfirmedAt: '2026-09-12T11:45:00Z',
  },
  {
    id: 'BKG-1105',
    customerId: 'user_cust_01',
    customerName: 'Ananya Deshmukh',
    customerPhone: '+91 98201 44521',
    customerAddress: 'Flat 402, Tower B, Green Residency, Baner Rd',
    societyName: 'Green Residency',
    serviceCategory: 'Plumbing',
    problemType: 'Kitchen sink siphon leak',
    details: 'Water seeping into lower kitchen cabinet from the siphon seal.',
    photos: [],
    urgencyTier: 'STANDARD',
    state: 'REVISIT_REQUESTED',
    createdAt: '2026-09-10T14:00:00Z',
    updatedAt: '2026-09-11T16:00:00Z',
    otp: '7841',
    pricing: {
      total: 550,
      workerShare: 385,
      societyShare: 30,
      cooperativeFund: 135,
    },
    matchedWorkerId: 'w_rahul',
    matchedWorker: INITIAL_WORKERS[0],
    revisitDetails: {
      reason: 'Trap joint still seeping minor drops under heavy hot water drain. Needs silicone gasket inspection.',
      status: 'PENDING',
      requestedAt: '2026-09-11T16:05:00Z',
    },
  },
  {
    id: 'BKG-1080',
    customerId: 'user_cust_01',
    customerName: 'Ananya Deshmukh',
    customerPhone: '+91 98201 44521',
    customerAddress: 'Flat 402, Tower B, Green Residency, Baner Rd',
    societyName: 'Green Residency',
    serviceCategory: 'Appliance Repair',
    problemType: 'Microwave fuse blowout',
    details: 'Unit not powering on after power surge in society.',
    photos: [],
    urgencyTier: 'STANDARD',
    state: 'CANCELLED',
    createdAt: '2026-09-08T11:00:00Z',
    updatedAt: '2026-09-08T11:45:00Z',
    otp: '1902',
    pricing: {
      total: 450,
      workerShare: 315,
      societyShare: 25,
      cooperativeFund: 110,
    },
    cancellationDetails: {
      cancelledBy: 'Customer (Ananya)',
      reason: 'Resolved issue by resetting external MCB circuit breaker; technician visit no longer needed.',
      cancelledAt: '2026-09-08T11:45:00Z',
    },
  },
  {
    id: 'BKG-0992',
    customerId: 'user_cust_01',
    customerName: 'Ananya Deshmukh',
    customerPhone: '+91 98201 44521',
    customerAddress: 'Flat 402, Tower B, Green Residency, Baner Rd',
    societyName: 'Green Residency',
    serviceCategory: 'Cleaning',
    problemType: 'Bathroom intensive tile descaling',
    details: 'Deep descaling and lime removal for 2 attached bathrooms.',
    photos: [],
    urgencyTier: 'STANDARD',
    state: 'COMPLETED',
    createdAt: '2026-09-09T10:00:00Z',
    updatedAt: '2026-09-09T14:30:00Z',
    otp: '3190',
    pricing: {
      total: 1000,
      workerShare: 700,
      societyShare: 50,
      cooperativeFund: 250,
    },
    matchedWorkerId: 'w_sunita',
    matchedWorker: INITIAL_WORKERS[4],
    beforeImage: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=500&auto=format&fit=crop&q=80',
    afterImage: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=500&auto=format&fit=crop&q=80',
    managerVerification: {
      verifiedBy: 'Priya Sharma (Society Manager)',
      status: 'APPROVED',
      notes: 'Descaling inspected and verified to cooperative standards.',
      verifiedAt: '2026-09-09T14:45:00Z',
    },
    rating: {
      stars: 5,
      comment: 'Sunita ji was extraordinarily thorough and professional. Tiles look brand new!',
      ratedAt: '2026-09-09T15:00:00Z',
    },
  },
];

export const INITIAL_COMMUNITY_BOOKINGS: CommunityBooking[] = [
  {
    id: 'COMM-GR-01',
    societyName: 'Green Residency',
    serviceCategory: 'Plumbing',
    description: 'Comprehensive pre-monsoon plumbing overhaul: tap seals, valve checks, drain strainer cleanouts.',
    participantCount: 7,
    targetDiscountPercent: 20,
    scheduledDate: 'This Saturday, 10:00 AM',
    status: 'open',
    participants: [
      { id: 'p1', customerName: 'Ananya Deshmukh', flatNumber: 'B-402', joinedAt: '2 days ago' },
      { id: 'p2', customerName: 'Kunal Kulkarni', flatNumber: 'A-101', joinedAt: 'Yesterday' },
      { id: 'p3', customerName: 'Ritu Sen', flatNumber: 'C-304', joinedAt: 'Yesterday' },
      { id: 'p4', customerName: 'Harish Mehta', flatNumber: 'B-601', joinedAt: '12 hrs ago' },
      { id: 'p5', customerName: 'Deepa Hegde', flatNumber: 'A-502', joinedAt: '6 hrs ago' },
      { id: 'p6', customerName: 'Vikram Ranade', flatNumber: 'C-103', joinedAt: '3 hrs ago' },
      { id: 'p7', customerName: 'Rohit Bansal', flatNumber: 'B-205', joinedAt: '1 hr ago' },
    ],
  },
  {
    id: 'COMM-PM-02',
    societyName: 'Palm Meadows Society',
    serviceCategory: 'Electrical',
    description: 'Quarterly township electrical safety audit and distribution panel thermographic scan.',
    participantCount: 14,
    targetDiscountPercent: 25,
    scheduledDate: 'Next Sunday, 09:30 AM',
    status: 'confirmed',
    participants: [
      { id: 'pm1', customerName: 'Aditi Rao', flatNumber: 'T1-201', joinedAt: '3 days ago' },
      { id: 'pm2', customerName: 'Sanjay Kapoor', flatNumber: 'T2-504', joinedAt: '3 days ago' },
      { id: 'pm3', customerName: 'Nitin Gadre', flatNumber: 'T1-802', joinedAt: '2 days ago' },
    ],
  },
];

export const INITIAL_COOPERATIVE_FUND: CooperativeFund = {
  balance: 482500,
  monthlyContributions: 84200,
  workerSupportAllocated: 125000,
  toolBankAllocated: 95000,
  emergencyAidAllocated: 60000,
  trainingAllocated: 45000,
  transactions: [
    {
      id: 'TXN-8841',
      date: '2026-09-11',
      type: 'credit',
      category: 'booking_share',
      amount: 250,
      description: 'Cooperative share from Booking #0992 (Cleaning)',
      relatedBookingId: 'BKG-0992',
    },
    {
      id: 'TXN-8840',
      date: '2026-09-10',
      type: 'debit',
      category: 'tool_purchase',
      amount: 14500,
      description: 'Purchased 2x Fluke Digital Multimeters for Baner Tool Bank Hub',
    },
    {
      id: 'TXN-8839',
      date: '2026-09-08',
      type: 'debit',
      category: 'emergency_aid',
      amount: 12000,
      description: 'Emergency medical assistance grant disbursed to Worker Ramesh K.',
    },
    {
      id: 'TXN-8838',
      date: '2026-09-07',
      type: 'credit',
      category: 'booking_share',
      amount: 1850,
      description: 'Batch settlement: 9 completed residential jobs',
    },
    {
      id: 'TXN-8837',
      date: '2026-09-05',
      type: 'debit',
      category: 'training',
      amount: 8000,
      description: 'Safety & First Aid certification workshop for 20 cooperative workers',
    },
  ],
};

export const INITIAL_TOOL_BANK: ToolBankItem[] = [
  {
    id: 'TOOL-01',
    name: 'Professional Rotary Hammer Drill (Bosch GBH 2-28 F)',
    category: 'Power Tools',
    serialNumber: 'BSH-2024-8841',
    condition: 'excellent',
    status: 'available',
  },
  {
    id: 'TOOL-02',
    name: 'Digital Thermal Imaging Camera (Flir One Pro)',
    category: 'Diagnostics',
    serialNumber: 'FLR-2025-0192',
    condition: 'excellent',
    status: 'available',
  },
  {
    id: 'TOOL-03',
    name: 'True RMS Digital Multimeter & Clamp (Fluke 376 FC)',
    category: 'Electrical',
    serialNumber: 'FLK-2023-9904',
    condition: 'good',
    status: 'available',
  },
  {
    id: 'TOOL-04',
    name: 'Heavy Duty Portable Circular Saw (DeWalt DWE575)',
    category: 'Carpentry',
    serialNumber: 'DWT-2024-5512',
    condition: 'good',
    status: 'borrowed',
    borrowedByWorkerId: 'w_amit',
    borrowedByWorkerName: 'Amit Kumar',
    borrowedDate: '2026-09-10',
    returnDate: '2026-09-14',
  },
  {
    id: 'TOOL-05',
    name: 'Electric Pipe Threading Machine 1/2" - 2"',
    category: 'Plumbing',
    serialNumber: 'PTH-2025-3310',
    condition: 'excellent',
    status: 'available',
  },
  {
    id: 'TOOL-06',
    name: '16-Step Telescopic Aluminum Extension Ladder (3.8m)',
    category: 'Access Equipment',
    serialNumber: 'LDR-2024-7721',
    condition: 'good',
    status: 'available',
  },
];

export const INITIAL_EMERGENCY_AID_REQUESTS: WorkerEmergencyAidRequest[] = [
  {
    id: 'AID-101',
    workerId: 'w_sanjay',
    workerName: 'Sanjay Rao',
    reason: 'Family medical emergency: sudden hospitalization deposit for spouse.',
    requestedAmount: 15000,
    requestedDate: '2026-09-11',
    status: 'pending',
    notes: 'Member in good standing for 18 months, zero previous loan defaults.',
  },
  {
    id: 'AID-098',
    workerId: 'w_rajesh',
    workerName: 'Rajesh Verma',
    reason: 'Power planer tool motor burnout replacement assistance.',
    requestedAmount: 6500,
    requestedDate: '2026-09-04',
    status: 'approved',
    notes: 'Approved by Cooperative Board under Equipment Support Scheme.',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'NOTIF-01',
    recipientRole: 'customer',
    title: 'Worker Dispatched',
    message: 'Priya Patel is travelling to Flat 402, Green Residency. ETA 12 mins.',
    timestamp: '15 mins ago',
    type: 'info',
    read: false,
    relatedBookingId: 'BKG-1048',
  },
  {
    id: 'NOTIF-02',
    recipientRole: 'worker',
    title: 'Job Request Assigned',
    message: 'You have been matched with urgent electrical repair at Green Residency.',
    timestamp: '25 mins ago',
    type: 'info',
    read: false,
    relatedBookingId: 'BKG-1048',
  },
  {
    id: 'NOTIF-03',
    recipientRole: 'society_manager',
    title: 'New Worker KYC Submitted',
    message: 'Vikram Joshi submitted ITI Electrical documents for review.',
    timestamp: '1 hour ago',
    type: 'info',
    read: true,
  },
];
