import json

# Read customer_raw.json to get exact keys
with open('scripts/locales_data/customer_raw.json', 'r', encoding='utf-8') as f:
    raw = json.load(f)

# Master dictionary for customer translations
TRANSLATIONS = {
    # Wizard
    "wizard.serviceCategory": ("Service Category", "सेवा श्रेणी"),
    "wizard.step1": ("1. Select Category", "1. श्रेणी चुनें"),
    "wizard.step2": ("2. Describe Issue", "2. समस्या का विवरण दें"),
    "wizard.step4": ("4. Fair Pricing & Confirmation", "4. उचित मूल्य और पुष्टि"),
    "wizard.confirmBooking": ("Confirm Request", "अनुरोध की पुष्टि करें"),
    "wizard.problemLabel": ("Problem Description", "समस्या का विवरण"),

    # Services Page
    "servicesPage.verifiedCatalog": ("Verified Service Catalog", "सत्यापित सेवा सूची"),
    "servicesPage.title": ("Household & Community Services", "घरेलू एवं सामुदायिक सेवाएँ"),
    "servicesPage.subtitle": ("All services are performed by verified cooperative members adhering to standardized community rates and transparent splits.", "सभी सेवाएँ सत्यापित सहकारी सदस्यों द्वारा मानकीकृत दरों और पारदर्शी विभाजन के तहत की जाती हैं।"),
    "servicesPage.searchPlaceholder": ("Search for repair, installation, cleaning...", "मरम्मत, स्थापना, सफाई आदि खोजें..."),
    "servicesPage.allServices": ("All Services ({{count}})", "सभी सेवाएँ ({{count}})"),
    "servicesPage.coopBaseRate": ("Coop Base Rate", "सहकारी आधार दर"),
    "servicesPage.commonRequests": ("Common Requests:", "सामान्य अनुरोध:"),
    "servicesPage.requestService": ("Request {{name}}", "{{name}} का अनुरोध करें"),

    # Tracking
    "tracking.workerArriving": ("On The Way", "रास्ते में"),
    "tracking.otpInstruction": ("Share this code with your worker upon arrival:", "कार्यकर्ता के पहुँचने पर यह कोड साझा करें:"),

    # Emergency
    "emergency.plumbing": ("Plumbing", "प्लंबिंग"),
    "emergency.plumbingDesc": ("Severe pipe burst / continuous water leakage flooding room", "गंभीर पाइप फटना / कमरे में पानी भरना"),
    "emergency.electrical": ("Electrical", "इलेक्ट्रिकल"),
    "emergency.electricalDesc": ("Main distribution box sparking / burning smell / complete blackout", "मेन बॉक्स से चिंगारी / जलने की गंध / पूर्ण बिजली गुल"),
    "emergency.carpentry": ("Carpentry", "बढ़ईगीरी"),
    "emergency.carpentryDesc": ("Main entrance security door jammed shut / resident locked out", "मुख्य प्रवेश द्वार का लॉक जाम / बाहर बंद होना"),
    "emergency.title": ("Need help immediately?", "क्या आपको तत्काल सहायता चाहिए?"),
    "emergency.subtitle": ("Cooperative Priority Emergency Response", "सहकारी प्राथमिकता आपातकालीन प्रतिक्रिया"),
    "emergency.queueTitle": ("Emergency Priority Queue", "आपातकालीन प्राथमिकता कतार"),
    "emergency.queueDesc": ("For situations requiring immediate assistance. Dispatches directly to closest available verified specialists with auto-escalation.", "तत्काल सहायता के लिए। स्वतः एस्केलेशन के साथ निकटतम सत्यापित विशेषज्ञों को भेजा जाता है।"),
    "emergency.selectType": ("Select Emergency Type:", "आपातकाल प्रकार चुनें:"),
    "emergency.dispatchingTo": ("Dispatching to:", "भेजा जा रहा है:"),
    "emergency.requestHelp": ("Request Immediate Emergency Help", "तत्काल आपातकालीन सहायता का अनुरोध करें"),

    # Payment
    "payment.payVia": ("Pay ₹{{amount}} via UPI / Card", "यूपीआई / कार्ड द्वारा ₹{{amount}} का भुगतान करें"),
    "payment.upi": ("UPI", "यूपीआई"),
    "payment.upiSub": ("Google Pay, PhonePe, BHIM, Paytm", "गूगल पे, फोनपे, भीम, पेटीएम"),
    "payment.card": ("Credit / Debit Card", "क्रेडिट / डेबिट कार्ड"),
    "payment.cardSub": ("Visa, Mastercard, RuPay", "वीज़ा, मास्टरकार्ड, रुपे"),
    "payment.netBanking": ("Net Banking", "नेट बैंकिंग"),
    "payment.netBankingSub": ("All major Indian banks", "सभी प्रमुख भारतीय बैंक"),
    "payment.wallet": ("Cooperative Wallet", "सहकारी वॉलेट"),
    "payment.walletSub": ("Your society wallet balance", "आपकी सोसाइटी का वॉलेट शेष"),
    "payment.yourInvoice": ("Your Invoice", "आपका चालान"),
    "payment.paymentMethod": ("Payment Method", "भुगतान विधि"),
    "payment.reviewConfirm": ("Review & Confirm", "समीक्षा और पुष्टि करें"),
    "payment.stepInvoice": ("Invoice", "चालान"),
    "payment.stepMethod": ("Method", "विधि"),
    "payment.stepConfirm": ("Confirm", "पुष्टि करें"),
    "payment.popular": ("Popular", "लोकप्रिय"),
    "payment.title": ("Transparent Payment", "पारदर्शी भुगतान"),
    "payment.settlementFor": ("Settlement for Booking", "बुकिंग का निपटान"),
    "payment.serviceCompleted": ("Service Completed ✓", "सेवा पूर्ण ✓"),
    "payment.itemizedAllocation": ("Itemized Allocation", "मदवार आवंटन"),
    "payment.cooperativeFormula": ("Cooperative Formula", "सहकारी सूत्र"),
    "payment.workerPayout": ("Worker Direct Payout", "कार्यकर्ता को सीधा भुगतान"),
    "payment.societyShareLabel": ("Share", "हिस्सा"),
    "payment.coopFundLabel": ("Cooperative Emergency & Tool Fund", "सहकारी आपातकालीन एवं टूल फंड"),
    "payment.totalSettlement": ("Total Settlement", "कुल भुगतान राशि"),
    "payment.guaranteeNote": ("Unlike commercial gig apps that extract 30%+ profit, your payment directly supports worker livelihoods, resident society upkeep, and zero-interest emergency tool loans.", "30%+ लाभ लेने वाले व्यावसायिक ऐप्स के विपरीत, आपका भुगतान सीधे कार्यकर्ताओं की आजीविका, सोसाइटी रखरखाव और शून्य-ब्याज टूल लोन का समर्थन करता है।"),
    "payment.paymentConfirmed": ("Payment Confirmed! ✓", "भुगतान की पुष्टि हुई! ✓"),

    # Dispute
    "dispute.tagPunctual": ("Punctual arrival", "समय पर आगमन"),
    "dispute.tagPolite": ("Polite behaviour", "विनम्र व्यवहार"),
    "dispute.tagCleanup": ("Spotless cleanup", "उत्कृष्ट सफाई"),
    "dispute.tagExpert": ("Expert repair", "कुशल मरम्मत"),
    "dispute.revisitTitle": ("Request Service Revisit", "पुनः कार्य का अनुरोध करें"),
    "dispute.disputeTitle": ("Report Quality Concern", "गुणवत्ता संबंधी शिकायत दर्ज करें"),
    "dispute.rateTitle": ("How was your service?", "आपकी सेवा कैसी रही?"),
    "dispute.workProof": ("Work Execution Proof (Before & After)", "कार्य निष्पादन प्रमाण (पहले और बाद)"),
    "dispute.noBefore": ("No Before Photo", "पहले का फोटो उपलब्ध नहीं"),
    "dispute.before": ("Before", "पहले"),
    "dispute.noAfter": ("No After Photo", "बाद का फोटो उपलब्ध नहीं"),
    "dispute.after": ("After ✓", "बाद में ✓"),
    "dispute.excellent": ("Excellent — Highly recommended!", "उत्कृष्ट — अत्यधिक अनुशंसित!"),
    "dispute.good": ("Good — Satisfactory work.", "अच्छा — संतोषजनक कार्य।"),
    "dispute.average": ("Average — Met expectations.", "औसत — उम्मीदों के अनुरूप।"),
    "dispute.below": ("Below expectation.", "उम्मीद से कम।"),
    "dispute.unsatisfactory": ("Unsatisfactory.", "असंतोषजनक।"),
    "dispute.detailedFeedback": ("Detailed Feedback (Optional)", "विस्तृत प्रतिक्रिया (वैकल्पिक)"),
    "dispute.feedbackPlaceholder": ("Share your experience to help the cooperative maintain quality...", "गुणवत्ता बनाए रखने में मदद के लिए अपना अनुभव साझा करें..."),
    "dispute.submitRating": ("Submit Rating", "रेटिंग सबमिट करें"),
    "dispute.needFollowup": ("Need follow-up? Request Revisit", "क्या सुधार की आवश्यकता है? पुनः सेवा मांगें"),
    "dispute.reportDispute": ("Report quality dispute", "गुणवत्ता संबंधी विवाद दर्ज करें"),
    "dispute.revisitNoticeTitle": ("Complimentary Cooperative Revisit", "निःशुल्क सहकारी पुनः सेवा"),
    "dispute.revisitNoticeDesc": ("If the service requires follow-up, our society manager will coordinate a free revisit with the technician.", "यदि कार्य में सुधार आवश्यक है, तो प्रबंधक निःशुल्क पुनः विज़िट का समन्वय करेगा।"),
    "dispute.reasonForRevisit": ("Reason for Revisit:", "पुनः विज़िट का कारण:"),
    "dispute.revisitPlaceholder": ("e.g. Joint slightly dripping under heavy water pressure. Needs second inspection...", "उदा. भारी पानी के दबाव में जोड़ से हल्का रिसाव हो रहा है। दूसरी जांच की आवश्यकता है..."),
    "dispute.backToRating": ("Back to Rating", "रेटिंग पर वापस जाएँ"),
    "dispute.submitRevisit": ("Submit Revisit Request", "पुनः सेवा अनुरोध सबमिट करें"),
    "dispute.disputeGuarantee": ("Cooperative Guarantee: If work is defective or incomplete, our society coordinator will review and assign a complimentary revisit at zero additional charge.", "सहकारी गारंटी: यदि कार्य अधूरा या दोषपूर्ण है, तो समन्वयक समीक्षा करेगा और बिना किसी अतिरिक्त शुल्क के निःशुल्क पुनः कार्य कराएगा।"),
    "dispute.issueCategory": ("Issue Category:", "समस्या श्रेणी:"),
    "dispute.incompleteWork": ("Incomplete work", "अधूरा काम"),
    "dispute.poorQuality": ("Poor quality / recurring leak", "खराब गुणवत्ता / बार-बार रिसाव"),
    "dispute.workerIssue": ("Worker conduct / delay", "कार्यकर्ता आचरण / देरी"),
    "dispute.damage": ("Accidental damage", "दुर्घटना से क्षति"),
    "dispute.otherConcern": ("Other concern", "अन्य चिंता"),
    "dispute.describeIssue": ("Describe the specific issue:", "विशिष्ट समस्या का वर्णन करें:"),
    "dispute.disputePlaceholder": ("e.g. The tap joint started dripping again within 2 hours of repair...", "उदा. मरम्मत के 2 घंटे के भीतर नल का जोड़ फिर से टपकने लगा..."),
    "dispute.submitDispute": ("Submit Quality Dispute", "गुणवत्ता विवाद सबमिट करें"),

    # SOS
    "sos.customerReasons.safetyConcern": ("Safety concern", "सुरक्षा संबंधी चिंता"),
    "sos.customerReasons.workerIssue": ("Worker issue", "कार्यकर्ता से संबंधित समस्या"),
    "sos.customerReasons.medicalEmergency": ("Medical emergency", "चिकित्सा आपातकाल"),
    "sos.customerReasons.propertyDamage": ("Property damage", "संपत्ति की क्षति"),
    "sos.customerReasons.workerNotArrived": ("Worker has not arrived", "कार्यकर्ता नहीं आया है"),
    "sos.customerReasons.other": ("Other", "अन्य"),
    "sos.customerTitle": ("Active Job SOS", "सक्रिय कार्य एसओएस"),
    "sos.customerSubtitle": ("Emergency Assistance", "आपातकालीन सहायता"),
    "sos.customerGpsTelemetry": ("Captured GPS Telemetry", "दर्ज जीपीएस टेलीमेट्री"),
    "sos.maps": ("Maps", "मानचित्र"),
    "sos.ticketDispatched": ("Ticket Dispatched", "टिकट भेजा गया"),
    "sos.ticketNumber": ("Ticket #${submittedTicketId}", "टिकट #{{id}}"),
    "sos.customerStandbyNotice": ("Your Society Desk and Emergency Response have been alerted with live GPS telemetry.", "लाइव जीपीएस के साथ आपकी सोसाइटी डेस्क और आपातकालीन दल को सचेत कर दिया गया है।"),
    "sos.policeControl": ("Emergency Police (112)", "आपातकालीन पुलिस (112)"),
    "sos.call112": ("Call 112", "112 पर कॉल करें"),
    "sos.societyManagerDesk": ("Society Manager Desk", "सोसाइटी प्रबंधक डेस्क"),
    "sos.callDesk": ("Call Desk", "डेस्क पर कॉल करें"),
    "sos.closeWindow": ("Close Window", "खिड़की बंद करें"),
    "sos.whatsWrong": ("What's wrong?", "क्या समस्या है?"),
    "sos.additionalDetails": ("Additional Details (Optional)", "अतिरिक्त विवरण (वैकल्पिक)"),
    "sos.provideContext": ("Provide any critical context...", "कोई भी महत्वपूर्ण संदर्भ दें..."),
    "sos.sendCustomerSos": ("Submit Emergency SOS with Location", "स्थान के साथ आपातकालीन एसओएस भेजें"),
    "sos.title": ("Emergency SOS — always available", "आपातकालीन एसओएस — हमेशा उपलब्ध"),
    "sos.workerReasons.unsafeEnv": ("Unsafe environment", "असुरक्षित वातावरण"),
    "sos.workerReasons.customerSafetyIssue": ("Customer safety issue", "ग्राहक सुरक्षा समस्या"),
    "sos.workerReasons.medicalEmergency": ("Medical emergency", "चिकित्सा आपातकाल"),
    "sos.workerReasons.conflict": ("Conflict", "विवाद / तनाव"),
    "sos.workerReasons.equipmentProblem": ("Equipment problem", "उपकरण समस्या"),
    "sos.workerReasons.other": ("Other", "अन्य"),
    "sos.workerTitle": ("Worker Safety SOS", "कार्यकर्ता सुरक्षा एसओएस"),
    "sos.workerSubtitle": ("Worker Support Escalation", "कार्यकर्ता सहायता एस्केलेशन"),
    "sos.workerCoords": ("Worker Job Coordinates", "कार्यकर्ता कार्य निर्देशांक"),
    "sos.supportDispatched": ("Support Dispatched", "सहायता दल रवाना किया गया"),
    "sos.workerStandbyNotice": ("Your Society Manager and Cooperative Support desk are on stand-by to assist immediately.", "आपके सोसाइटी प्रबंधक और सहकारी सहायता डेस्क तुरंत सहायता के लिए तैयार हैं।"),
    "sos.societySafetyDesk": ("Society Safety Desk", "सोसाइटी सुरक्षा डेस्क"),
    "sos.describeSituation": ("Describe the immediate situation...", "तात्कालिक स्थिति का वर्णन करें..."),
    "sos.sendWorkerSos": ("Send Urgent Worker SOS", "तत्काल कार्यकर्ता एसओएस भेजें"),

    # Customer
    "customer.activitySubtitle": ("Full history of your cooperative household bookings in {{society}}", "{{society}} में आपकी सहकारी घरेलू बुकिंग का पूरा इतिहास"),
    "customer.afterRepair": ("After Repair ✓", "मरम्मत के बाद ✓"),
    "customer.beforeRepair": ("Before Repair", "मरम्मत से पहले"),
    "customer.bookingLabel": ("Booking", "बुकिंग"),
    "customer.cancellationReason": ("Cancellation Reason:", "रद्द करने का कारण:"),
    "customer.cancelledByWithReason": ("Cancelled by {{cancelledBy}}: {{reason}}", "{{cancelledBy}} द्वारा रद्द: {{reason}}"),
    "customer.commonConcerns": ("Common Concerns (tap to append):", "सामान्य चिंताएँ (जोड़ने के लिए टैप करें):"),
    "customer.compareEvidenceDesc": ("Compare the before & after evidence photos below. If you're satisfied, confirm below. If not, request a free revisit.", "नीचे पहले और बाद के फोटो की तुलना करें। यदि आप संतुष्ट हैं तो पुष्टि करें, अन्यथा निःशुल्क पुनः सेवा मांगें।"),
    "customer.confirmWorkDone": ("Confirm Work Done", "कार्य पूर्ण होने की पुष्टि करें"),
    "customer.confirmationRecorded": ("Confirmation recorded. Awaiting Society Manager final approval.", "पुष्टि दर्ज की गई। सोसाइटी प्रबंधक के अंतिम अनुमोदन की प्रतीक्षा है।"),
    "customer.coopGuarantee": ("Cooperative Quality Guarantee", "सहकारी गुणवत्ता गारंटी"),
    "customer.coopGuaranteeDesc": ("If the completed service did not resolve your issue or requires follow-up adjustment, you can request a complimentary revisit. Your society manager will inspect and schedule the follow-up.", "यदि पूर्ण सेवा ने आपकी समस्या का समाधान नहीं किया, तो आप निःशुल्क पुनः कार्य का अनुरोध कर सकते हैं। प्रबंधक जांच कर समय निर्धारित करेगा।"),
    "customer.coopKycVerified": ("100% Cooperative KYC Verified", "100% सहकारी केवाईसी सत्यापित"),
    "customer.coopKycVerifiedDesc": ("Physical address, police clearance, and skill assessment verified by society manager.", "भौतिक पता, पुलिस क्लीयरेंस और कौशल का सोसाइटी प्रबंधक द्वारा सत्यापन।"),
    "customer.describeNeedsAttention": ("Describe what needs attention:", "बताएं कि किस पर ध्यान देने की आवश्यकता है:"),
    "customer.estResume": ("Est. Resume", "अनुमानित कार्य पुनः आरंभ"),
    "customer.greeting": ("Hello", "नमस्ते"),
    "customer.historyFilters.all": ("All History", "संपूर्ण इतिहास"),
    "customer.historyFilters.cancelled": ("Cancelled", "रद्द किया गया"),
    "customer.historyFilters.finished": ("Finished", "समाप्त"),
    "customer.historyFilters.revisited": ("Revisited", "पुनः विज़िट किया गया"),
    "customer.jobsDone": ("jobs", "काम"),
    "customer.kycSkillVerifiedBadge": ("KYC & Skill Verified ✓", "केवाईसी एवं कौशल सत्यापित ✓"),
    "customer.myServiceActivity": ("My Service Activity", "मेरी सेवा गतिविधि"),
    "customer.needHelp": ("What do you need help with today?", "आज आपको किस काम में सहायता चाहिए?"),
    "customer.noAfterPhoto": ("No After Photo", "बाद का फोटो उपलब्ध नहीं"),
    "customer.noBeforePhoto": ("No Before Photo", "पहले का फोटो उपलब्ध नहीं"),
    "customer.noBookingsMatchingFilter": ("You don't have any bookings matching this filter.", "इस फ़िल्टर से मेल खाती कोई बुकिंग नहीं है।"),
    "customer.noRequestsFound": ("No requests found.", "कोई अनुरोध नहीं मिला।"),
    "customer.overdue": ("Overdue", "समय समाप्त"),
    "customer.payAmount": ("Pay", "भुगतान करें"),
    "customer.pendingManagerReview": ("Pending Manager Review", "प्रबंधक समीक्षा लंबित"),
    "customer.professionalBio": ("Professional Bio", "पेशेवर विवरण"),
    "customer.rateService": ("Rate Service", "सेवा को रेट करें"),
    "customer.remaining": ("Remaining", "शेष"),
    "customer.requestAService": ("Request a Service", "सेवा का अनुरोध करें"),
    "customer.requestRevisit": ("Request Revisit", "पुनः सेवा का अनुरोध करें"),
    "customer.requestServiceRevisit": ("Request Service Revisit", "पुनः सेवा का अनुरोध करें"),
    "customer.requestServiceWithWorker": ("Request Service with {{name}}", "{{name}} के साथ सेवा का अनुरोध करें"),
    "customer.revisitInformation": ("Revisit Information:", "पुनः विज़िट जानकारी:"),
    "customer.revisitPlaceholder": ("e.g. The leak in the kitchen pipe started again after 2 hours. Needs washer replacement...", "उदा. रसोई के पाइप में 2 घंटे बाद फिर से रिसाव शुरू हो गया। वॉशर बदलने की जरूरत है..."),
    "customer.revisitReason1": ("Work still leaking / not holding pressure", "काम के बाद भी रिसाव / दबाव नहीं रुक रहा"),
    "customer.revisitReason2": ("Part improperly fitted or loose", "पुर्जा गलत तरीके से लगाया गया या ढीला है"),
    "customer.revisitReason3": ("Problem recurred within hours of repair", "मरम्मत के कुछ ही घंटों में समस्या फिर से आ गई"),
    "customer.revisitReason4": ("Incomplete cleanup or missing final check", "अधूरी सफाई या अंतिम जांच नहीं की गई"),
    "customer.revisitReasonRequired": ("Please provide a reason for the revisit request so the coordinator can inspect.", "कृपया पुनः विज़िट का कारण बताएं ताकि समन्वयक जांच कर सके।"),
    "customer.scheduled": ("Scheduled", "निर्धारित"),
    "customer.scheduledDate": ("Scheduled Date:", "निर्धारित तिथि:"),
    "customer.searchServices": ("Search for plumbing, cleaning, repairs...", "प्लंबिंग, सफाई, मरम्मत आदि खोजें..."),
    "customer.step1Confirm": ("Step 1: Confirm work or request a revisit.", "चरण 1: कार्य की पुष्टि करें या पुनः सेवा मांगें।"),
    "customer.submitRevisitRequest": ("Submit Revisit Request", "पुनः सेवा अनुरोध सबमिट करें"),
    "customer.tabs.active": ("Active", "सक्रिय"),
    "customer.tabs.all": ("All Requests", "सभी अनुरोध"),
    "customer.tabs.completed": ("Completed", "पूर्ण"),
    "customer.tabs.history": ("History", "इतिहास"),
    "customer.tabs.issues": ("Service Issues", "सेवा समस्याएँ"),
    "customer.totalSettled": ("Total Settled:", "कुल निपटान:"),
    "customer.track": ("Track", "ट्रैक करें"),
    "customer.willResumeShortly": ("{{name}} will resume work shortly", "{{name}} शीघ्र ही काम पुनः शुरू करेंगे"),
    "customer.workerFinishedInspect": ("Worker has finished! Please inspect & confirm work.", "कार्यकर्ता ने काम पूरा कर लिया है! कृपया जांचें और पुष्टि करें।"),
    "customer.workerOnBreakTitle": ("Worker is on a Short Break", "कार्यकर्ता अल्प विराम पर है"),
    "customer.yourSpecialist": ("Your specialist", "आपके विशेषज्ञ"),

    # Group Booking
    "groupBooking.back": ("Back", "वापस"),
    "groupBooking.createBtn": ("Start Group Booking", "समूह बुकिंग शुरू करें"),
    "groupBooking.creating": ("Creating…", "बनाया जा रहा है…"),
    "groupBooking.details.bookingNotFound": ("Booking not found.", "बुकिंग नहीं मिली।"),
    "groupBooking.details.bookingProgress": ("Booking Progress", "बुकिंग प्रगति"),
    "groupBooking.details.confirmedDate": ("Confirmed Date ✓", "पुष्ट तिथि ✓"),
    "groupBooking.details.confirmedTime": ("Confirmed Time ✓", "पुष्ट समय ✓"),
    "groupBooking.details.costBreakdown": ("Cost Breakdown", "लागत विवरण"),
    "groupBooking.details.discount": ("Discount", "छूट"),
    "groupBooking.details.discountedTotal": ("Discounted Total", "छूट के बाद कुल"),
    "groupBooking.details.groupDiscount": ("Group Discount ({{percent}}%)", "समूह छूट ({{percent}}%)"),
    "groupBooking.details.groupSaving": ("group saving", "समूह बचत"),
    "groupBooking.details.individualAllocations": ("Individual Allocations", "व्यक्तिगत आवंटन"),
    "groupBooking.details.invoiceReady": ("Invoice Ready — Pay Your Share", "चालान तैयार — अपना हिस्सा चुकाएं"),
    "groupBooking.details.loadError": ("Payment confirmation failed. Please contact support.", "भुगतान पुष्टि विफल रही। कृपया सहायता से संपर्क करें।"),
    "groupBooking.details.ofMax": ("of max {{max}}", "अधिकतम {{max}} में से"),
    "groupBooking.details.organisedBy": ("Organised by {{name}}", "{{name}} द्वारा आयोजित"),
    "groupBooking.details.paid": ("Paid", "भुगतान किया गया"),
    "groupBooking.details.paidPendingSummary": ("{{paid}} paid · {{pending}} pending", "{{paid}} भुगतान पूर्ण · {{pending}} शेष"),
    "groupBooking.details.participantsSection": ("Participants ({{count}})", "प्रतिभागी ({{count}})"),
    "groupBooking.details.participantsStat": ("Participants", "प्रतिभागी"),
    "groupBooking.details.payNow": ("Pay Now", "अभी भुगतान करें"),
    "groupBooking.details.paymentConfirmed": ("Payment Confirmed!", "भुगतान की पुष्टि हुई!"),
    "groupBooking.details.preferredDate": ("Preferred Date", "पसंदीदा तिथि"),
    "groupBooking.details.retry": ("Retry", "पुनः प्रयास करें"),
    "groupBooking.details.schedule": ("Schedule", "समय सारणी"),
    "groupBooking.details.settled": ("{{pct}}% settled", "{{pct}}% निपटान हुआ"),
    "groupBooking.details.timeWindow": ("Time Window", "समय अवधि"),
    "groupBooking.details.title": ("Booking Details", "बुकिंग विवरण"),
    "groupBooking.details.totalServiceCost": ("Total Service Cost", "कुल सेवा लागत"),
    "groupBooking.details.workerAssignments": ("Worker Assignments", "कार्यकर्ता कार्यभार"),
    "groupBooking.details.youParenthetical": ("(You)", "(आप)"),
    "groupBooking.details.youSuffix": ("· You", "· आप"),
    "groupBooking.details.yourShare": ("Your Share", "आपका हिस्सा"),
    "groupBooking.details.yourShareAmount": ("Your share: ₹{{amount}}", "आपका हिस्सा: ₹{{amount}}"),
    "groupBooking.detailsBtn": ("Details", "विवरण"),
    "groupBooking.enterBriefDesc": ("Please enter a brief description of the group requirement.", "कृपया समूह आवश्यकता का संक्षिप्त विवरण दर्ज करें।"),
    "groupBooking.filterAll": ("All ({{count}})", "सभी ({{count}})"),
    "groupBooking.filterCompleted": ("Completed", "पूर्ण"),
    "groupBooking.filterInProgress": ("In Progress", "प्रगति पर"),
    "groupBooking.filterOpen": ("Open", "खुला"),
    "groupBooking.full": ("Full", "भरा हुआ"),
    "groupBooking.groupCreatedMsg": ("Neighbors in your society can now join this request.", "आपकी सोसाइटी के पड़ोसी अब इस अनुरोध में शामिल हो सकते हैं।"),
    "groupBooking.groupCreatedTitle": ("Group Booking Created", "समूह बुकिंग बनाई गई"),
    "groupBooking.howItWorksDesc": ("When multiple households book the same service on the same day, the cooperative worker eliminates travel overhead. You get a direct 20% discount and the worker earns uninterrupted bulk wages — everyone wins.", "जब एक ही दिन कई घर एक ही सेवा बुक करते हैं, तो यात्रा लागत बचती है। आपको सीधी 20% छूट मिलती है और कार्यकर्ता को एकमुश्त मजदूरी — सभी का लाभ होता है।"),
    "groupBooking.howItWorksTitle": ("How Group Bookings Save You Money", "समूह बुकिंग से पैसे कैसे बचते हैं"),
    "groupBooking.inviteNeighborsDesc": ("Invite neighbors in your society to save together", "साथ मिलकर बचत करने के लिए सोसाइटी पड़ोसियों को आमंत्रित करें"),
    "groupBooking.joinGroup": ("Join Group Booking", "समूह बुकिंग में शामिल हों"),
    "groupBooking.joinGroupBtn": ("Join Group", "समूह में जुड़ें"),
    "groupBooking.joinedBtn": ("Joined", "शामिल हो गए"),
    "groupBooking.joinedCount": ("{{count}} joined", "{{count}} शामिल हुए"),
    "groupBooking.joinedGroupMsg": ("Added to community bulk request with 20% savings.", "20% बचत के साथ सामुदायिक समूह अनुरोध में जोड़ा गया।"),
    "groupBooking.joinedGroupSuccess": ("Joined Group Booking", "समूह बुकिंग में शामिल हुए"),
    "groupBooking.loadError": ("Unable to load group bookings.", "समूह बुकिंग लोड करने में असमर्थ।"),
    "groupBooking.next": ("Next →", "आगे →"),
    "groupBooking.noBookings": ("No group bookings yet", "अभी तक कोई समूह बुकिंग नहीं है"),
    "groupBooking.noBookingsSub": ("Be the first to start one for your society!", "अपनी सोसाइटी के लिए शुरुआत करने वाले पहले व्यक्ति बनें!"),
    "groupBooking.organisedBy": ("Organised by", "आयोजक"),
    "groupBooking.payShare": ("Pay My Share", "अपना हिस्सा चुकाएं"),
    "groupBooking.preferredDate": ("Preferred date", "पसंदीदा तिथि"),
    "groupBooking.retry": ("Retry", "पुनः प्रयास करें"),
    "groupBooking.splitStrategy.custom": ("Custom Amounts", "कस्टम राशियाँ"),
    "groupBooking.splitStrategy.equal": ("Equal Split", "बराबर विभाजन"),
    "groupBooking.splitStrategy.proportional": ("Proportional (by area)", "आनुपातिक (क्षेत्रफल के अनुसार)"),
    "groupBooking.spotsLeft": ("{{count}} spots left", "{{count}} स्थान शेष"),
    "groupBooking.spotsLeftOne": ("1 spot left", "1 स्थान शेष"),
    "groupBooking.startGroupBooking": ("Start Group Booking", "समूह बुकिंग शुरू करें"),
    "groupBooking.startSocietyGroupBooking": ("Start Society Group Booking", "सोसाइटी समूह बुकिंग शुरू करें"),
    "groupBooking.status.cancelled": ("Cancelled", "रद्द"),
    "groupBooking.status.completed": ("Completed", "पूर्ण"),
    "groupBooking.status.confirmed": ("Confirmed", "पुष्ट"),
    "groupBooking.status.draft": ("Draft", "प्रारूप"),
    "groupBooking.status.inProgress": ("In Progress", "प्रगति पर"),
    "groupBooking.status.invoiced": ("Invoiced", "चालान जारी"),
    "groupBooking.status.locked": ("Locked", "लॉक"),
    "groupBooking.status.open": ("Open", "खुला"),
    "groupBooking.status.paid": ("Paid", "भुगतान पूर्ण"),
    "groupBooking.status.partiallyPaid": ("Partial", "आंशिक भुगतान"),
    "groupBooking.statusBadge.cancelled": ("Cancelled", "रद्द"),
    "groupBooking.statusBadge.completed": ("Work Completed", "कार्य पूर्ण"),
    "groupBooking.statusBadge.confirmed": ("Confirmed – Worker Assigned", "पुष्ट – कार्यकर्ता नियत"),
    "groupBooking.statusBadge.draft": ("Draft", "प्रारूप"),
    "groupBooking.statusBadge.inProgress": ("Work In Progress", "कार्य प्रगति पर"),
    "groupBooking.statusBadge.invoiced": ("Invoice Sent", "चालान भेजा गया"),
    "groupBooking.statusBadge.locked": ("Locked – Cost Split Finalised", "लॉक – लागत विभाजन अंतिम"),
    "groupBooking.statusBadge.open": ("Open – Accepting Participants", "खुला – प्रतिभागी आमंत्रित हैं"),
    "groupBooking.statusBadge.paid": ("Fully Paid", "पूर्ण भुगतान"),
    "groupBooking.statusBadge.partiallyPaid": ("Partially Paid", "आंशिक भुगतान"),
    "groupBooking.subtitle": ("Book together with neighbours and unlock up to 20% group discounts.", "पड़ोसियों के साथ मिलकर बुक करें और 20% तक समूह छूट पाएं।"),
    "groupBooking.targetDate": ("Target Date", "लक्ष्य तिथि"),
    "groupBooking.title": ("Community Group Bookings", "सामुदायिक समूह बुकिंग"),
    "groupBooking.validationError": ("Please complete all fields before continuing.", "आगे बढ़ने से पहले कृपया सभी फ़ील्ड भरें।"),
    "groupBooking.yourShareEst": ("Your share (est.)", "आपका अनुमानित हिस्सा"),

    # Group Booking Participant statuses
    "groupBooking.participants.pending": ("Pending", "लंबित"),
    "groupBooking.participants.confirmed": ("Confirmed", "पुष्ट"),
    "groupBooking.participants.opt_out": ("Opted Out", "बाहर निकले"),
    "groupBooking.participants.removed": ("Removed", "हटाया गया"),
    "groupBooking.participants.invoiced": ("Invoiced", "चालान जारी"),
    "groupBooking.participants.paid": ("Paid", "भुगतान पूर्ण"),
    "groupBooking.participants.payment_failed": ("Payment Failed", "भुगतान विफल"),

    # CustomerDashboard dynamic additions
    "customer.servicesHeading": ("सहाAI Services", "सहाAI सेवाएँ"),
    "customer.tapAnyService": ("Tap any service to request", "अनुरोध करने के लिए किसी भी सेवा पर टैप करें"),
    "customer.fromPrice": ("From {{price}}", "{{price}} से शुरू"),
    "customer.toWorker": ("70% to worker", "70% कार्यकर्ता को"),
    "customer.yourActiveService": ("Your Active Service", "आपकी सक्रिय सेवा"),
    "customer.bookingNum": ("Booking #{{id}}", "बुकिंग #{{id}}"),
    "customer.emergencySosActive": ("Emergency Support during active service", "सक्रिय सेवा के दौरान आपातकालीन सहायता"),
    "customer.specialistAssignedBanner": ("✓ Specialist assigned — ready to track your service", "✓ विशेषज्ञ नियत — अपनी सेवा ट्रैक करने के लिए तैयार"),
    "customer.verified": ("✓ Verified", "✓ सत्यापित"),
    "customer.confirmingSpecialist": ("Cooperative matching engine is confirming your specialist...", "सहकारी मिलान इंजन आपके विशेषज्ञ की पुष्टि कर रहा है..."),
    "customer.trackService": ("Track Service", "सेवा ट्रैक करें"),
    "customer.payAmountBtn": ("Pay ₹{{amount}}", "₹{{amount}} का भुगतान करें"),
    "customer.popularIn": ("Popular in {{society}}", "{{society}} में लोकप्रिय"),
    "customer.seasonalCarePackages": ("Seasonal care packages", "मौसमी सेवा पैकेज"),
    "customer.book": ("Book", "बुक करें"),
    "customer.neighborsBooking": ("Your neighbors are booking", "आपके पड़ोसी बुक कर रहे हैं"),
    "customer.joinBulkRequests": ("Join bulk requests in {{society}} for group discounts", "समूह छूट के लिए {{society}} में सामूहिक अनुरोधों से जुड़ें"),
    "customer.viewAllCount": ("View all ({{count}}) →", "सभी देखें ({{count}}) →"),
    "customer.communityDiscount": ("Community Discount", "सामुदायिक छूट"),
    "customer.homesCount": ("{{count}} homes", "{{count}} घर"),
    "customer.joinedInSociety": ("joined in your society", "आपकी सोसाइटी में शामिल हुए"),
    "customer.coopBatchService": ("Cooperative batch service", "सहकारी बैच सेवा"),
    "customer.joined": ("Joined", "शामिल हुए"),
    "customer.joinRequest": ("Join Request", "अनुरोध में जुड़ें"),
    "customer.joinedGroupBookingTitle": ("Joined Group Booking", "समूह बुकिंग में शामिल हुए"),
    "customer.joinedGroupBookingMsg": ("Added to {{category}} batch request.", "{{category}} बैच अनुरोध में जोड़ा गया।"),
    "customer.startManageGroupBookings": ("Start or Manage Group Bookings", "समूह बुकिंग शुरू या प्रबंधित करें"),
    "customer.groupBookingSubtitle": ("Create, join, track, and pay your share — full group booking flow", "बनाएं, जुड़ें, ट्रैक करें और अपना हिस्सा चुकाएं — पूर्ण समूह बुकिंग"),
    "customer.yourCommunity": ("Your Community", "आपका समुदाय"),
    "customer.openCommunityHub": ("Open Community Hub →", "समुदाय केंद्र खोलें →"),
    "customer.societyUpdateBadge": ("Society Update", "सोसाइटी समाचार"),
    "customer.societyManagerRole": ("Society Manager", "सोसाइटी प्रबंधक"),
    "customer.recentActivity": ("Recent Activity", "हाल की गतिविधि"),
    "customer.viewFullActivity": ("View Full Activity →", "पूरी गतिविधि देखें →"),
    "customer.completedOnDate": ("Completed on {{date}} · ₹{{amount}}", "{{date}} को पूर्ण · ₹{{amount}}"),
    "customer.settled": ("Settled", "निपटान हुआ"),
    "customer.talkToHuman": ("Need Help? Talk to a Human Support Specialist", "सहायता चाहिए? सीधे मानव सहायता विशेषज्ञ से बात करें"),
    "customer.noChatbots": ("No Chatbots", "कोई चैटबॉट नहीं"),
    "customer.humanSupportDesc": ("Live in-app chat, one-tap callback request, and WhatsApp support with auto-attached booking IDs.", "लाइव चैट, एक-टैप कॉलबैक और ऑटो-अटैच बुकिंग आईडी के साथ व्हाट्सएप सहायता।"),
    "customer.connectWithHuman": ("Connect with Human Agent", "मानव सहायता एजेंट से जुड़ें"),

    # Category items
    "customer.category.plumbing": ("Plumbing", "प्लंबिंग"),
    "customer.categoryDesc.plumbing": ("Leaks, taps, drains & pipes", "लीकेज, नल, ड्रेन और पाइप मरम्मत"),
    "customer.category.electrical": ("Electrical", "इलेक्ट्रिकल"),
    "customer.categoryDesc.electrical": ("Wiring, MCBs, fans & switches", "वायरिंग, एमसीबी, पंखे और स्विच"),
    "customer.category.cleaning": ("Cleaning", "सफाई"),
    "customer.categoryDesc.cleaning": ("Deep cleaning & bathroom descaling", "डीप क्लीनिंग और बाथरूम सफाई"),
    "customer.category.carpentry": ("Carpentry", "बढ़ईगीरी"),
    "customer.categoryDesc.carpentry": ("Doors, locks, hinges & furniture", "दरवाजे, ताले, कब्जे और फर्नीचर"),
    "customer.category.painting": ("Painting", "पेंटिंग"),
    "customer.categoryDesc.painting": ("Touch-ups, waterproofing & walls", "टच-अप, वाटरप्रूफिंग और दीवारें"),
    "customer.category.appliance_repairs": ("Appliance Repairs", "उपकरण मरम्मत"),
    "customer.categoryDesc.appliance_repairs": ("AC, fridge, geyser & washing machine", "एसी, फ्रिज, गीजर और वाशिंग मशीन"),
    "customer.category.pest_control": ("Pest Control", "कीट नियंत्रण"),
    "customer.categoryDesc.pest_control": ("Cockroach, termite & mosquito misting", "कॉकरोच, दीमक और मच्छर छिड़काव"),
    "customer.category.gardening___greenery": ("Gardening & Greenery", "बागवानी एवं हरियाली"),
    "customer.categoryDesc.gardening___greenery": ("Balcony garden, trimming & pots", "बालकनी गार्डन, कटाई और गमले"),
    "customer.category.security___cctv": ("Security & CCTV", "सुरक्षा एवं सीसीटीवी"),
    "customer.categoryDesc.security___cctv": ("Video doorbell, camera setup & sensors", "वीडियो डोरबेल, कैमरा सेटअप और सेंसर"),

    # Packages
    "customer.pkgBadge_monsoon": ("Seasonal Essential", "मौसमी आवश्यकता"),
    "customer.pkgTitle_monsoon": ("Monsoon Waterproofing & Leak Check", "मानसून वाटरप्रूफिंग एवं लीकेज जांच"),
    "customer.pkgDesc_monsoon": ("Comprehensive drain flushing & roof seal check for heavy rain.", "भारी बारिश के लिए ड्रेन फ्लशिंग और छत सील जांच।"),
    "customer.pkgBadge_summer_ac": ("Popular", "लोकप्रिय"),
    "customer.pkgTitle_summer_ac": ("Pre-Summer AC Master Servicing", "गर्मी पूर्व एसी मास्टर सर्विसिंग"),
    "customer.pkgDesc_summer_ac": ("High-pressure filter wash & cooling check by certified technician.", "प्रमाणित तकनीशियन द्वारा हाई-प्रेशर फिल्टर वॉश और कूलिंग जांच।"),
    "customer.pkgBadge_elec_audit": ("Preventative", "निवारक सुरक्षा"),
    "customer.pkgTitle_elec_audit": ("Apartment Electrical Safety Audit", "अपार्टमेंट इलेक्ट्रिकल सुरक्षा ऑडिट"),
    "customer.pkgDesc_elec_audit": ("Detailed distribution board check to avoid sudden power tripping.", "अचानक बिजली ट्रिपिंग से बचने के लिए वितरण बोर्ड की विस्तृत जांच।"),
}

# Ensure all raw keys are in TRANSLATIONS
for k in raw:
    if k not in TRANSLATIONS:
        # Default fallback
        TRANSLATIONS[k] = (raw[k], raw[k])

with open('scripts/locales_data/customer.py', 'w', encoding='utf-8') as f:
    f.write('# Customer, Group Booking, Payment, Emergency, Tracking, Dispute, SOS translations\n\nDATA = {\n')
    for k, (en_val, hi_val) in sorted(TRANSLATIONS.items()):
        en_clean = en_val.replace('\"', '\\\"')
        hi_clean = hi_val.replace('\"', '\\\"')
        f.write(f'    \"{k}\": (\"{en_clean}\", \"{hi_clean}\"),\n')
    f.write('}\n')

print(f"Customer module built! Total keys: {len(TRANSLATIONS)}")
