# Complete Part 1 translation generator (313 keys)
import json

raw_data = json.load(open('scripts/locales_data/worker_raw.json'))

part1_keys = [k for k in sorted(raw_data.keys()) if k.startswith(('addSkill.', 'jobStatus.', 'worker.dashboard.', 'worker.jobs.', 'worker.jobExec.', 'worker.break', 'worker.notifications.', 'worker.photoTile.', 'worker.stepLabels.', 'worker.work.')) or k in ('worker.acceptJob', 'worker.processing', 'worker.startBreak', 'worker.resumeWork', 'worker.priorityEmergency', 'worker.priorityUrgent', 'worker.jobRequest')]

translations = {
    # addSkill.*
    "addSkill.addAnotherSkill": ("+ Add Another Skill", "+ दूसरा कौशल जोड़ें"),
    "addSkill.bannerDesc": ("This form records the skilled worker's trade experience and service area for cooperative database management.", "यह प्रपत्र सहकारी डेटाबेस प्रबंधन हेतु कुशल कार्यकर्ता के व्यापार अनुभव और सेवा क्षेत्र को दर्ज करता है।"),
    "addSkill.bannerTitle": ("Manager-Side Skill Record:", "प्रबंधक-पक्षीय कौशल रिकॉर्ड:"),
    "addSkill.certSubtitle": ("Trade diploma, vocational certificate, or training card", "ट्रेड डिप्लोमा, व्यावसायिक प्रमाणपत्र, या प्रशिक्षण कार्ड"),
    "addSkill.charsCount": ("{{count}}/500 chars", "{{count}}/500 वर्ण"),
    "addSkill.chooseFile": ("Choose File", "फ़ाइल चुनें"),
    "addSkill.customAreaPlaceholder": ("Or enter custom Area / PIN code (e.g. Baner, Pune 411045)", "या कस्टम क्षेत्र / पिन कोड दर्ज करें (उदा. बानेर, पुणे 411045)"),
    "addSkill.descPlaceholder": ("Describe specific trade expertise, equipment handled, problem resolution capabilities...", "विशिष्ट व्यापार विशेषज्ञता, संभाले गए उपकरण, समस्या समाधान क्षमताओं का वर्णन करें..."),
    "addSkill.errAreaReq": ("Please specify the service area.", "कृपया सेवा क्षेत्र निर्दिष्ट करें।"),
    "addSkill.errDescLen": ("Skill description must be between 20 and 500 characters.", "कौशल विवरण 20 और 500 वर्णों के बीच होना चाहिए।"),
    "addSkill.errExpRange": ("Years of experience must be between 0 and 50.", "अनुभव के वर्ष 0 और 50 के बीच होने चाहिए।"),
    "addSkill.errFileSize": ("Skill Certificate file must be under 5 MB.", "कौशल प्रमाणपत्र फ़ाइल 5 एमबी से कम होनी चाहिए।"),
    "addSkill.errSkillReq": ("Please select a primary skill / trade.", "कृपया एक प्राथमिक कौशल / व्यापार चुनें।"),
    "addSkill.fieldArea": ("5. Service Area (Area / City / PIN)", "5. सेवा क्षेत्र (क्षेत्र / शहर / पिन)"),
    "addSkill.fieldCert": ("4. Skill Certificate (Optional · JPG / JPEG / PNG / PDF, max 5 MB)", "4. कौशल प्रमाणपत्र (वैकल्पिक · जेपीजी / जेपीईजी / पीएनजी / पीडीएफ, अधिकतम 5 एमबी)"),
    "addSkill.fieldDesc": ("3. Skill Description (20–500 characters)", "3. कौशल विवरण (20–500 वर्ण)"),
    "addSkill.fieldExp": ("2. Years of Experience (0–50 years)", "2. अनुभव के वर्ष (0–50 वर्ष)"),
    "addSkill.fieldSkill": ("1. Primary Skill / Trade", "1. प्राथमिक कौशल / व्यापार"),
    "addSkill.noFileSelected": ("No file selected", "कोई फ़ाइल नहीं चुनी गई"),
    "addSkill.saveSkill": ("Save Skill Record", "कौशल रिकॉर्ड सहेजें"),
    "addSkill.saving": ("Saving Skill...", "कौशल सहेजा जा रहा है..."),
    "addSkill.skillAddedMsg": ("{{skill}} added for {{name}}.", "{{name}} के लिए {{skill}} जोड़ा गया।"),
    "addSkill.skillAddedTitle": ("Skill Added", "कौशल जोड़ा गया"),
    "addSkill.subtitle": ("Level 2: Skill Information Record for {{workerName}}", "{{workerName}} के लिए स्तर 2: कौशल सूचना रिकॉर्ड"),
    "addSkill.successMsg": ("{{primarySkill}} ({{experienceYears}} yrs) recorded for {{workerName}}. Ready for Manager check.", "{{workerName}} के लिए {{primarySkill}} ({{experienceYears}} वर्ष) दर्ज। प्रबंधक जांच के लिए तैयार।"),
    "addSkill.successTitle": ("Skill Added Successfully", "कौशल सफलतापूर्वक जोड़ा गया"),
    "addSkill.title": ("+ Add Skill Now", "+ अब कौशल जोड़ें"),

    # jobStatus.*
    "jobStatus.arrived": ("Arrived On-Site", "कार्यस्थल पर पहुंचे"),
    "jobStatus.assigned": ("Assigned", "आवंटित"),
    "jobStatus.awaitingVerification": ("Awaiting Verification", "सत्यापन की प्रतीक्षा"),
    "jobStatus.cancelled": ("Cancelled", "रद्द किया गया"),
    "jobStatus.completed": ("Completed", "पूर्ण हुआ"),
    "jobStatus.confirmed": ("Confirmed", "पुष्टि की गई"),
    "jobStatus.inProgress": ("In Progress", "प्रगति पर"),
    "jobStatus.new": ("New Request", "नया अनुरोध"),
    "jobStatus.newAssignment": ("New Assignment", "नया कार्य आवंटन"),
    "jobStatus.openRequest": ("Open Request", "खुला अनुरोध"),
    "jobStatus.paid": ("Paid & Settled", "भुगतान एवं निपटान पूर्ण"),
    "jobStatus.qualityIssue": ("Quality Issue", "गुणवत्ता समस्या"),
    "jobStatus.rated": ("Rated ★", "रेटिंग प्राप्त ★"),
    "jobStatus.rejected": ("Rejected", "अस्वीकृत"),
    "jobStatus.revisitRequested": ("Revisit Requested", "पुनः यात्रा का अनुरोध"),
    "jobStatus.revisitScheduled": ("Revisit Scheduled", "पुनः यात्रा निर्धारित"),
    "jobStatus.travelling": ("En Route", "रास्ते में"),
    "jobStatus.unknown": ("Unknown", "अज्ञात"),
    "jobStatus.upcoming": ("Upcoming", "आगामी"),

    # Top-level worker actions & indicators
    "worker.acceptJob": ("Accept Job — ₹{{amount}}", "कार्य स्वीकार करें — ₹{{amount}}"),
    "worker.processing": ("Processing…", "प्रक्रिया जारी है…"),
    "worker.startBreak": ("Start {{label}}", "{{label}} शुरू करें"),
    "worker.resumeWork": ("Resume Work Now", "अब काम फिर से शुरू करें"),
    "worker.priorityEmergency": ("EMERGENCY", "आपातकालीन"),
    "worker.priorityUrgent": ("URGENT", "अति आवश्यक"),
    "worker.jobRequest": ("JOB REQUEST", "कार्य अनुरोध"),
    "worker.breakReason": ("Reason:", "कारण:"),

    # worker.break*
    "worker.breakTitle": ("Take a Break", "ब्रेक लें"),
    "worker.breakDurationLabel": ("Select Break Duration:", "ब्रेक की अवधि चुनें:"),
    "worker.breakMinutes": ("{{minutes}} Minutes", "{{minutes}} मिनट"),
    "worker.breakEndsIn": ("Break ends in {{time}}", "ब्रेक {{time}} में समाप्त होगा"),
    "worker.breakDispatchNotice": ("Job dispatch paused · Automatic wake up", "कार्य प्रेषण रुका हुआ · स्वचालित पुनः सक्रियता"),
    "worker.breakShort": ("15 min · Quick Tea", "15 मिनट · त्वरित चाय"),
    "worker.breakLunch": ("30 min · Lunch Break", "30 मिनट · दोपहर का भोजन"),
    "worker.breakCustom": ("45 min · Rest / Prayer", "45 मिनट · विश्राम / प्रार्थना"),
    "worker.breakUnavailable": ("Unavailable for rest of day", "दिन के शेष समय के लिए अनुपलब्ध"),

    # worker.breakPicker.*
    "worker.breakPicker.breakDurationLabel": ("Break Duration", "ब्रेक की अवधि"),
    "worker.breakPicker.confirmBtn": ("Start {{duration}}-Minute Break", "{{duration}}-मिनट का ब्रेक शुरू करें"),
    "worker.breakPicker.customMin": ("Custom (minutes)", "कस्टम (मिनट)"),
    "worker.breakPicker.customReasonPlaceholder": ("Describe reason…", "कारण बताएं…"),
    "worker.breakPicker.durationBtn": ("{{d}} min", "{{d}} मिनट"),
    "worker.breakPicker.durationLabel": ("Duration", "अवधि"),
    "worker.breakPicker.enterMinutesPlaceholder": ("Enter minutes (1-180)", "मिनट दर्ज करें (1-180)"),
    "worker.breakPicker.errorInvalid": ("Please enter a duration between 1 and 180 minutes.", "कृपया 1 से 180 मिनट के बीच की अवधि दर्ज करें।"),
    "worker.breakPicker.pauseNotice": ("Job requests will be temporarily paused during your break.", "आपके ब्रेक के दौरान कार्य अनुरोध अस्थायी रूप से रोक दिए जाएंगे।"),
    "worker.breakPicker.preset15": ("15m Quick", "15 मिनट त्वरित"),
    "worker.breakPicker.preset30": ("30m Lunch", "30 मिनट दोपहर भोजन"),
    "worker.breakPicker.preset45": ("45m Rest", "45 मिनट विश्राम"),
    "worker.breakPicker.preset60": ("60m Long", "60 मिनट लंबा"),
    "worker.breakPicker.quickPresets": ("Quick Presets", "त्वरित प्रीसेट"),
    "worker.breakPicker.reasonLabel": ("Reason (Optional)", "कारण (वैकल्पिक)"),
    "worker.breakPicker.reasonLunch": ("Lunch Break", "दोपहर का भोजन"),
    "worker.breakPicker.reasonMaterials": ("Sourcing Materials", "सामग्री लाना"),
    "worker.breakPicker.reasonOther": ("Other…", "अन्य…"),
    "worker.breakPicker.reasonParts": ("Sourcing Parts", "पुर्जे लाना"),
    "worker.breakPicker.reasonPersonal": ("Personal Break", "व्यक्तिगत ब्रेक"),
    "worker.breakPicker.reasonPlaceholder": ("e.g. Lunch break, Personal work", "उदा. दोपहर का भोजन, व्यक्तिगत कार्य"),
    "worker.breakPicker.reasonPrayer": ("Prayer Break", "प्रार्थना ब्रेक"),
    "worker.breakPicker.subtitle": ("Customer will be notified automatically", "ग्राहक को स्वचालित रूप से सूचित किया जाएगा"),
    "worker.breakPicker.title": ("Take a Break", "ब्रेक लें"),

    # worker.notifications.*
    "worker.notifications.markAllRead": ("Mark all as read", "सभी को पढ़ा हुआ चिह्नित करें"),
    "worker.notifications.newCount": ("{{count}} new", "{{count}} नए"),
    "worker.notifications.noNotifications": ("No notifications yet", "अभी तक कोई सूचना नहीं"),
    "worker.notifications.noNotifsSub": ("Job updates, payments, and announcements will appear here.", "कार्य अपडेट, भुगतान और घोषणाएं यहां दिखाई देंगी।"),
    "worker.notifications.noNotifsTitle": ("No notifications yet", "अभी तक कोई सूचना नहीं"),
    "worker.notifications.recentActivity": ("Recent Activity", "हालिया गतिविधि"),
    "worker.notifications.subtitle": ("Job dispatches, payments, cooperative updates and alerts", "कार्य प्रेषण, भुगतान, सहकारी अपडेट और अलर्ट"),
    "worker.notifications.systemNotifs": ("System Notifications", "सिस्टम सूचनाएं"),
    "worker.notifications.tabAll": ("All", "सभी"),
    "worker.notifications.tabAlerts": ("Alerts", "अलर्ट"),
    "worker.notifications.tabEarnings": ("Earnings", "कमाई"),
    "worker.notifications.tabJobs": ("Jobs", "कार्य"),
    "worker.notifications.title": ("Notifications", "सूचनाएं"),

    # worker.photoTile.*
    "worker.photoTile.recorded": ("{{label}} Recorded", "{{label}} रिकॉर्ड किया गया"),
    "worker.photoTile.retakeChange": ("Retake / Change", "पुनः लें / बदलें"),
    "worker.photoTile.retakeChangeLabel": ("Retake / Change {{label}}", "{{label}} पुनः लें / बदलें"),
    "worker.photoTile.takeUploadLabel": ("Take / Upload {{label}}", "{{label}} लें / अपलोड करें"),
    "worker.photoTile.tapToCapture": ("Tap to capture with camera or select from device gallery", "कैमरे से फोटो लेने या डिवाइस गैलरी से चुनने के लिए टैप करें"),
    "worker.photoTile.tapToUpload": ("Tap to take / upload photo", "फोटो लेने / अपलोड करने के लिए टैप करें"),
    "worker.photoTile.uploading": ("Uploading photo...", "फोटो अपलोड हो रही है..."),

    # worker.stepLabels.*
    "worker.stepLabels.1": ("Before Photo", "कार्य-पूर्व फोटो"),
    "worker.stepLabels.2": ("Start Work", "कार्य प्रारंभ"),
    "worker.stepLabels.3": ("After Photo", "कार्य-उपरांत फोटो"),
    "worker.stepLabels.4": ("Mark Complete", "पूर्ण चिह्नित करें"),
    "worker.stepLabels.arrive": ("Arrive", "पहुंचे"),
    "worker.stepLabels.complete": ("Complete", "पूर्ण"),
    "worker.stepLabels.start": ("Start", "शुरू"),
    "worker.stepLabels.travel": ("Travel", "यात्रा"),

    # worker.work.*
    "worker.work.operationsBadge": ("Worker Operations", "कार्यकर्ता परिचालन"),
    "worker.work.subtitle": ("Manage your service pipeline, active assignments, OTP verification, and earnings ledger.", "अपनी सेवा पाइपलाइन, सक्रिय कार्य, ओटीपी सत्यापन और कमाई लेजर प्रबंधित करें।"),
    "worker.work.tabCommunity": ("Trade Guilds", "ट्रेड गिल्ड"),
    "worker.work.tabEarnings": ("My Earnings", "मेरी कमाई"),
    "worker.work.tabJobs": ("My Jobs", "मेरे कार्य"),
    "worker.work.tabToolBank": ("Tool Bank", "टूल बैंक"),

    # worker.dashboard.*
    "worker.dashboard.acceptAmountBtn": ("Accept (₹{{amount}})", "स्वीकार करें (₹{{amount}})"),
    "worker.dashboard.acceptingBtn": ("Accepting…", "स्वीकार किया जा रहा है…"),
    "worker.dashboard.activeAllocationNotice": ("You are active in the allocation queue. Nearby requests will pop up automatically.", "आप आवंटन कतार में सक्रिय हैं। पास के अनुरोध स्वचालित रूप से दिखाई देंगे।"),
    "worker.dashboard.activeHotspots": ("Active Cooperative Demand Hotspots", "सक्रिय सहकारी मांग हॉटस्पॉट"),
    "worker.dashboard.activeStat": ("active", "सक्रिय"),
    "worker.dashboard.arrivedAction": ("Tap Arrived at Gate / Customer Flat", "गेट / ग्राहक के फ़्लैट पर आगमन पर टैप करें"),
    "worker.dashboard.arrivedBtn": ("Mark Arrived", "पहुंचना दर्ज करें"),
    "worker.dashboard.availableDesc": ("Ready for new job assignments in your assigned society clusters", "आपके आवंटित सोसाइटी क्लस्टर में नए कार्य आवंटन के लिए तैयार"),
    "worker.dashboard.availableMsg": ("New job requests will be dispatched to you based on skill and proximity.", "कौशल और निकटता के आधार पर आपको नए कार्य अनुरोध भेजे जाएंगे।"),
    "worker.dashboard.availableTitle": ("🟢 You are now Available", "🟢 अब आप उपलब्ध हैं"),
    "worker.dashboard.breakDesc": ("Dispatching is paused. You will not receive new requests until your break finishes or you resume.", "प्रेषण रुका हुआ है। आपका ब्रेक समाप्त होने या फिर से शुरू करने तक नए अनुरोध नहीं मिलेंगे।"),
    "worker.dashboard.breakEndsIn": ("Break ends in {{time}}", "ब्रेक {{time}} में समाप्त होगा"),
    "worker.dashboard.breakStartedMsg": ("You are temporarily paused for {{duration}} minutes.", "आप {{duration}} मिनट के लिए अस्थायी रूप से रुके हुए हैं।"),
    "worker.dashboard.breakStartedTitle": ("Break Started", "ब्रेक शुरू हुआ"),
    "worker.dashboard.breakTitle": ("On Temporary Break", "अस्थायी ब्रेक पर"),
    "worker.dashboard.callBtn": ("Call", "कॉल करें"),
    "worker.dashboard.callCustomer": ("Call Customer", "ग्राहक को कॉल करें"),
    "worker.dashboard.callResident": ("Call Resident", "निवासी को कॉल करें"),
    "worker.dashboard.callSecurity": ("Call Security", "सुरक्षा को कॉल करें"),
    "worker.dashboard.closeHeatmap": ("Close Heatmap", "हीटमैप बंद करें"),
    "worker.dashboard.completedStat": ("completed", "पूर्ण"),
    "worker.dashboard.confirmedNet": ("Confirmed Net", "पुष्ट शुद्ध राशि"),
    "worker.dashboard.coopBatchNotice": ("Cooperative batch request · 20% resident discount applied · Full payout to worker guaranteed", "सहकारी बैच अनुरोध · 20% निवासी छूट लागू · कार्यकर्ता को पूर्ण भुगतान की गारंटी"),
    "worker.dashboard.customerNotifiedMyWork": ("Customer notified. Added to My Work.", "ग्राहक को सूचित किया गया। 'मेरे कार्य' में जोड़ा गया।"),
    "worker.dashboard.customerNotifiedUpcoming": ("Customer notified. Added to Upcoming jobs.", "ग्राहक को सूचित किया गया। आगामी कार्यों में जोड़ा गया।"),
    "worker.dashboard.declineBtn": ("Decline", "अस्वीकार करें"),
    "worker.dashboard.demandForecastUpdate": ("Predictive demand forecast updated every 30 mins", "अनुमानित मांग पूर्वानुमान हर 30 मिनट में अपडेट होता है"),
    "worker.dashboard.demandNearYou": ("Demand Near You", "आपके पास मांग"),
    "worker.dashboard.distanceLabel": ("Distance: {{distance}}", "दूरी: {{distance}}"),
    "worker.dashboard.enableSharing": ("Enable Sharing", "साझाकरण सक्षम करें"),
    "worker.dashboard.enterCustomerOtp": ("Enter Customer 4-Digit OTP to Start", "शुरू करने के लिए ग्राहक का 4-अंकीय ओटीपी दर्ज करें"),
    "worker.dashboard.estimatedNet": ("Est. Earnings", "अनुमानित कमाई"),
    "worker.dashboard.exploreDemandHeatmap": ("Explore Demand Heatmap", "मांग हीटमैप देखें"),
    "worker.dashboard.heatmapModalSubtitle": ("Cooperative Spatial Dispatch Engine & Active Clusters", "सहकारी स्थानिक प्रेषण इंजन और सक्रिय क्लस्टर"),
    "worker.dashboard.heatmapModalTitle": ("Predictive Demand & Operational Sectors", "अनुमानित मांग एवं परिचालन क्षेत्र"),
    "worker.dashboard.hotspotsDesc": ("Live spatial demand distribution across Western Pune member societies and high-volume sectors.", "पश्चिमी पुणे सदस्य सोसायटियों और उच्च-मांग वाले क्षेत्रों में लाइव स्थानिक मांग वितरण।"),
    "worker.dashboard.immediateDispatch": ("Immediate Dispatch", "तत्काल प्रेषण"),
    "worker.dashboard.jobAccepted": ("Job Accepted! ✅", "कार्य स्वीकृत! ✅"),
    "worker.dashboard.jobDeclined": ("Job Declined", "कार्य अस्वीकृत"),
    "worker.dashboard.jobRef": ("Job Reference #{{id}}", "कार्य संदर्भ #{{id}}"),
    "worker.dashboard.liveCoopDispatch": ("Live Cooperative Dispatch", "लाइव सहकारी प्रेषण"),
    "worker.dashboard.locationActive": ("Live Location Sharing Active", "लाइव स्थान साझाकरण सक्रिय"),
    "worker.dashboard.locationPaused": ("Location Sharing Paused", "स्थान साझाकरण रुका हुआ"),
    "worker.dashboard.markedArrived": ("Marked as arrived! Customer has been notified.", "आगमन दर्ज! ग्राहक को सूचित कर दिया गया है।"),
    "worker.dashboard.markedTravelling": ("Status updated to Travelling. Customer can track your arrival.", "स्थिति 'यात्रा में' अपडेट की गई। ग्राहक आपके आगमन को ट्रैक कर सकता है।"),
    "worker.dashboard.navigateBtn": ("Navigate", "दिशा-निर्देश"),
    "worker.dashboard.newJobForYou": ("New Job For You", "आपके लिए नया कार्य"),
    "worker.dashboard.newJobSubtitle": ("Matched based on your skill, distance and availability", "आपके कौशल, दूरी और उपलब्धता के आधार पर मिलान किया गया"),
    "worker.dashboard.nextJob": ("Next Job", "अगला कार्य"),
    "worker.dashboard.nextJobTitle": ("Next Scheduled Job", "अगला निर्धारित कार्य"),
    "worker.dashboard.noActiveJobs": ("No active jobs right now", "अभी कोई सक्रिय कार्य नहीं"),
    "worker.dashboard.noPendingRequests": ("No pending requests", "कोई लंबित अनुरोध नहीं"),
    "worker.dashboard.noRequests": ("No pending requests at the moment", "इस समय कोई लंबित अनुरोध नहीं"),
    "worker.dashboard.noUpcomingJobs": ("No upcoming jobs scheduled yet.", "अभी तक कोई आगामी कार्य निर्धारित नहीं है।"),
    "worker.dashboard.offlineDesc": ("You are offline and will not receive customer requests", "आप ऑफलाइन हैं और ग्राहक अनुरोध प्राप्त नहीं करेंगे"),
    "worker.dashboard.offlineLabel": ("Offline", "ऑफलाइन"),
    "worker.dashboard.offlineMsg": ("You will not receive new dispatches while offline.", "ऑफलाइन होने पर आपको नए प्रेषण नहीं मिलेंगे।"),
    "worker.dashboard.offlineTitle": ("🔴 You are now Offline", "🔴 अब आप ऑफलाइन हैं"),
    "worker.dashboard.onDuty": ("On Duty · Available", "ड्यूटी पर · उपलब्ध"),
    "worker.dashboard.openInMyWork": ("Open in My Work →", "मेरे कार्य में खोलें →"),
    "worker.dashboard.openJobSheet": ("Open Job Sheet", "जॉब शीट खोलें"),
    "worker.dashboard.otpMatched": ("OTP verified! Service started.", "ओटीपी सत्यापित! सेवा शुरू हुई।"),
    "worker.dashboard.otpMismatch": ("Incorrect OTP. Please ask customer for the 4-digit start PIN.", "गलत ओटीपी। कृपया ग्राहक से 4-अंकीय प्रारंभ पिन मांगें।"),
    "worker.dashboard.passedNextSpecialist": ("Assignment passed to next specialist.", "कार्य अगले विशेषज्ञ को भेजा गया।"),
    "worker.dashboard.pingLabel": ("Ping:", "पिंग:"),
    "worker.dashboard.predictiveHeatmapLink": ("Predictive Heatmap Link", "अनुमानित हीटमैप लिंक"),
    "worker.dashboard.prioritySuffix": ("{{priority}} Priority", "{{priority}} प्राथमिकता"),
    "worker.dashboard.quickActionsTitle": ("Quick Actions", "त्वरित कार्रवाइयां"),
    "worker.dashboard.ratingLabel": ("Rating", "रेटिंग"),
    "worker.dashboard.requestDeclinedMsg": ("Request has been returned to fair matching pool.", "अनुरोध निष्पक्ष मिलान पूल में वापस कर दिया गया है।"),
    "worker.dashboard.requestDeclinedTitle": ("Request Declined", "अनुरोध अस्वीकृत"),
    "worker.dashboard.resumeBtn": ("Resume Work", "काम फिर से शुरू करें"),
    "worker.dashboard.resumedMsg": ("You are now online and available for jobs.", "अब आप ऑनलाइन हैं और कार्यों के लिए उपलब्ध हैं।"),
    "worker.dashboard.resumedTitle": ("Work Resumed", "काम फिर से शुरू हुआ"),
    "worker.dashboard.routedNextSpecialist": ("Assignment routed to the next available specialist.", "कार्य अगले उपलब्ध विशेषज्ञ को सौंपा गया।"),
    "worker.dashboard.safetySosBtn": ("Safety SOS", "सुरक्षा एसओएस"),
    "worker.dashboard.sharePercent": ("70% share", "70% हिस्सा"),
    "worker.dashboard.sharingActive": ("● Sharing Active", "● साझाकरण सक्रिय"),
    "worker.dashboard.startBreakBtn": ("Take Break", "ब्रेक लें"),
    "worker.dashboard.startJobBtn": ("Start Job", "कार्य शुरू करें"),
    "worker.dashboard.startTravelBtn": ("Start Travel", "यात्रा शुरू करें"),
    "worker.dashboard.stationLabel": ("Station:", "स्टेशन:"),
    "worker.dashboard.statusActive": ("Active Job in Progress", "सक्रिय कार्य प्रगति पर"),
    "worker.dashboard.statusAssigned": ("New Job Assigned", "नया कार्य आवंटित"),
    "worker.dashboard.statusAvailable": ("Available for Jobs", "कार्यों के लिए उपलब्ध"),
    "worker.dashboard.statusBreak": ("On Break", "ब्रेक पर"),
    "worker.dashboard.statusOffline": ("Currently Offline", "वर्तमान में ऑफलाइन"),
    "worker.dashboard.switchAvailableNotice": ("Switch to Available to receive new dispatches from your society.", "अपनी सोसाइटी से नए प्रेषण प्राप्त करने के लिए 'उपलब्ध' पर स्विच करें।"),
    "worker.dashboard.takeBreakAction": ("Take Break", "ब्रेक लें"),
    "worker.dashboard.thisWeekEarnings": ("This Week's Earnings", "इस सप्ताह की कमाई"),
    "worker.dashboard.todayJobs": ("Today's Jobs", "आज के कार्य"),
    "worker.dashboard.viewAllJobs": ("View All Jobs", "सभी कार्य देखें"),
    "worker.dashboard.viewAllMyWork": ("View all in My Work", "मेरे कार्य में सभी देखें"),
    "worker.dashboard.viewEarningsPayments": ("View Earnings & Payments", "कमाई एवं भुगतान देखें"),
    "worker.dashboard.viewFullSchedule": ("View Full Schedule", "पूरा शेड्यूल देखें"),
    "worker.dashboard.waitingForJobs": ("Waiting for next assignment...", "अगले आवंटन की प्रतीक्षा में..."),
    "worker.dashboard.welcomeBack": ("🟢 Welcome back!", "🟢 पुनः स्वागत है!"),
    "worker.dashboard.welcomeBackMsg": ("You are now ready to receive new job dispatches.", "अब आप नए कार्य प्रेषण प्राप्त करने के लिए तैयार हैं।"),

    # worker.jobExec.*
    "worker.jobExec.actionArrived": ("Confirm Arrived On-Site", "कार्यस्थल पर पहुंचने की पुष्टि करें"),
    "worker.jobExec.actionComplete": ("Mark Job Completed", "कार्य पूर्ण चिह्नित करें"),
    "worker.jobExec.actionStart": ("Start Service", "सेवा शुरू करें"),
    "worker.jobExec.actionTravel": ("Start Travel to Location", "स्थान के लिए यात्रा शुरू करें"),
    "worker.jobExec.afterPhoto": ("After-Work Photo", "कार्य के बाद की फोटो"),
    "worker.jobExec.afterPhotoHint": ("Clean finish view confirming completed repair", "पूर्ण मरम्मत की पुष्टि करने वाला स्वच्छ दृश्य"),
    "worker.jobExec.arrivedOtpDesc": ("Ask the customer for the 4-digit code shown on their Cooperative mobile screen to verify identity and unlock job execution.", "पहचान सत्यापित करने और कार्य निष्पादन शुरू करने के लिए ग्राहक से उनकी सहकारी स्क्रीन पर दिखाया गया 4-अंकीय कोड मांगें।"),
    "worker.jobExec.arrivedOtpTitle": ("Customer 4-Digit Arrival Code", "ग्राहक 4-अंकीय आगमन कोड"),
    "worker.jobExec.awaitingDesc": ("Job submitted. The society manager will review your before/after photos and approve the job. You'll be notified once it's cleared.", "कार्य सबमिट किया गया। सोसाइटी प्रबंधक आपकी पहले/बाद की तस्वीरों की समीक्षा करेगा और कार्य स्वीकृत करेगा। स्वीकृत होने पर आपको सूचित किया जाएगा।"),
    "worker.jobExec.awaitingTitle": ("Awaiting Manager Verification", "प्रबंधक सत्यापन की प्रतीक्षा"),
    "worker.jobExec.beforePhoto": ("Before-Work Photo", "कार्य से पहले की फोटो"),
    "worker.jobExec.beforePhotoHint": ("Clear shot of the broken/unfixed state before starting", "शुरू करने से पहले टूटी हुई/खराब स्थिति का स्पष्ट फोटो"),
    "worker.jobExec.bookingSubtitle": ("Booking", "बुकिंग"),
    "worker.jobExec.callCustomer": ("Call Customer", "ग्राहक को कॉल करें"),
    "worker.jobExec.callManager": ("Call Manager", "प्रबंधक को कॉल करें"),
    "worker.jobExec.callSecurity": ("Society Gate", "सोसाइटी गेट"),
    "worker.jobExec.cancelJob": ("Cancel Job", "कार्य रद्द करें"),
    "worker.jobExec.cancellationReasonPlaceholder": ("Reason for cancellation (e.g. Resident unreachable, hazardous conditions)...", "रद्द करने का कारण (उदा. निवासी से संपर्क नहीं, खतरनाक स्थिति)..."),
    "worker.jobExec.close": ("Close", "बंद करें"),
    "worker.jobExec.collectCash": ("Collect Cash Payment", "नकद भुगतान एकत्र करें"),
    "worker.jobExec.completedSettlement": ("Settlement of ₹{{amount}} is routed to your cooperative account.", "₹{{amount}} का निपटान आपके सहकारी खाते में भेजा गया है।"),
    "worker.jobExec.completedTitle": ("Job Successfully Completed!", "कार्य सफलतापूर्वक पूर्ण हुआ!"),
    "worker.jobExec.confirmArrival": ("Confirm Arrival At Society / Doorstep", "सोसाइटी / दरवाजे पर आगमन की पुष्टि करें"),
    "worker.jobExec.confirmCancellation": ("Confirm Cancellation", "रद्दीकरण की पुष्टि करें"),
    "worker.jobExec.confirmedDesc": ("You have accepted this job. Tap below when you begin travelling to notify the resident.", "आपने यह कार्य स्वीकार कर लिया है। निवासी को सूचित करने के लिए यात्रा शुरू करते समय नीचे टैप करें।"),
    "worker.jobExec.coopCommission": ("Coop Fund Share", "सहकारी फंड हिस्सा"),
    "worker.jobExec.customerAddress": ("Customer Address", "ग्राहक का पता"),
    "worker.jobExec.customerDestination": ("Customer & Destination", "ग्राहक एवं गंतव्य"),
    "worker.jobExec.customerNotes": ("Customer Notes", "ग्राहक की टिप्पणियाँ"),
    "worker.jobExec.customerOtpLabel": ("Enter Customer 4-Digit PIN to Begin", "शुरू करने के लिए ग्राहक का 4-अंकीय पिन दर्ज करें"),
    "worker.jobExec.customerOtpPlaceholder": ("4-digit OTP", "4-अंकीय ओटीपी"),
    "worker.jobExec.customerRating": ("Customer Rating", "ग्राहक रेटिंग"),
    "worker.jobExec.disputeNotice": ("Quality dispute open on this job. Revisit ticket is in review.", "इस कार्य पर गुणवत्ता विवाद खुला है। पुनः यात्रा टिकट समीक्षाधीन है।"),
    "worker.jobExec.enRoute": ("En Route to Customer Residence", "ग्राहक आवास के रास्ते में"),
    "worker.jobExec.enRouteNotice": ("Customer has been notified that you are en route. Live GPS telemetry is being transmitted for resident safety.", "ग्राहक को सूचित कर दिया गया है कि आप रास्ते में हैं। निवासी सुरक्षा के लिए लाइव जीपीएस भेजा जा रहा है।"),
    "worker.jobExec.enterOtpLabel": ("Enter 4-Digit Customer Code:", "4-अंकीय ग्राहक कोड दर्ज करें:"),
    "worker.jobExec.enterOtpToProceed": ("Please enter the 4-digit start OTP provided by the resident.", "कृपया निवासी द्वारा प्रदान किया गया 4-अंकीय प्रारंभ ओटीपी दर्ज करें।"),
    "worker.jobExec.estimatedEarnings": ("Your Earnings (70%)", "आपकी कमाई (70%)"),
    "worker.jobExec.eta": ("ETA:", "अनुमानित समय:"),
    "worker.jobExec.evidencePhotos": ("Evidence Photos (Before & After)", "साक्ष्य फोटो (पहले और बाद)"),
    "worker.jobExec.evidencePhotosReq": ("Please capture both Before and After photos to complete job verification.", "कार्य सत्यापन पूरा करने के लिए कृपया पहले और बाद दोनों की तस्वीरें लें।"),
    "worker.jobExec.evidenceSaved": ("Evidence photos attached to cooperative ledger.", "साक्ष्य फोटो सहकारी लेजर में संलग्न किए गए।"),
    "worker.jobExec.executionStage": ("Execution Stage:", "निष्पादन चरण:"),
    "worker.jobExec.finalInvoice": ("Final Invoice Breakdown", "अंतिम चालान विवरण"),
    "worker.jobExec.finishJob": ("Finish & Settle", "समाप्त करें एवं निपटान करें"),
    "worker.jobExec.gatePassCode": ("Gate Pass Code", "गेट पास कोड"),
    "worker.jobExec.gpsPin": ("GPS Pin:", "जीपीएस पिन:"),
    "worker.jobExec.instructions": ("Special Instructions", "विशेष निर्देश"),
    "worker.jobExec.jobCompleted": ("Job Completed!", "कार्य पूर्ण हुआ!"),
    "worker.jobExec.jobDescription": ("Job Description", "कार्य विवरण"),
    "worker.jobExec.jobDetails": ("Job Details", "कार्य विवरण"),
    "worker.jobExec.jobId": ("Job ID #{{id}}", "कार्य आईडी #{{id}}"),
    "worker.jobExec.jobNotes": ("Worker Completion Notes", "कार्यकर्ता समापन नोट्स"),
    "worker.jobExec.jobNotesPlaceholder": ("Detail what parts were replaced, tests run, or warranties noted...", "विस्तार से बताएं कि कौन से हिस्से बदले गए, परीक्षण किए गए, आदि..."),
    "worker.jobExec.jobSheetTitle": ("Active Cooperative Job Sheet", "सक्रिय सहकारी जॉब शीट"),
    "worker.jobExec.jobStatus": ("Current Status", "वर्तमान स्थिति"),
    "worker.jobExec.markComplete": ("Complete Service", "सेवा पूर्ण करें"),
    "worker.jobExec.materialsUsed": ("Materials / Replacement Parts Used", "उपयोग की गई सामग्री / बदले गए हिस्से"),
    "worker.jobExec.modalTitle": ("Job Execution Center", "कार्य निष्पादन केंद्र"),
    "worker.jobExec.navigate": ("Navigate to Location", "स्थान के लिए नेविगेट करें"),
    "worker.jobExec.navigateGoogleMaps": ("Navigate (Google Maps)", "नेविगेट करें (गूगल मैप्स)"),
    "worker.jobExec.noActiveBooking": ("No active job found.", "कोई सक्रिय कार्य नहीं मिला।"),
    "worker.jobExec.onBreakDuration": ("Duration", "अवधि"),
    "worker.jobExec.onBreakPaused": ("PAUSED", "रुका हुआ"),
    "worker.jobExec.onBreakReason": ("Reason", "कारण"),
    "worker.jobExec.onBreakSubtitle": ("Customer has been notified · Job paused", "ग्राहक को सूचित किया गया · कार्य रुका हुआ"),
    "worker.jobExec.onBreakTitle": ("You're on a Break", "आप ब्रेक पर हैं"),
    "worker.jobExec.openGpsNav": ("Open Live Turn-by-Turn GPS Navigation", "लाइव जीपीएस नेविगेशन खोलें"),
    "worker.jobExec.otpErrorEmpty": ("Please enter the 4-digit code provided by the customer.", "कृपया ग्राहक द्वारा दिया गया 4-अंकीय कोड दर्ज करें।"),
    "worker.jobExec.otpErrorIncorrect": ("Incorrect OTP. Please ask the customer to confirm the code shown on their app.", "गलत ओटीपी। कृपया ग्राहक से उनके ऐप में दिखाए गए कोड की पुष्टि करने को कहें।"),
    "worker.jobExec.otpHelp": ("Customer receives this PIN on their active booking screen.", "ग्राहक को यह पिन उनकी सक्रिय बुकिंग स्क्रीन पर मिलता है।"),
    "worker.jobExec.otpIncorrect": ("Invalid OTP entered. Please re-check with resident.", "अमान्य ओटीपी दर्ज किया गया। कृपया निवासी से पुनः जांच करें।"),
    "worker.jobExec.otpPlaceholder": ("e.g. 4829", "उदा. 4829"),
    "worker.jobExec.otpVerified": ("OTP Verified! You may now begin the repair work.", "ओटीपी सत्यापित! अब आप मरम्मत कार्य शुरू कर सकते हैं।"),
    "worker.jobExec.paymentCollected": ("Payment Collected Successfully", "भुगतान सफलतापूर्वक एकत्र किया गया"),
    "worker.jobExec.paymentMode": ("Payment Mode", "भुगतान का प्रकार"),
    "worker.jobExec.paymentSummary": ("Payment Summary", "भुगतान सारांश"),
    "worker.jobExec.pricingDetails": ("Pricing & Payout Details", "मूल्य निर्धारण एवं भुगतान विवरण"),
    "worker.jobExec.qrPayment": ("Customer Paying via UPI / Escrow", "ग्राहक यूपीआई / एस्क्रो के माध्यम से भुगतान कर रहा है"),
    "worker.jobExec.rateCustomer": ("Rate Customer Interaction", "ग्राहक सहभागिता को रेट करें"),
    "worker.jobExec.recorded": ("Recorded", "रिकॉर्ड किया गया"),
    "worker.jobExec.requirement": ("Requirement:", "आवश्यकता:"),
    "worker.jobExec.residentName": ("Resident Name", "निवासी का नाम"),
    "worker.jobExec.resumeNotice": ("Resuming will notify the customer that work has restarted.", "काम फिर से शुरू करने से ग्राहक को सूचित किया जाएगा कि काम फिर से शुरू हो गया है।"),
    "worker.jobExec.resumeWork": ("Resume Work", "काम फिर से शुरू करें"),
    "worker.jobExec.retakeChange": ("Retake / Change", "पुनः लें / बदलें"),
    "worker.jobExec.serviceCategory": ("Trade / Service", "ट्रेड / सेवा"),
    "worker.jobExec.settlementComplete": ("Settlement Complete", "निपटान पूर्ण"),
    "worker.jobExec.societyShare": ("Society Hub (5%)", "सोसाइटी केंद्र (5%)"),
    "worker.jobExec.startTravelling": ("Start Travelling to Customer", "ग्राहक के लिए यात्रा शुरू करें"),
    "worker.jobExec.started": ("Started", "शुरू हुआ"),
    "worker.jobExec.statusUpdated": ("Job status updated to {{status}}.", "कार्य स्थिति {{status}} में अपडेट की गई।"),
    "worker.jobExec.step1ContinueBtn": ("Before Photo Captured — Continue", "कार्य-पूर्व फोटो ली गई — जारी रखें"),
    "worker.jobExec.step1Desc": ("Capture the work area before starting any repairs. This protects both you and the customer.", "कोई भी मरम्मत शुरू करने से पहले कार्य क्षेत्र की तस्वीर लें। यह आपकी और ग्राहक दोनों की सुरक्षा करता है।"),
    "worker.jobExec.step1Header": ("Step 1 of 4 — Before Photo", "चरण 1 / 4 — कार्य-पूर्व फोटो"),
    "worker.jobExec.step1ProceedBtn": ("Capture Before Photo to Proceed", "आगे बढ़ने के लिए कार्य-पूर्व फोटो लें"),
    "worker.jobExec.step2BeforeLabel": ("✓ Before", "✓ पहले"),
    "worker.jobExec.step2Desc": ("Before photo recorded. You're ready to begin the repair. Tap below to officially start.", "पहले की फोटो दर्ज हुई। आप मरम्मत शुरू करने के लिए तैयार हैं। आधिकारिक तौर पर शुरू करने के लिए नीचे टैप करें।"),
    "worker.jobExec.step2Header": ("Step 2 of 4 — Begin Work", "चरण 2 / 4 — कार्य प्रारंभ"),
    "worker.jobExec.step2NotesLabel": ("Work Notes & Parts Replaced (optional):", "कार्य नोट्स और बदले गए पुर्जे (वैकल्पिक):"),
    "worker.jobExec.step2NotesPlaceholder": ("e.g. Replaced faulty silicone seal on hot water inlet. Pressure checked.", "उदा. गर्म पानी के इनलेट पर दोषपूर्ण सिलिकॉन सील बदली गई। दबाव जांचा गया।"),
    "worker.jobExec.step2StartBtn": ("Start Work Now", "अब काम शुरू करें"),
    "worker.jobExec.step3AfterLabel": ("After ✓", "बाद में ✓"),
    "worker.jobExec.step3AfterPlaceholder": ("After", "बाद में"),
    "worker.jobExec.step3BeforeLabel": ("Before", "पहले"),
    "worker.jobExec.step3ContinueBtn": ("After Photo Captured — Continue", "कार्य-उपरांत फोटो ली गई — जारी रखें"),
    "worker.jobExec.step3Desc": ("Capture the completed repair. This serves as proof of work quality for verification.", "पूर्ण मरम्मत की तस्वीर लें। यह सत्यापन के लिए कार्य गुणवत्ता के प्रमाण के रूप में कार्य करता है।"),
    "worker.jobExec.step3Header": ("Step 3 of 4 — After Photo", "चरण 3 / 4 — कार्य-उपरांत फोटो"),
    "worker.jobExec.step3ProceedBtn": ("Capture After Photo to Proceed", "आगे बढ़ने के लिए कार्य-उपरांत फोटो लें"),
    "worker.jobExec.step4AfterLabel": ("After ✓", "बाद में ✓"),
    "worker.jobExec.step4BeforeLabel": ("Before", "पहले"),
    "worker.jobExec.step4Desc": ("Both photos captured. Review and submit the job. It will enter the manager verification queue.", "दोनों तस्वीरें ले ली गईं। कार्य की समीक्षा करें और सबमिट करें। यह प्रबंधक सत्यापन कतार में जाएगा।"),
    "worker.jobExec.step4Header": ("Step 4 of 4 — Mark as Completed", "चरण 4 / 4 — पूर्ण चिह्नित करें"),
    "worker.jobExec.step4NotesLabel": ("Notes:", "टिप्पणियाँ:"),
    "worker.jobExec.step4Notice": ("Job will enter the manager verification queue. Customer will be notified.", "कार्य प्रबंधक सत्यापन कतार में प्रवेश करेगा। ग्राहक को सूचित किया जाएगा।"),
    "worker.jobExec.step4SubmitBtn": ("Submit Quality Proof", "गुणवत्ता प्रमाण सबमिट करें"),
    "worker.jobExec.submitQualityProof": ("Submit Quality Proof", "गुणवत्ता प्रमाण सबमिट करें"),
    "worker.jobExec.takeABreak": ("Take a Break", "ब्रेक लें"),
    "worker.jobExec.takeAfterPhoto": ("Upload After Photo", "कार्य के बाद की फोटो अपलोड करें"),
    "worker.jobExec.takeBeforePhoto": ("Upload Before Photo", "कार्य से पहले की फोटो अपलोड करें"),
    "worker.jobExec.tapToCaptureAfter": ("Tap to capture or upload after photo", "बाद की फोटो लेने या अपलोड करने के लिए टैप करें"),
    "worker.jobExec.tapToCaptureBefore": ("Tap to capture or upload before photo", "पहले की फोटो लेने या अपलोड करने के लिए टैप करें"),
    "worker.jobExec.totalJobPrice": ("Total Customer Charge", "कुल ग्राहक शुल्क"),
    "worker.jobExec.uploadAfter": ("Upload After", "बाद की अपलोड करें"),
    "worker.jobExec.uploadBefore": ("Upload Before", "पहले की अपलोड करें"),
    "worker.jobExec.verifyBeginWork": ("Verify & Begin Work", "सत्यापित करें एवं कार्य प्रारंभ करें"),
    "worker.jobExec.verifyOtpBtn": ("Verify OTP & Start", "ओटीपी सत्यापित करें और शुरू करें"),
    "worker.jobExec.viewCustomerProfile": ("View Customer Profile", "ग्राहक प्रोफ़ाइल देखें"),
    "worker.jobExec.workUnderway": ("Work Underway (OTP Verified)", "कार्य प्रगति पर (ओटीपी सत्यापित)"),
    "worker.jobExec.workerPayout": ("Worker Payout:", "कार्यकर्ता भुगतान:"),
    "worker.jobExec.workerShare": ("Your Payout (70%)", "आपका भुगतान (70%)"),

    # worker.jobs.*
    "worker.jobs.accept": ("Accept", "स्वीकार करें"),
    "worker.jobs.acceptJob": ("Accept Job", "कार्य स्वीकार करें"),
    "worker.jobs.active": ("Active", "सक्रिय"),
    "worker.jobs.after": ("After ✓", "बाद में ✓"),
    "worker.jobs.all": ("All Jobs", "सभी कार्य"),
    "worker.jobs.arrivalConfirmed": ("Arrival Confirmed!", "आगमन की पुष्टि हुई!"),
    "worker.jobs.arrivalConfirmedMsg": ("OTP verified. You may start the job.", "ओटीपी सत्यापित। आप कार्य शुरू कर सकते हैं।"),
    "worker.jobs.arrivalRuleDesc": ("Must request 4-digit resident OTP upon arrival", "आगमन पर निवासी से 4-अंकीय ओटीपी मांगना अनिवार्य"),
    "worker.jobs.arrivalRuleLabel": ("Arrival Rule:", "आगमन नियम:"),
    "worker.jobs.arrivedOnSite": ("Arrived on Site", "कार्यस्थल पर पहुंचे"),
    "worker.jobs.askOtpMsg": ("Ask resident for their 4-digit OTP.", "निवासी से उनका 4-अंकीय ओटीपी मांगें।"),
    "worker.jobs.assignedJobLabel": ("Assigned Job:", "आवंटित कार्य:"),
    "worker.jobs.assignmentDetails": ("Assignment Details", "आवंटन विवरण"),
    "worker.jobs.autoReminder": ("Auto-reminder 1 hr before", "1 घंटे पहले स्वचालित अनुस्मारक"),
    "worker.jobs.awaitingVerification": ("Awaiting Manager Verification", "प्रबंधक सत्यापन की प्रतीक्षा"),
    "worker.jobs.before": ("Before", "पहले"),
    "worker.jobs.callCustomer": ("Call Customer", "ग्राहक को कॉल करें"),
    "worker.jobs.cancellationInfo": ("Cancellation Info:", "रद्दीकरण जानकारी:"),
    "worker.jobs.cancellationNote": ("Cancellation Note:", "रद्दीकरण टिप्पणी:"),
    "worker.jobs.cancelled": ("Cancelled", "रद्द"),
    "worker.jobs.cancelledBy": ("Cancelled by {{name}}:", "{{name}} द्वारा रद्द:"),
    "worker.jobs.cancelledLabel": ("Cancelled", "रद्द"),
    "worker.jobs.client": ("Customer:", "ग्राहक:"),
    "worker.jobs.completed": ("Completed", "पूर्ण"),
    "worker.jobs.completedDate": ("Completed:", "पूर्ण हुआ:"),
    "worker.jobs.completedLabel": ("Completed:", "पूर्ण हुआ:"),
    "worker.jobs.contactResident": ("Contact", "संपर्क"),
    "worker.jobs.customerLabel": ("Customer:", "ग्राहक:"),
    "worker.jobs.date": ("Date:", "दिनांक:"),
    "worker.jobs.decline": ("Decline", "अस्वीकार करें"),
    "worker.jobs.details": ("Details", "विवरण"),
    "worker.jobs.empty": ("No jobs in this category yet.", "इस श्रेणी में अभी तक कोई कार्य नहीं।"),
    "worker.jobs.emptyDesc": ("New requests from your assigned cooperative society will appear here automatically.", "आपकी आवंटित सहकारी सोसाइटी से नए अनुरोध स्वचालित रूप से यहां दिखाई देंगे।"),
    "worker.jobs.emergency": ("Emergency", "आपातकालीन"),
    "worker.jobs.estEarnings": ("Est. Earnings", "अनुमानित कमाई"),
    "worker.jobs.executionWizard": ("Execution Wizard", "निष्पादन विज़ार्ड"),
    "worker.jobs.filterAll": ("All", "सभी"),
    "worker.jobs.filterBy": ("Filter By:", "फ़िल्टर करें:"),
    "worker.jobs.filterCancelled": ("Cancelled", "रद्द"),
    "worker.jobs.filterCompleted": ("Completed", "पूर्ण"),
    "worker.jobs.filterFinished": ("Finished", "समाप्त"),
    "worker.jobs.filterPending": ("Pending", "लंबित"),
    "worker.jobs.filterRevisited": ("Revisited", "पुनः देखा गया"),
    "worker.jobs.filterToday": ("Today", "आज"),
    "worker.jobs.guaranteedNet": ("70% Guaranteed Member Net", "70% गारंटीकृत सदस्य शुद्ध हिस्सा"),
    "worker.jobs.iHaveArrived": ("I Have Arrived", "मैं पहुंच गया हूं"),
    "worker.jobs.inExecution": ("In Execution", "निष्पादन में"),
    "worker.jobs.jobCardId": ("Job #{{id}}", "कार्य #{{id}}"),
    "worker.jobs.jobClosed": ("Job Closed", "कार्य बंद"),
    "worker.jobs.jobCompleted": ("Job Completed", "कार्य पूर्ण हुआ"),
    "worker.jobs.jobCompletedMsg": ("Job closed. Customer billed and rating requested.", "कार्य बंद। ग्राहक को बिल भेजा गया और रेटिंग मांगी गई।"),
    "worker.jobs.jobHistory": ("Job History & Completed Services", "कार्य इतिहास एवं पूर्ण सेवाएं"),
    "worker.jobs.jobMarkedComplete": ("Job Marked Complete!", "कार्य पूर्ण चिह्नित किया गया!"),
    "worker.jobs.jobMarkedCompleteMsg": ("Job closed. Earnings credited to your ledger.", "कार्य बंद। कमाई आपके लेजर में जमा की गई।"),
    "worker.jobs.jobVerification": ("Job Verification", "कार्य सत्यापन"),
    "worker.jobs.location": ("Location:", "स्थान:"),
    "worker.jobs.markComplete": ("Mark Complete", "पूर्ण चिह्नित करें"),
    "worker.jobs.navigate": ("Navigate", "नेविगेट"),
    "worker.jobs.noActiveJobs": ("No active jobs right now", "अभी कोई सक्रिय कार्य नहीं"),
    "worker.jobs.noActiveJobsDesc": ("Turn on Available mode to receive dispatch calls.", "प्रेषण कॉल प्राप्त करने के लिए उपलब्ध मोड चालू करें।"),
    "worker.jobs.noCancelled": ("No cancelled jobs", "कोई रद्द कार्य नहीं"),
    "worker.jobs.noCancelledDesc": ("Any cancelled or rescheduled appointments will be listed here.", "कोई भी रद्द या पुनर्निर्धारित अपॉइंटमेंट यहां सूचीबद्ध होंगे।"),
    "worker.jobs.noCancelledSub": ("Cancelled jobs will appear here.", "रद्द किए गए कार्य यहां दिखाई देंगे।"),
    "worker.jobs.noCancelledTitle": ("No cancelled jobs", "कोई रद्द कार्य नहीं"),
    "worker.jobs.noCompleted": ("No completed jobs yet", "अभी तक कोई पूर्ण कार्य नहीं"),
    "worker.jobs.noCompletedDesc": ("Finished assignments and customer ratings will be archived here.", "पूर्ण कार्य और ग्राहक रेटिंग यहां संग्रहीत होंगे।"),
    "worker.jobs.noCompletedSub": ("Completed jobs will appear here.", "पूर्ण कार्य यहां दिखाई देंगे।"),
    "worker.jobs.noCompletedTitle": ("No completed jobs yet", "अभी तक कोई पूर्ण कार्य नहीं"),
    "worker.jobs.noHistorySub": ("Jobs that are finished, revisited, or cancelled will appear here.", "समाप्त, पुनः देखे गए, या रद्द कार्य यहां दिखाई देंगे।"),
    "worker.jobs.noHistoryTitle": ("No matching history records", "कोई मिलान इतिहास रिकॉर्ड नहीं"),
    "worker.jobs.noInProgressSub": ("Jobs will appear here once you start travel or work.", "यात्रा या कार्य शुरू करने पर कार्य यहां दिखाई देंगे।"),
    "worker.jobs.noInProgressTitle": ("No active jobs in progress", "प्रगति पर कोई सक्रिय कार्य नहीं"),
    "worker.jobs.noUpcoming": ("No upcoming jobs scheduled", "कोई आगामी कार्य निर्धारित नहीं"),
    "worker.jobs.noUpcomingDesc": ("New accepted assignments from societies will appear here.", "सोसायटियों से नए स्वीकृत कार्य यहां दिखाई देंगे।"),
    "worker.jobs.noUpcomingSub": ("New accepted or assigned jobs for your trade will appear here.", "आपके व्यापार के लिए नए स्वीकृत या आवंटित कार्य यहां दिखाई देंगे।"),
    "worker.jobs.noUpcomingTitle": ("No upcoming jobs", "कोई आगामी कार्य नहीं"),
    "worker.jobs.openJobSheet": ("Open Job Sheet", "जॉब शीट खोलें"),
    "worker.jobs.otpErrorInvalid": ("Invalid OTP code. Ask customer for flat OTP.", "अमान्य ओटीपी कोड। ग्राहक से फ्लैट ओटीपी मांगें।"),
    "worker.jobs.otpErrorRequired": ("Please enter the 4-digit arrival OTP", "कृपया 4-अंकीय आगमन ओटीपी दर्ज करें"),
    "worker.jobs.otpInvalid": ("Invalid OTP code. Ask customer for 4-digit OTP.", "अमान्य ओटीपी कोड। ग्राहक से 4-अंकीय ओटीपी मांगें।"),
    "worker.jobs.otpPlaceholder": ("4-digit OTP", "4-अंकीय ओटीपी"),
    "worker.jobs.otpRequired": ("Please enter the 4-digit arrival OTP", "कृपया 4-अंकीय आगमन ओटीपी दर्ज करें"),
    "worker.jobs.paidBadge": ("Paid ✓", "भुगतान पूर्ण ✓"),
    "worker.jobs.paymentPending": ("Payment pending · ₹{{amount}}", "भुगतान लंबित · ₹{{amount}}"),
    "worker.jobs.paymentReceived": ("Payment Received", "भुगतान प्राप्त हुआ"),
    "worker.jobs.payout": ("Payout:", "भुगतान:"),
    "worker.jobs.pendingBadge": ("Pending", "लंबित"),
    "worker.jobs.photoProof": ("Photo Proof:", "फोटो प्रमाण:"),
    "worker.jobs.price": ("Price:", "मूल्य:"),
    "worker.jobs.priority": ("Priority:", "प्राथमिकता:"),
    "worker.jobs.rateReview": ("Review", "समीक्षा"),
    "worker.jobs.reasonLabel": ("Reason:", "कारण:"),
    "worker.jobs.recently": ("Recently", "हाल ही में"),
    "worker.jobs.refPrefix": ("Reference #", "संदर्भ #"),
    "worker.jobs.revisitBadge": ("Revisit", "पुनः यात्रा"),
    "worker.jobs.revisitDetails": ("Revisit Details:", "पुनः यात्रा विवरण:"),
    "worker.jobs.scheduledDate": ("Scheduled Date:", "निर्धारित दिनांक:"),
    "worker.jobs.scheduledToday": ("Scheduled Today", "आज निर्धारित"),
    "worker.jobs.searchPlaceholder": ("Search by job ID, resident name, building or trade...", "कार्य आईडी, निवासी नाम, इमारत या ट्रेड द्वारा खोजें..."),
    "worker.jobs.seeDetails": ("View Details", "विवरण देखें"),
    "worker.jobs.settledBadge": ("✓ Settled", "✓ निपटान पूर्ण"),
    "worker.jobs.settlementShareLabel": ("Settlement Share:", "निपटान हिस्सा:"),
    "worker.jobs.society": ("Society:", "सोसाइटी:"),
    "worker.jobs.sos": ("SOS", "एसओएस"),
    "worker.jobs.standardAssignment": ("Standard Trade Assignment", "मानक ट्रेड कार्य"),
    "worker.jobs.startJob": ("Start Job", "कार्य शुरू करें"),
    "worker.jobs.startTravel": ("Start Travel", "यात्रा शुरू करें"),
    "worker.jobs.status": ("Status:", "स्थिति:"),
    "worker.jobs.subtitle": ("Manage your active dispatches, view history, and coordinate door-to-door repairs.", "अपने सक्रिय प्रेषण प्रबंधित करें, इतिहास देखें और घर-घर मरम्मत का समन्वय करें।"),
    "worker.jobs.tabCancelled": ("Cancelled", "रद्द"),
    "worker.jobs.tabCompleted": ("Completed", "पूर्ण"),
    "worker.jobs.tabHistory": ("Job History & Filter", "कार्य इतिहास एवं फ़िल्टर"),
    "worker.jobs.tabInProgress": ("In Progress", "प्रगति पर"),
    "worker.jobs.tabUpcoming": ("Upcoming", "आगामी"),
    "worker.jobs.time": ("Scheduled Time:", "निर्धारित समय:"),
    "worker.jobs.title": ("My Jobs & Bookings", "मेरे कार्य एवं बुकिंग"),
    "worker.jobs.today": ("Today", "आज"),
    "worker.jobs.totalJobsCount": ("{{count}} Jobs Total", "कुल {{count}} कार्य"),
    "worker.jobs.trackRoute": ("Track Route", "मार्ग ट्रैक करें"),
    "worker.jobs.travelStarted": ("Travel Started", "यात्रा शुरू हुई"),
    "worker.jobs.travelStartedMsg": ("Customer notified of your departure.", "ग्राहक को आपकी रवानगी की सूचना दी गई।"),
    "worker.jobs.updated": ("Updated:", "अपडेट हुआ:"),
    "worker.jobs.verificationProofSaved": ("Verification Proof Saved", "सत्यापन प्रमाण सहेजा गया"),
    "worker.jobs.verificationProofSavedMsg": ("Quality check saved. Society manager notified.", "गुणवत्ता जांच सहेजी गई। सोसाइटी प्रबंधक को सूचित किया गया।"),
    "worker.jobs.verifyAndStart": ("Verify & Start", "सत्यापित करें और शुरू करें"),
    "worker.jobs.verifyStart": ("Verify & Start", "सत्यापित करें और शुरू करें"),
    "worker.jobs.viewDetails": ("View Details", "विवरण देखें"),
    "worker.jobs.viewEvidence": ("View Evidence", "साक्ष्य देखें"),
    "worker.jobs.viewInvoice": ("View Invoice", "चालान देखें"),
    "worker.jobs.viewReceipt": ("View Receipt", "रसीद देखें"),
    "worker.jobs.waitingOtp": ("Awaiting Customer OTP", "ग्राहक ओटीपी की प्रतीक्षा"),
    "worker.jobs.workerCut": ("70% Worker Cut", "70% कार्यकर्ता हिस्सा"),
    "worker.jobs.workerDesk": ("Worker Desk", "कार्यकर्ता डेस्क"),
    "worker.jobs.workerShare": ("Worker Share", "कार्यकर्ता हिस्सा"),
}

# Verify against raw_data for part1
missing = set(part1_keys) - set(translations.keys())
print(f"Total part1 keys needed: {len(part1_keys)}, translated: {len(translations)}")
if missing:
    print("Still missing keys in part1:", missing)
    raise SystemExit(1)

with open('scripts/locales_data/worker_part1.py', 'w', encoding='utf-8') as f:
    f.write("# Worker Part 1: Dashboard, Jobs, JobExec, Break, Notifications, Status, Skills\n\n")
    f.write("DATA = {\n")
    for k in sorted(translations.keys()):
        en_val, hi_val = translations[k]
        f.write(f"    {repr(k)}: ({repr(en_val)}, {repr(hi_val)}),\n")
    f.write("}\n")

print("Successfully generated scripts/locales_data/worker_part1.py with 100% coverage!")
