# Generate scripts/locales_data/admin_support.py
import json

raw_data = json.load(open('scripts/locales_data/admin_support_raw.json'))

# Manual translation mapping for all admin_support keys
translations = {
    # Admin / Verification / Map
    "admin.approveDoc": ("Approve Document", "दस्तावेज़ स्वीकृत करें"),
    "admin.approvedBadge": ("✓ Approved", "✓ स्वीकृत"),
    "admin.attachedRecord": ("Attached Record:", "संलग्न रिकॉर्ड:"),
    "admin.callWorker": ("Call Worker", "कार्यकर्ता को कॉल करें"),
    "admin.currentSector": ("Current Sector:", "वर्तमान सेक्टर:"),
    "admin.docCategory": ("Document Category:", "दस्तावेज़ श्रेणी:"),
    "admin.documentReview": ("Verification Document Review", "सत्यापन दस्तावेज़ समीक्षा"),
    "admin.encryptedStorage": ("Encrypted local custody storage", "एन्क्रिप्टेड स्थानीय कस्टडी स्टोरेज"),
    "admin.federationRegistry": ("Maharashtra Cooperative Federation Registry", "महाराष्ट्र सहकारी महासंघ रजिस्ट्री"),
    "admin.gpsTelemetry": ("GPS Telemetry:", "जीपीएस टेलीमेट्री:"),
    "admin.jobsCompleted": ("jobs completed", "कार्य पूर्ण किए"),
    "admin.justNow": ("Just now", "अभी-अभी"),
    "admin.lastPing": ("Last Ping:", "अंतिम पिंग:"),
    "admin.mapAvailable": ("Available", "उपलब्ध"),
    "admin.mapFilterAll": ("All (${workers.length})", "सभी (${workers.length})"),
    "admin.mapOffline": ("Offline", "ऑफलाइन"),
    "admin.mapOnJob": ("On Job", "कार्यरत"),
    "admin.mapTravelling": ("Travelling", "यात्रा में"),
    "admin.needsCorrectionBadge": ("Needs Correction", "सुधार आवश्यक"),
    "admin.officialRecord": ("Official Verification Record", "आधिकारिक सत्यापन रिकॉर्ड"),
    "admin.pendingReviewBadge": ("Pending Review", "समीक्षा लंबित"),
    "admin.priorReviewNote": ("Prior Review Note:", "पूर्व समीक्षा टिप्पणी:"),
    "admin.rejectDoc": ("Reject", "अस्वीकार करें"),
    "admin.rejectedBadge": ("✗ Rejected", "✗ अस्वीकृत"),
    "admin.remarksPlaceholder": ("Add note for worker (e.g. 'Clear copy verified', 'Address matches society ward', etc.)", "कार्यकर्ता के लिए टिप्पणी जोड़ें (उदा. 'स्पष्ट प्रति सत्यापित', 'पता सोसाइटी वार्ड से मेल खाता है', आदि)"),
    "admin.requestCorrection": ("Request Correction", "सुधार का अनुरोध करें"),
    "admin.reviewerRemarks": ("Reviewer Remarks / Feedback (Optional)", "समीक्षक टिप्पणी / प्रतिपुष्टि (वैकल्पिक)"),
    "admin.societyStation": ("Society Station:", "सोसाइटी स्टेशन:"),
    "admin.tamperEvident": ("Tamper-evident verification", "छेड़छाड़-रोधी सत्यापन"),
    "admin.tapWorkerMarker": ("Tap any worker marker on the map to inspect location telemetry.", "स्थान टेलीमेट्री देखने के लिए मानचित्र पर किसी भी कार्यकर्ता मार्कर पर टैप करें।"),
    "admin.verification": ("Verification:", "सत्यापन:"),
    "admin.verification.aadhaarNumber": ("Aadhaar Number", "आधार संख्या"),
    "admin.verification.addressProvided": ("Address provided during onboarding", "ऑनबोर्डिंग के दौरान प्रदान किया गया पता"),
    "admin.verification.approvedBadge": ("✓ Approved", "✓ स्वीकृत"),
    "admin.verification.areaLabel": ("Area:", "क्षेत्र:"),
    "admin.verification.certificateLabel": ("Certificate:", "प्रमाणपत्र:"),
    "admin.verification.checkIdentityPrompt": ("Check identity and Aadhaar details to verify worker's personal record.", "कार्यकर्ता के व्यक्तिगत रिकॉर्ड को सत्यापित करने के लिए पहचान और आधार विवरण की जांच करें।"),
    "admin.verification.dobOnRecord": ("DOB on record", "रिकॉर्ड में जन्म तिथि"),
    "admin.verification.docUpdatedMsg": ("Updated verification for {{name}}.", "{{name}} के लिए सत्यापन अपडेट किया गया।"),
    "admin.verification.docUpdatedTitle": ("Document {{status}}", "दस्तावेज़ {{status}}"),
    "admin.verification.eligibleDesc": ("Personal KYC is verified and at least 1 trade skill is verified.", "व्यक्तिगत केवाईसी सत्यापित है और कम से कम 1 व्यावसायिक कौशल सत्यापित है।"),
    "admin.verification.eligibleMatching": ("Eligible for Customer Job Matching", "ग्राहक कार्य मिलान के लिए पात्र"),
    "admin.verification.emergencyContact": ("Emergency Contact", "आपातकालीन संपर्क"),
    "admin.verification.experienceLabel": ("Experience:", "अनुभव:"),
    "admin.verification.familyMember": ("Family Member", "परिवार का सदस्य"),
    "admin.verification.genderDob": ("Gender & DOB", "लिंग और जन्म तिथि"),
    "admin.verification.level1Title": ("Level 1: Personal KYC Details", "स्तर 1: व्यक्तिगत केवाईसी विवरण"),
    "admin.verification.level2Subtitle": ("Workers can have multiple trade skills. Each skill is verified individually.", "कार्यकर्ताओं के पास कई व्यावसायिक कौशल हो सकते हैं। प्रत्येक कौशल को व्यक्तिगत रूप से सत्यापित किया जाता है।"),
    "admin.verification.level2Title": ("Level 2: Skill Information Records", "स्तर 2: कौशल सूचना रिकॉर्ड"),
    "admin.verification.needsCorrection": ("Needs Correction", "सुधार आवश्यक"),
    "admin.verification.noStructuredSkills": ("No structured skill entries added yet for {{name}}.", "{{name}} के लिए अभी तक कोई संरचित कौशल प्रविष्टि नहीं जोड़ी गई है।"),
    "admin.verification.notEligibleDesc": ("Requires Personal KYC verified + at least 1 trade skill verified by Society Manager.", "सोसाइटी प्रबंधक द्वारा व्यक्तिगत केवाईसी सत्यापित + कम से कम 1 व्यावसायिक कौशल सत्यापित आवश्यक है।"),
    "admin.verification.notSpecified": ("Not specified", "निर्दिष्ट नहीं"),
    "admin.verification.notYetVisible": ("Not Yet Visible to Customers", "अभी तक ग्राहकों के लिए दृश्यमान नहीं"),
    "admin.verification.pendingCheck": ("Pending Check", "जांच लंबित"),
    "admin.verification.pendingManager": ("Pending Manager Verification", "प्रबंधक सत्यापन लंबित"),
    "admin.verification.pendingManagerReview": ("Pending Manager Review", "प्रबंधक समीक्षा लंबित"),
    "admin.verification.pendingReview": ("Pending Review", "समीक्षा लंबित"),
    "admin.verification.personalKycLabel": ("Personal KYC:", "व्यक्तिगत केवाईसी:"),
    "admin.verification.personalKycVerifiedBadge": ("✓ Personal KYC Verified", "✓ व्यक्तिगत केवाईसी सत्यापित"),
    "admin.verification.phoneEmail": ("Phone & Email", "फ़ोन और ईमेल"),
    "admin.verification.pinCode": ("PIN Code:", "पिन कोड:"),
    "admin.verification.resAddressPin": ("Residential Address & PIN", "आवासीय पता और पिन"),
    "admin.verification.verifiedActive": ("Verified & Active", "सत्यापित एवं सक्रिय"),
    "admin.verification.verifiedBadge": ("✓ Verified", "✓ सत्यापित"),
    "admin.verification.verifiedOnFile": ("Verified on File", "फ़ाइल पर सत्यापित"),
    "admin.verification.verifiedSkillsLabel": ("Verified Skills:", "सत्यापित कौशल:"),
    "admin.verification.verifyPersonalKyc": ("Verify Personal KYC", "व्यक्तिगत केवाईसी सत्यापित करें"),
    "admin.verification.verifySkill": ("Verify Skill", "कौशल सत्यापित करें"),
    "admin.verification.viewAadhaarDoc": ("View Aadhaar Document", "आधार दस्तावेज़ देखें"),
    "admin.verification.viewFile": ("View File", "फ़ाइल देखें"),
    "admin.verificationChecksum": ("Verification Checksum:", "सत्यापन चेकसम:"),
    "admin.viewFullProfile": ("View Full Profile & KYC", "पूर्ण प्रोफ़ाइल और केवाईसी देखें"),
    "admin.workerMapSubtitle": ("Operational visibility for stationed specialists. Private to Society Desk.", "तैनात विशेषज्ञों के लिए परिचालन दृश्यता। केवल सोसाइटी डेस्क हेतु।"),
    "admin.workerMapTitle": ("Where are my workers? — ${societyName} Live Map", "मेरे कार्यकर्ता कहाँ हैं? — ${societyName} लाइव मैप"),
    "admin.workerTelemetry": ("Worker Telemetry", "कार्यकर्ता टेलीमेट्री"),

    # Card Content
    "cardContent.powerSocketIssue": ("Power Socket Issue", "पावर सॉकेट समस्या"),
    "cardContent.todayScheduled": ("Today · Scheduled", "आज · निर्धारित"),

    # Category & Priority
    "category.": ("Category", "श्रेणी"),
    "category.electrical": ("Electrical", "इलेक्ट्रिकल"),
    "category.plumbing": ("Plumbing", "प्लंबिंग"),
    "category.carpentry": ("Carpentry", "बढ़ईगीरी"),
    "category.painting": ("Painting", "पेंटिंग"),
    "category.cleaning": ("Cleaning", "सफाई"),
    "category.appliance_repairs": ("Appliance Repairs", "उपकरण मरम्मत"),
    "category.hvac___ac_service": ("HVAC & AC Service", "एचवीएसी एवं एसी सेवा"),
    "category.masonry": ("Masonry", "चिनाई"),
    "category.pest_control": ("Pest Control", "कीट नियंत्रण"),
    "category.gardening": ("Gardening", "बागवानी"),
    "category.gardening___greenery": ("Gardening & Greenery", "बागवानी एवं हरियाली"),
    "category.security___cctv": ("Security & CCTV", "सुरक्षा एवं सीसीटीवी"),
    "priority.": ("Priority", "प्राथमिकता"),
    "priority.low": ("Low", "कम"),
    "priority.medium": ("Medium", "मध्यम"),
    "priority.high": ("High", "उच्च"),
    "priority.emergency": ("Emergency", "आपातकालीन"),
    "priority.urgent": ("Urgent", "अति आवश्यक"),

    # Community
    "community.channels": ("Community Channels", "सामुदायिक चैनल"),
    "community.coopVerified": ("Cooperative Verified", "सहकारी सत्यापित"),
    "community.createGroupRequest": ("Create Group Request", "सामूहिक अनुरोध बनाएं"),
    "community.customerCommunityBadge": ("Your Community", "आपका समुदाय"),
    "community.descGoal": ("Description / Goal", "विवरण / लक्ष्य"),
    "community.descGoalPlaceholder": ("e.g. Society-wide AC deep cleaning & filter wash before summer", "उदा. गर्मियों से पहले सोसाइटी-व्यापी एसी डीप क्लीनिंग और फ़िल्टर धुलाई"),
    "community.discussions": ("Community Discussions", "सामुदायिक चर्चाएं"),
    "community.groupDiscountTarget": ("Group Discount Target:", "सामूहिक छूट लक्ष्य:"),
    "community.guildChannels": ("Trade Guild Channels", "व्यापार गिल्ड चैनल"),
    "community.homesJoined": ("Homes Joined", "जुड़े हुए घर"),
    "community.howGroupBookingsWork": ("How Cooperative Group Bookings Work", "सहकारी सामूहिक बुकिंग कैसे काम करती है"),
    "community.howGroupBookingsWorkDesc": ("When multiple households in the same society book identical services together on the same scheduled day, cooperative workers optimize travel time. You unlock direct 20% discounts while specialists earn uninterrupted bulk wages.", "जब एक ही सोसाइटी के कई परिवार एक ही निर्धारित दिन पर एक साथ समान सेवाएं बुक करते हैं, तो सहकारी कार्यकर्ता यात्रा के समय को अनुकूलित करते हैं। आपको सीधे 20% की छूट मिलती है जबकि विशेषज्ञ निर्बाध थोक कमाई करते हैं।"),
    "community.hubSubtitle": ("Society maintenance updates, neighbor discussions, and collective group bookings with 20% savings.", "सोसाइटी रखरखाव अपडेट, पड़ोसियों के साथ चर्चा, और 20% बचत के साथ सामूहिक बुकिंग।"),
    "community.hubTitle": ("Your Community Hub", "आपका सामुदायिक केंद्र"),
    "community.joinedBatch": ("Joined Batch", "शामिल बैच"),
    "community.myGuilds": ("My Professional Guilds", "मेरे व्यावसायिक गिल्ड"),
    "community.neighborsBooking": ("Your neighbors are booking", "आपके पड़ोसी बुक कर रहे हैं"),
    "community.noMessages": ("No messages yet in #{{name}}.", "#{{name}} में अभी तक कोई संदेश नहीं।"),
    "community.officialNotice": ("Official Notice", "आधिकारिक सूचना"),
    "community.participatingHouseholds": ("Participating Households:", "भाग लेने वाले परिवार:"),
    "community.postUpdatePlaceholder": ("Post update to #{{name}}...", "#{{name}} में अपडेट पोस्ट करें..."),
    "community.startConversation": ("Start the conversation with your community below.", "नीचे अपने समुदाय के साथ बातचीत शुरू करें।"),
    "community.workerCommunityBadge": ("My Professional Community", "मेरा व्यावसायिक समुदाय"),
    "community.workerHubSubtitle": ("Connect with certified trade peers, share tool tips, coordinate emergency aid, and discuss technical standards.", "प्रमाणित सहकर्मियों से जुड़ें, टूल टिप्स साझा करें, आपातकालीन सहायता समन्वय करें, और तकनीकी मानकों पर चर्चा करें।"),
    "community.workerHubTitle": ("Professional Trade Guilds", "व्यावसायिक ट्रेड गिल्ड"),

    # Location
    "location.bookmarkLocation": ("Bookmark this location", "इस स्थान को बुकमार्क करें"),
    "location.chooseSubtitle": ("Find stationed specialists and calculate exact arrival distance", "तैनात विशेषज्ञों को खोजें और सटीक आगमन दूरी की गणना करें"),
    "location.chooseTitle": ("Choose Service Location", "सेवा स्थान चुनें"),
    "location.confirmLocation": ("Confirm Service Location", "सेवा स्थान की पुष्टि करें"),
    "location.deliveringTo": ("Delivering to", "वितरण स्थान"),
    "location.detecting": ("Detecting...", "पहचान की जा रही है..."),
    "location.detectingGPS": ("Detecting GPS...", "जीपीएस का पता लगाया जा रहा है..."),
    "location.dragPinNotice": ("Drag pin to fine-tune doorstep location", "दरवाजे के सटीक स्थान के लिए पिन को खींचें"),
    "location.home": ("home", "घर"),
    "location.interactiveMapPin": ("Interactive Map Pin", "इंटरएक्टिव मैप पिन"),
    "location.other": ("other", "अन्य"),
    "location.permissionDenied": ("Location permission is disabled in your browser. You can select your address from the search bar or move the pin on the map.", "आपके ब्राउज़र में स्थान अनुमति अक्षम है। आप खोज बार से अपना पता चुन सकते हैं या मानचित्र पर पिन ले जा सकते हैं।"),
    "location.resolvedAddress": ("Resolved Doorstep Address", "सत्यापित पता"),
    "location.resolvingAddress": ("Resolving street & society details...", "सड़क और सोसाइटी विवरण हल किए जा रहे हैं..."),
    "location.satelliteFailed": ("Unable to acquire exact GPS satellite fix. Using approximate sector location.", "सटीक जीपीएस उपग्रह स्थान प्राप्त करने में असमर्थ। अनुमानित सेक्टर स्थान का उपयोग किया जा रहा है।"),
    "location.savePlaceholder": ("e.g., Home (Flat 402), Parents Flat...", "उदा., घर (फ़्लैट 402), माता-पिता का फ़्लैट..."),
    "location.savedPlaces": ("Saved Places", "सहेजे गए स्थान"),
    "location.searchPlaceholder": ("Search society, building, or area in Pune...", "पुणे में सोसाइटी, इमारत या क्षेत्र खोजें..."),
    "location.selectedLocation": ("Selected Location", "चयनित स्थान"),
    "location.serviceDeliveryLocation": ("Service Delivery Location", "सेवा वितरण स्थान"),
    "location.updatingAddress": ("Updating address...", "पता अपडेट किया जा रहा है..."),
    "location.useGPS": ("Use GPS", "जीपीएस का उपयोग करें"),
    "location.work": ("work", "कार्यस्थल"),

    # Map
    "map.active": ("Active", "सक्रिय"),
    "map.gpsPrecision": ("GPS Precision", "जीपीएस सटीकता"),
    "map.liveMap": ("Cooperative Live Map", "सहकारी लाइव मैप"),
    "map.locatePosition": ("Locate my position", "मेरी स्थिति का पता लगाएं"),
    "map.pinDropInstruction": ("Tap map or drag pin to choose exact service location", "सटीक सेवा स्थान चुनने के लिए मानचित्र पर टैप करें या पिन खींचें"),
    "map.specialist": ("Specialist", "विशेषज्ञ"),
    "map.stationedSpecialist": ("Stationed Specialist", "तैनात विशेषज्ञ"),
    "map.status": ("Status:", "स्थिति:"),
    "map.zoomIn": ("Zoom in", "ज़ूम इन"),
    "map.zoomOut": ("Zoom out", "ज़ूम आउट"),

    # Scenario
    "scenario.bookingId": ("Booking ID:", "बुकिंग आईडी:"),
    "scenario.modalSubtitle": ("Interactive Scripted Scenario · Step {{current}} of {{total}}", "इंटरएक्टिव परिदृश्य · चरण {{current}} / {{total}}"),
    "scenario.modalTitle": ("Section 44: End-to-End Demonstration Walkthrough", "धारा 44: संपूर्ण डेमो वॉकथ्रू"),
    "scenario.perspective": ("Perspective: ", "दृष्टिकोण: "),
    "scenario.step10Action": ("10. Report Quality Dispute", "10. गुणवत्ता विवाद दर्ज करें"),
    "scenario.step10Actor": ("Customer (Ananya)", "ग्राहक (अनन्या)"),
    "scenario.step10Desc": ("Customer rates service and reports minor seepage fitting issue: ", "ग्राहक सेवा को रेट करता है और मामूली रिसाव फिटिंग समस्या की रिपोर्ट करता है: "),
    "scenario.step10Title": ("Customer Rates & Flags Quality Dispute", "ग्राहक ने रेटिंग दी और गुणवत्ता विवाद दर्ज किया"),
    "scenario.step11Action": ("11. Society Manager Reassigns Revisit", "11. सोसाइटी प्रबंधक ने पुनः यात्रा सौंपी"),
    "scenario.step11Actor": ("Society Manager (Suresh Menon)", "सोसाइटी प्रबंधक (सुरेश मेनन)"),
    "scenario.step11Desc": ("Society Manager reviews customer claim in Quality Disputes desk and dispatches a complimentary senior revisit ticket.", "सोसाइटी प्रबंधक गुणवत्ता विवाद डेस्क में ग्राहक के दावे की समीक्षा करता है और मानार्थ वरिष्ठ पुनः यात्रा टिकट भेजता है।"),
    "scenario.step11Title": ("Admin Reviews Dispute & Assigns Revisit", "व्यवस्थापक विवाद की समीक्षा करता है और पुनः यात्रा सौंपता है"),
    "scenario.step12Action": ("12. Finalize Revisit & Complete Flow", "12. पुनः यात्रा पूरी करें और प्रक्रिया समाप्त करें"),
    "scenario.step12Actor": ("Cooperative Resolution", "सहकारी समाधान"),
    "scenario.step12Desc": ("Senior specialist completes the complimentary inspection and secures the fitting. Customer dispute is resolved successfully!", "वरिष्ठ विशेषज्ञ मानार्थ निरीक्षण पूरा करता है और फिटिंग को सुरक्षित करता है। ग्राहक विवाद सफलतापूर्वक हल हुआ!"),
    "scenario.step12Title": ("Revisit Completed & Dispute Resolved", "पुनः यात्रा पूर्ण और विवाद हल हुआ"),
    "scenario.step1Action": ("1. Dispatch Emergency Request", "1. आपातकालीन अनुरोध भेजें"),
    "scenario.step1Actor": ("Customer (Ananya)", "ग्राहक (अनन्या)"),
    "scenario.step1Desc": ("Customer triggers an immediate emergency plumbing request for severe pipe burst at Green Residency.", "ग्राहक ग्रीन रेजीडेंसी में गंभीर पाइप फटने के लिए तत्काल आपातकालीन प्लंबिंग अनुरोध भेजता है।"),
    "scenario.step1Title": ("Customer Requests Emergency Plumbing", "ग्राहक ने आपातकालीन प्लंबिंग का अनुरोध किया"),
    "scenario.step2Action": ("2. Inspect Matching & Alert Candidate 1", "2. मिलान का निरीक्षण करें और उम्मीदवार 1 को सूचित करें"),
    "scenario.step2Actor": ("AI Fair Allocation Engine", "एआई निष्पक्ष आवंटन इंजन"),
    "scenario.step2Desc": ("Algorithmic match engine evaluates certified local plumbers on skill compatibility, proximity, and current workload balance. Candidate 1 (Amit Kumar) is selected.", "एल्गोरिदमिक मैच इंजन कौशल संगतता, निकटता और वर्तमान कार्यभार संतुलन पर प्रमाणित स्थानीय प्लंबर का मूल्यांकन करता है। उम्मीदवार 1 (अमित कुमार) का चयन किया गया है।"),
    "scenario.step2Title": ("Request Enters Priority Queue & Matching", "अनुरोध प्राथमिकता कतार और मिलान में प्रवेश करता है"),
    "scenario.step3Action": ("3. Simulate Worker 1 Rejecting Job", "3. कार्यकर्ता 1 द्वारा कार्य अस्वीकार करने का अनुकरण"),
    "scenario.step3Actor": ("Worker 1 (Amit Kumar)", "कार्यकर्ता 1 (अमित कुमार)"),
    "scenario.step3Desc": ("Candidate 1 (Amit Kumar) is currently in another task and declines the job offer.", "उम्मीदवार 1 (अमित कुमार) वर्तमान में किसी अन्य कार्य में व्यस्त है और कार्य प्रस्ताव अस्वीकार करता है।"),
    "scenario.step3Title": ("Candidate Worker 1 Rejects the Job", "उम्मीदवार कार्यकर्ता 1 ने कार्य अस्वीकार किया"),
    "scenario.step4Action": ("4. Re-match with Candidate 2 (Rahul)", "4. उम्मीदवार 2 (राहुल) के साथ पुनः मिलान करें"),
    "scenario.step4Actor": ("System Re-matching Engine", "सिस्टम पुनः मिलान इंजन"),
    "scenario.step4Desc": ("The platform automatically re-scores remaining eligible candidates excluding Amit. Candidate 2 (Rahul Sharma, 96% match score) is immediately matched without customer restart.", "प्लेटफ़ॉर्म स्वचालित रूप से अमित को छोड़कर शेष पात्र उम्मीदवारों का पुनः स्कोर करता है। उम्मीदवार 2 (राहुल शर्मा, 96% मिलान स्कोर) तुरंत ग्राहक के दोबारा शुरू किए बिना मेल खा जाता है।"),
    "scenario.step4Title": ("System Triggers Automatic Fair Re-Matching", "सिस्टम स्वचालित निष्पक्ष पुनः मिलान ट्रिगर करता है"),
    "scenario.step5Action": ("5. Rahul Accepts Job", "5. राहुल कार्य स्वीकार करता है"),
    "scenario.step5Actor": ("Worker 2 (Rahul Sharma)", "कार्यकर्ता 2 (राहुल शर्मा)"),
    "scenario.step5Desc": ("Rahul Sharma reviews the emergency job details and accepts. The booking moves to CONFIRMED.", "राहुल शर्मा आपातकालीन कार्य विवरण की समीक्षा करता है और स्वीकार करता है। बुकिंग 'पुष्टि' हो जाती है।"),
    "scenario.step5Title": ("Worker 2 (Rahul) Accepts the Job", "कार्यकर्ता 2 (राहुल) कार्य स्वीकार करता है"),
    "scenario.step6Action": ("6. Travel & Confirm Arrival", "6. यात्रा और आगमन की पुष्टि करें"),
    "scenario.step6Actor": ("Worker (Rahul Sharma)", "कार्यकर्ता (राहुल शर्मा)"),
    "scenario.step6Desc": ("Rahul updates status to TRAVELLING (notifying resident) and subsequently marks ARRIVED at Green Residency.", "राहुल स्थिति को यात्रा में अपडेट करता है (निवासी को सूचित करते हुए) और बाद में ग्रीन रेजीडेंसी पर आगमन दर्ज करता है।"),
    "scenario.step6Title": ("Worker Travels & Arrives at Customer", "कार्यकर्ता यात्रा करता है और ग्राहक के पास पहुंचता है"),
    "scenario.step7Action": ("7. Verify OTP & Start Job", "7. ओटीपी सत्यापित करें और कार्य शुरू करें"),
    "scenario.step7Actor": ("Customer + Worker", "ग्राहक + कार्यकर्ता"),
    "scenario.step7Desc": ("Customer shares the secure 4-digit code ({{otp}}) with Rahul. OTP is verified and status advances to IN_PROGRESS.", "ग्राहक राहुल के साथ सुरक्षित 4-अंकीय कोड ({{otp}}) साझा करता है। ओटीपी सत्यापित होता है और स्थिति प्रगति पर आगे बढ़ती है।"),
    "scenario.step7Title": ("Customer OTP Verification & Job Starts", "ग्राहक ओटीपी सत्यापन और कार्य प्रारंभ"),
    "scenario.step8Action": ("8. Complete Job & Notes", "8. कार्य और टिप्पणियाँ पूरी करें"),
    "scenario.step8Actor": ("Worker (Rahul Sharma)", "कार्यकर्ता (राहुल शर्मा)"),
    "scenario.step8Desc": ("Rahul replaces the cracked inlet gasket, checks water pressure, attaches post-work photo, and marks job as COMPLETED.", "राहुल टूटे हुए इनलेट गास्केट को बदलता है, पानी के दबाव की जांच करता है, काम के बाद की तस्वीर संलग्न करता है, और काम को पूर्ण चिह्नित करता है।"),
    "scenario.step8Title": ("Worker Completes Repair Job", "कार्यकर्ता मरम्मत कार्य पूरा करता है"),
    "scenario.step9Action": ("9. Settle Payment", "9. भुगतान का निपटान करें"),
    "scenario.step9Actor": ("Customer Settlement", "ग्राहक निपटान"),
    "scenario.step9Desc": ("Customer settles ₹600: Worker receives ₹420 (70%), Green Residency society receives ₹30 (5%), and Cooperative Fund receives ₹150 (25%).", "ग्राहक ₹600 का निपटान करता है: कार्यकर्ता को ₹420 (70%), ग्रीन रेजीडेंसी सोसाइटी को ₹30 (5%), और सहकारी निधि को ₹150 (25%) प्राप्त होता है।"),
    "scenario.step9Title": ("Transparent Payment & Fund Credit", "पारदर्शी भुगतान और फंड क्रेडिट"),
    "scenario.stepBadge": ("STEP {{current}}/{{total}}", "चरण {{current}}/{{total}}"),
    "scenario.stepsOutline": ("Scenario Steps Outline:", "परिदृश्य चरण रूपरेखा:"),
    "scenario.whatHappens": ("What Happens at this Step:", "इस चरण में क्या होता है:"),

    # Support
    "support.activeBooking": ("Active Booking", "सक्रिय बुकिंग"),
    "support.addIssueSummaryOptional": ("Add Issue Summary for WhatsApp Desk (Optional)", "व्हाट्सएप डेस्क के लिए समस्या सारांश जोड़ें (वैकल्पिक)"),
    "support.attachedAlert": ("Booking #{{booking}} and Recent Txn #{{txn}} will be on the agent's screen when calling.", "कॉल करते समय एजेंट की स्क्रीन पर बुकिंग #{{booking}} और हालिया लेनदेन #{{txn}} उपलब्ध होंगे।"),
    "support.autoAttachedContext": ("Auto-Attached Account Context", "स्वतः संलग्न खाता संदर्भ"),
    "support.autoFormattedPreview": ("Auto-Formatted Message Preview:", "स्वतः स्वरूपित संदेश पूर्वावलोकन:"),
    "support.avgReplyTime": ("Avg reply under 2 mins", "औसत उत्तर 2 मिनट के भीतर"),
    "support.benefitManagerContact": ("✓ Direct contact with your Society Cooperative Manager", "✓ आपके सोसाइटी सहकारी प्रबंधक से सीधा संपर्क"),
    "support.benefitRefunds": ("✓ Authorized to approve direct refunds & rescheduling", "✓ प्रत्यक्ष रिफंड और पुनर्निर्धारण को स्वीकृत करने हेतु अधिकृत"),
    "support.briefNotesOptional": ("Brief Notes / What should we know? (Optional)", "संक्षिप्त नोट्स / हमें क्या जानना चाहिए? (वैकल्पिक)"),
    "support.callbackQueuedDetail": ("Officer {{officer}} will call you at {{phone}} during {{slot}}.", "अधिकारी {{officer}} आपको {{slot}} के दौरान {{phone}} पर कॉल करेंगे।"),
    "support.callbackQueuedTitle": ("Callback Successfully Queued!", "कॉलबैक सफलतापूर्वक कतारबद्ध किया गया!"),
    "support.callbackRequest": ("One-Tap Callback Request", "वन-टैप कॉलबैक अनुरोध"),
    "support.channelLabel": ("Channel:", "चैनल:"),
    "support.chooseTimeSlot": ("Choose Convenient Time Slot", "सुविधाजनक समय स्लॉट चुनें"),
    "support.confirmCallbackRequest": ("Confirm Callback Request", "कॉलबैक अनुरोध की पुष्टि करें"),
    "support.contextNotice": ("Your support agent automatically receives these verified IDs", "आपके सहायता एजेंट को स्वचालित रूप से ये सत्यापित आईडी प्राप्त होती हैं"),
    "support.directHumanSupport": ("Direct Human Support", "प्रत्यक्ष मानव सहायता"),
    "support.escrowProtected": ("Escrow Protected & Verified", "एस्क्रो संरक्षित और सत्यापित"),
    "support.issuesResolvedCount": ("1,400+ issues resolved", "1,400+ समस्याएं हल हुईं"),
    "support.launchWhatsApp": ("Launch WhatsApp Chat Now", "अब व्हाट्सएप चैट शुरू करें"),
    "support.liveInAppChat": ("Live In-App Chat", "लाइव इन-ऐप चैट"),
    "support.markResolved": ("Mark Resolved", "हल किया हुआ चिह्नित करें"),
    "support.memberVerification": ("Member Verification", "सदस्य सत्यापन"),
    "support.mySupportTickets": ("My Support Tickets ({{count}})", "मेरे सहायता टिकट ({{count}})"),
    "support.noTicketsRecorded": ("No tickets recorded yet.", "अभी तक कोई टिकट दर्ज नहीं किया गया।"),
    "support.notesPlaceholder": ("e.g. Need to adjust the technician arrival time and discuss pricing breakdown...", "उदा. तकनीशियन के आगमन समय को समायोजित करने और मूल्य विवरण पर चर्चा करने की आवश्यकता है..."),
    "support.officerOnDuty": ("Support Officer on Duty", "ड्यूटी पर सहायता अधिकारी"),
    "support.officersOnline": ("4 Human Officers Online", "4 मानव अधिकारी ऑनलाइन"),
    "support.phoneForCallback": ("Your Phone Number for Callback", "कॉलबैक के लिए आपका फ़ोन नंबर"),
    "support.promptAccount1": ("Update society / flat address", "सोसाइटी / फ़्लैट का पता अपडेट करें"),
    "support.promptAccount2": ("Cooperative membership card query", "सहकारी सदस्यता कार्ड संबंधी प्रश्न"),
    "support.promptAccount3": ("Change registered phone number", "पंजीकृत फ़ोन नंबर बदलें"),
    "support.promptAccount4": ("View my service history report", "मेरी सेवा इतिहास रिपोर्ट देखें"),
    "support.promptBooking1": ("Worker has not arrived yet", "कार्यकर्ता अभी तक नहीं आया है"),
    "support.promptBooking2": ("Need to reschedule my booking time", "मेरी बुकिंग का समय पुनर्निर्धारित करने की आवश्यकता है"),
    "support.promptBooking3": ("Want to add additional task to job", "कार्य में अतिरिक्त काम जोड़ना चाहते हैं"),
    "support.promptBooking4": ("Cancel this booking without penalty", "बिना किसी जुर्माने के यह बुकिंग रद्द करें"),
    "support.promptPayment1": ("Dispute charges on recent invoice", "हालिया इनवॉइस पर शुल्कों पर विवाद"),
    "support.promptPayment2": ("Payment deducted twice via UPI", "यूपीआई के माध्यम से भुगतान दो बार कट गया"),
    "support.promptPayment3": ("Need an official tax receipt", "आधिकारिक कर रसीद चाहिए"),
    "support.promptPayment4": ("Release escrow payout confirmation", "एस्क्रो भुगतान रिलीज की पुष्टि"),
    "support.promptSafety1": ("Urgent safety / emergency report", "अति आवश्यक सुरक्षा / आपातकालीन रिपोर्ट"),
    "support.promptSafety2": ("Property damage during service", "सेवा के दौरान संपत्ति का नुकसान"),
    "support.promptSafety3": ("Verify worker ID card & background", "कार्यकर्ता आईडी कार्ड और पृष्ठभूमि सत्यापित करें"),
    "support.promptSafety4": ("Request society manager inspection", "सोसाइटी प्रबंधक निरीक्षण का अनुरोध करें"),
    "support.quickStartersFor": ("Quick Starters for {{category}}", "{{category}} के लिए त्वरित शुरुआत"),
    "support.recentLedgerTxn": ("Recent Ledger Txn", "हालिया लेजर लेनदेन"),
    "support.refTicket": ("Reference Ticket: ", "संदर्भ टिकट: "),
    "support.replyToAgent": ("Reply to {{name}}...", "{{name}} को उत्तर दें..."),
    "support.requestCallbackSubtitle": ("Skip holding on the phone line. A specialized support officer will call you directly.", "फ़ोन लाइन पर होल्ड छोड़ें। एक समर्पित सहायता अधिकारी आपको सीधे कॉल करेगा।"),
    "support.requestCallbackTitle": ("Request Immediate or Scheduled Callback", "तत्काल या निर्धारित कॉलबैक का अनुरोध करें"),
    "support.scheduleAnotherCallback": ("Schedule Another Callback", "एक और कॉलबैक शेड्यूल करें"),
    "support.selectCategory": ("Select Issue Category", "समस्या श्रेणी चुनें"),
    "support.seniorAdvocate": ("Senior Customer Advocate", "वरिष्ठ ग्राहक अधिवक्ता"),
    "support.slot15Min": ("Within 15 minutes (Urgent)", "15 मिनट के भीतर (अति आवश्यक)"),
    "support.slotToday3to4": ("Today 3:00 PM – 4:00 PM", "आज दोपहर 3:00 बजे – शाम 4:00 बजे"),
    "support.slotToday6to7": ("Today 6:00 PM – 7:00 PM", "आज शाम 6:00 बजे – शाम 7:00 बजे"),
    "support.slotTomorrowMorning": ("Tomorrow Morning (10 AM – 11 AM)", "कल सुबह (सुबह 10 बजे – सुबह 11 बजे)"),
    "support.startLiveConversation": ("Start Live Conversation with a Support Specialist", "सहायता विशेषज्ञ के साथ लाइव बातचीत शुरू करें"),
    "support.startLiveDesc": ("Click any common topic below or type your message. All booking and payment details will be automatically provided to your specialist.", "नीचे किसी भी सामान्य विषय पर क्लिक करें या अपना संदेश टाइप करें। सभी बुकिंग और भुगतान विवरण आपके विशेषज्ञ को स्वचालित रूप से प्रदान किए जाएंगे।"),
    "support.startNewChat": ("Start New Chat", "नई चैट शुरू करें"),
    "support.supportSubtitle": ("Connect directly with dedicated cooperative officers for instant, personalized resolution.", "त्वरित, व्यक्तिगत समाधान के लिए समर्पित सहकारी अधिकारियों से सीधे जुड़ें।"),
    "support.ticketResolvedBanner": ("This support ticket has been resolved.", "यह सहायता टिकट हल कर दिया गया है।"),
    "support.ticketResolvedMsg": ("Issue closed successfully.", "समस्या सफलतापूर्वक बंद कर दी गई।"),
    "support.ticketResolvedTitle": ("Ticket Resolved", "टिकट हल हुआ"),
    "support.typeMessageToConnect": ("Type message to connect with human agent...", "मानव एजेंट से जुड़ने के लिए संदेश टाइप करें..."),
    "support.verifiedWhatsAppHours": ("Verified WhatsApp Business Account · Mon – Sun (7:00 AM – 11:00 PM IST)", "सत्यापित व्हाट्सएप बिजनेस खाता · सोम – रवि (सुबह 7:00 – रात 11:00 बजे IST)"),
    "support.whatsappPlaceholder": ("e.g. Please confirm if my plumber has accepted the updated flat address...", "उदा. कृपया पुष्टि करें कि क्या मेरे प्लंबर ने अपडेट किया गया फ़्लैट पता स्वीकार कर लिया है..."),
    "support.whatsappSupport": ("WhatsApp Support Redirect", "व्हाट्सएप सहायता पुनर्निर्देशन"),
    "support.whatsappSupportSubtitle": ("Chat with our verified cooperative support desk right from WhatsApp with pre-filled context.", "पहले से भरे संदर्भ के साथ व्हाट्सएप से सीधे हमारे सत्यापित सहकारी सहायता डेस्क से चैट करें।"),
    "support.whatsappSupportTitle": ("WhatsApp Business Direct Support", "व्हाट्सएप बिजनेस प्रत्यक्ष सहायता"),
    "support.zeroAiLoops": ("Zero AI / Bot Loops", "शून्य एआई / बॉट लूप"),
}

# Verify against raw_data
missing_in_translations = set(raw_data.keys()) - set(translations.keys())
print(f"Total in raw: {len(raw_data)}, Total translated: {len(translations)}")
if missing_in_translations:
    print("Missing keys:", missing_in_translations)
    raise SystemExit(1)

with open('scripts/locales_data/admin_support.py', 'w', encoding='utf-8') as f:
    f.write("# Admin, Support, Scenario, Community, Location, Map, Priority translations\n\n")
    f.write("DATA = {\n")
    for k in sorted(translations.keys()):
        en_val, hi_val = translations[k]
        f.write(f"    {repr(k)}: ({repr(en_val)}, {repr(hi_val)}),\n")
    f.write("}\n")

print("Successfully generated scripts/locales_data/admin_support.py!")
